### ISSUE TITLE
No additionnal tool menu on TB 68.4.1 / Linux kernel 5.3.0

### ISSUE THREAD

**Issue by Tarmo31** [thundernest/import-export-tools-ng#101]
Only the configuration pane is present, no menu added.
Regards.

**Comment by cleidigh** [comment]
@Tarmo31 
below is a screenshot of my Mint VM
the IETng menu addition just at the bottom.  Does your system show that?
![image](https://user-images.githubusercontent.com/25272315/79291337-60aa6880-7e9c-11ea-91ce-5c826bb5eff1.png)

**Comment by cleidigh** [comment]
@Tarmo31 
I assume you found the menu?
can we close?

**Comment by Tarmo31** [comment]
Sorry: wrong mailbox.



-------- Message transféré --------
Sujet : 	Re: [thundernest/import-export-tools-ng] No additionnal tool 
menu on TB 68.4.1 / Linux kernel 5.3.0 (#101)
Date : 	Wed, 15 Apr 2020 11:47:12 +0200
De : 	Boite01 <boite01@canales.fr>
Pour : 	Christopher Leidigh <notifications@github.com>



Dear Christopher,

I can't find the entry in my tools menu.

Thank you for your help!

Regards.

Le 15/04/2020 à 04:08, Christopher Leidigh a écrit :
