### ISSUE TITLE
HTML message body not exporting to CSV

### ISSUE THREAD

**Issue by keatsk** [thundernest/import-export-tools-ng#102]
I'm trying to export messages to a single CSV file, but the message body is just showing as "<HTML>" with no content in the CSV.

**Comment by cleidigh** [comment]
@keatsk 
thanks for the post, can you give me the versions OS/extension
thanks!
Christopher

**Comment by keatsk** [comment]
@cleidigh 
Version 4.0.4 on MacOS 10.15.3.  I also tried on a Windows 10 machine with the same result.  Thanks.

**Comment by cleidigh** [comment]
@keatsk 
I assume you're using the latest Thunderbird, 68.7?
Below is the output of to test e-mails using "Save selected messages/CSV" under Windows 10/Thunderbird 68.7
```
"test date received","Christopher Leidigh <cleidigh@gmail.com>","Test1@kokkini.net",3/27/2020 15:26, ,"<html>
<head>
<title>test date received</title>
<link rel=""important stylesheet"" href=""chrome://messagebody/skin/messageBody.css"">
</head>
<body>
<table border=0 cellspacing=0 cellpadding=0 width=""100%"" class=""header-part1""><tr><td><div class=""headerdisplayname"" style=""display:inline;"">Subject: </div>test date received</td></tr><tr><td><div class=""headerdisplayname"" style=""display:inline;"">From: </div>Christopher Leidigh &lt;cleidigh@gmail.com&gt;</td></tr><tr><td><div class=""headerdisplayname"" style=""display:inline;"">Date: </div>3/27/2020, 3:26 PM</td></tr></table><table border=0 cellspacing=0 cellpadding=0 width=""100%"" class=""header-part2""><tr><td><div class=""headerdisplayname"" style=""display:inline;"">To: </div>Test1@kokkini.net</td></tr></table><br>
<div class=""moz-text-flowed"" style=""font-family: -moz-fixed; font-size: 14px;"" lang=""x-unicode"">test
<br>
<br></div></body>
</html>
</table></div>"
"date test2","Christopher Leidigh <cleidigh@gmail.com>","Christopher Test <test1@kokkini.net>",3/27/2020 16:39, ,"<html>
<head>
<title>date test2</title>
<link rel=""important stylesheet"" href=""chrome://messagebody/skin/messageBody.css"">
</head>
<body>
<table border=0 cellspacing=0 cellpadding=0 width=""100%"" class=""header-part1""><tr><td><div class=""headerdisplayname"" style=""display:inline;"">Subject: </div>date test2</td></tr><tr><td><div class=""headerdisplayname"" style=""display:inline;"">From: </div>Christopher Leidigh &lt;cleidigh@gmail.com&gt;</td></tr><tr><td><div class=""headerdisplayname"" style=""display:inline;"">Date: </div>3/27/2020, 4:39 PM</td></tr></table><table border=0 cellspacing=0 cellpadding=0 width=""100%"" class=""header-part2""><tr><td><div class=""headerdisplayname"" style=""display:inline;"">To: </div>Christopher Test &lt;test1@kokkini.net&gt;</td></tr></table><br>
<html><head>
<meta http-equiv=""content-type"" content=""text/html; ""></head><body><div class=""moz-text-html"" lang=""x-unicode""><div dir=""ltr""><br></div>

</div></body></html></body>
</html>
</table></div>"
```
So we have to figure out what's going on differently on your machines.  Can you create two simple e-mails and export and post the output here?  
@cleidigh

**Comment by keatsk** [comment]
@cleidigh Yes it's 6.87.0.  I will switch to my Windows box and try to create a test file that I can share with you shortly.

**Comment by cleidigh** [comment]
Excellent
the other thing that would be good to capture is the Debug output (using ControlShift-J)
as well as the original message source (to look for some encoding issue)

**Comment by keatsk** [comment]
@cleidigh My apologies -- it appears this is not your bug, but a parsing problem in Excel.  Looking at the exported data in a text editor I see that it is all there.

Sorry to waste your time.  Thanks for a great tool.

**Comment by cleidigh** [comment]
no bug, no problem!
thanks, will close

**Comment by keatsk** [comment]
FYI, in case anybody else runs into this issue, MS Excel cannot handle importing multiple lines of HTML in a CSV file.  However I discovered that Google Sheets can import the CSV perfectly.

**Comment by cleidigh** [comment]
Thanks, that's good to know.
