### ISSUE TITLE
Add compatibility with TB 76+

### ISSUE THREAD

**Issue by amirhmoradi** [thundernest/import-export-tools-ng#103]
I cannot get the plugin with thunderbird 76 b1 (beta) even if I followed the  official udating guide here: [https://developer.thunderbird.net/add-ons/updating/tb78](https://developer.thunderbird.net/add-ons/updating/tb78)

I did some modifications based on the said guide, compiled the xpi and installed it in TB 76b1, but nothing shows up and the debug tools do not help more.

Do you any plans to make this great plugin compatible with TB 76+ ?

**Comment by cleidigh** [comment]
@amirhmoradi 
I am about to release an update for 68 up to I believe 74.
The major structural changes in Thunderbird 74+ will be a significant amount of work.
I am hoping I can make the evolution for 78 ESR but I don't know what I will be able to do 
for the beta releases.
Ultimately I am working with the core team to work out an integration plan for the functionality into core.  Unfortunately , there are quite a few subtleties for the conversions that are not necessarily obvious in the documentation.  For instance , everything that is an overlay has to be converted as well as most XUL UI components.

I have been doing quite a bit of work on this extension for the past number of months so I am absolutely moving forward - never enough time!

**Comment by amirhmoradi** [comment]
@cleidigh Thanks for your answer! 
That is great news, if there are small tasks I may help with, I would be more than happy to contribute to the plugin :)

**Comment by cleidigh** [comment]
@amirhmoradi 
if you are interested you can try and test/play with the hopefully last beta - b25
new help page, fully localized!
extended file support
improved index
basic shortcut key support (not yet documented, if  you're interested let me know)

https://github.com/thundernest/import-export-tools-ng/blob/v4.1.0-update/xpi/import-export-tools-ng-4.1.0-b25-tb.xpi

cheers
Christopher

**Comment by cleidigh** [comment]
@amirhmoradi 
Track here: #143
