### ISSUE TITLE
Moving local mail to Gmail 

### ISSUE THREAD

**Issue by afbendana** [thundernest/import-export-tools-ng#115]
Hi Christopher! To me, this is the best and most usesful add-on to Thunderbird, coming from an Import Export tool I used for older versions of TB. I do have a question though for a feature I can't find. Now that I've backed up all my emails from one of my GMail accounts to TB using your add-on...how do I load them into my current GMail account? Sort of like a "copy to xxxx@gmail.com" function. Thanks in advance!

**Comment by cleidigh** [comment]
@afbendana 
Thanks!
Assuming you have imported your e-mails into a local folder, you can use Thunderbirds copy command .  Highlight the e-mails  you want to Copy   and right click and you will see the copy command.
@cleidigh

**Comment by afbendana** [comment]
It's like 14000 emails...can all of them be highlighted at once?

**Comment by cleidigh** [comment]
@afbendana 
I would suggest doing them in groups.  You will be copying into a remote server so you'll be generating a lot of activity.  Maybe a few hundred at a time.  WhatEver make sure you do a
Copy NOT MOVE! You Want to make sure everything copyist correctly before deleting them locally.

**Comment by cleidigh** [comment]
@afbendana 
any progress?
Should I close this?

**Comment by afbendana** [comment]
Yes Christopher worked perfectly...thanks.

Cheers.

A.
