### ISSUE TITLE
html code instead of plain text in CSV export

### ISSUE THREAD

**Issue by Rik-2** [thundernest/import-export-tools-ng#118]
At first let me thank you for such a handy tool. 
The issue: when using "Export all messages in the folder" > "Spreadsheet (CSV)", there is html source code in the last column of the resulting file instead of body text of the message.

**Comment by cleidigh** [comment]
@Rik-2 
Thanks.
Can you identify what versions you are using (OS,Thunderbird,IETng)
Did you observe a change in this behavior from a particular version?
I just did a quick check 4.0.4 behaves the same way as 4.1.0 (using for windows 10, TB68.9)
if the e-mail is formatted in HTML, that is what is exported.

If you used to see plaintext regardless of the e-mail encoding, something changed in Thunderbird.
if the extension used to behave like that that I can investigate a lossy text output.
@cleidigh

**Comment by Rik-2** [comment]
IETng: 4.1.0-b27
TB: 68.8.1 (64 bit)
OS: W10 Pro (1909)

I have IETng installed for the first time, I haven't work with on previous versions of TB nor I have updated TB since the installation of IETng.

**Comment by cleidigh** [comment]
@Rik-2 
It was due to a HTML converter signature change.  Was not changed  in one instance.
I just posted a beta version with the fix which you can use until the next maintenance v.
https://github.com/thundernest/import-export-tools-ng/blob/v4.1.1-csv-enc-test/xpi/import-export-tools-ng-4.1.1-b1-csvt-tb.xpi
Please let me know your results.
@cleidigh

**Comment by Rik-2** [comment]
Export all files to Spreadsheet works like a charm now! Thank you!

Do you want me to test other functions of 4.1.1-b1?

**Comment by cleidigh** [comment]
@Rik-2 
excellent!  not sure how I missed it. Nothing else to test.
I have that change on a test branch with nothing else changed.
Once I get to the next Release I will roll it in.
Thanks.
@cleidigh

**Comment by Rik-2** [comment]
Great, thank you too.

**Comment by cleidigh** [comment]
@Rik-2 
FYI - I keep bugs open until they are officially merged just for tracking

**Comment by cleidigh** [comment]
Fixed Stream signature change
v10.0.0-b3

**Comment by cleidigh** [comment]
Fixed
v10.0.0
