### ISSUE TITLE
Save file with recipient/sender-email not recipient/sender-name

### ISSUE THREAD

**Issue by netpet** [thundernest/import-export-tools-ng#119]
Is it possible to save files based on their email adress not the name of the sender/recipient ?

Email adress is more reliant and offers more information to sort than the (from the sender choosen) name of the sender/recipient.

**Comment by cleidigh** [comment]
@netpet 
Thanks for the post.
Have you looked at/used the new extended file naming feature?  It does not have the ability to use the e-mail addresses, however, it utilizes tokens for a highly configurable name  format.
I could see adding ${sender-email} and ${recipient-email} as new tokens.
I assume just a straight e-mail format would be sufficient (means a '.' as part of the name)
example:
MySubject-test1@kokkini.net-11062020.eml

Of course , you can make any format with the new options.
@cleidigh

**Comment by netpet** [comment]
Dear Christopher,

yes, already all functionality tested and works like a charm with the new file naming feature, only email-address is missing and your work gets one of the seldom pieces of software, which makes life just easier not more complicated.

FYI I use it for the purpose of documentation of correspondence.  In combination with "everything" and a easy file organisation scheme I could avoid using a database based DMS. Your software was the missing link for email. Thanks in advance for further updates.

BR 
Peter


Am June 7, 2020 12:37:45 AM UTC schrieb Christopher Leidigh <notifications@github.com>:

**Comment by cleidigh** [comment]
@netpet 
Any feedback?

**Comment by cleidigh** [comment]
v10.0.0
