### ISSUE TITLE
Import profile: selecting 'use password manager': system fails

### ISSUE THREAD

**Issue by RobertBirnie** [thundernest/import-export-tools-ng#121]
Profile created in Thunderbird 68.9.0 32 bit // Win10.
Imported in Linux/Ubuntu TB 68.8.0
Imports correctly but when asked for password, if I select 'use password manager to remember this password' TB stalls. If I do not select the option then all is well and I can send and receive mails.
Problem is that each time I run TB I have to enter the password again as it is of course 'not remembered'.

**Comment by cleidigh** [comment]
@RobertBirnie 
I will have to investigate. I am not sure if the extension is the issue or Thunderbird itself.
@cleidigh

**Comment by RobertBirnie** [comment]
Yes I can do that if it would help. I will report back later today.

**Comment by RobertBirnie** [comment]
I have tested on a Win10 system using the same profile as used for my Linux/Ubuntu tests.
After doing the import, all worked well, sent/received mails and I did not have to input a password.
I deleted the Thunderbird installatio and profile and repeated the test and the result was the same.
I had already installed the profile on a laptop running Win10 and I am told it works perfectly.
If you need more tests or information let me know.

**Comment by cleidigh** [comment]
@RobertBirnie 
Thanks for doing the experiment.  we can conclude the import export on Windows implies the profile is "good".  We may assume , but not with absolute certainty,  that it is a platform issue, most likely in Thunderbird itself.  I will do a profile import on my Mint setup and see what it does.
Have you looked at the password manager to see what it contains?
@cleidigh

**Comment by RobertBirnie** [comment]
Yes but where do I find the password manager?
Will check tomorrow and respond.

**Comment by cleidigh** [comment]
@RobertBirnie 
it's under Options/Security
![image](https://user-images.githubusercontent.com/25272315/84581620-3d733b00-adb1-11ea-8ce7-2d8b1bb4d164.png)

**Comment by RobertBirnie** [comment]
@cleidigh
I looked at my Ubuntu Saved Logins page and it is empty.
On my main PC (Win10) this page shows the POP and SMTP settings.
Hope this is useful? Let me knowif I can do any tests please.
@RobertBirnie

**Comment by RobertBirnie** [comment]
@cleidigh
I looked at my Mint Saved Logins page and it is empty so Linux looks like the problem.
Hope this is useful? Let me know if I can do any tests please.
@RobertBirnie

**Comment by cleidigh** [comment]
@RobertBirnie 
I think I found a reference to the issue.
http://kb.mozillazine.org/Password_not_remembered_%28Thunderbird%29
it seems to match our scenario , give that a try.
@cleidigh

**Comment by RobertBirnie** [comment]
Cheers I will take a look tomorrow.  In  France here it's 2200 Sunday so after a good meal plus wine ready for bed!PeterSent from Samsung Tab S2
-------- Original message --------From: Christopher Leidigh <notifications@github.com> Date: 14/06/2020  19:17  (GMT+01:00) To: thundernest/import-export-tools-ng <import-export-tools-ng@noreply.github.com> Cc: RobertBirnie <peterbinic@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [thundernest/import-export-tools-ng] Import profile: selecting 'use password manager': system fails (#121) 
@RobertBirnie
I think I found a reference to the issue.
http://kb.mozillazine.org/Password_not_remembered_%28Thunderbird%29
it seems to match our scenario , give that a try.
@cleidigh

**Comment by cleidigh** [comment]
@RobertBirnie 
After a good bottle of French red wine,  I would be done with work as well 👍

**Comment by RobertBirnie** [comment]
@cleidigh
Good find! As the first point says, deleting the PKCS11.TXT file does the trick.
I have tested on Ububtu and all is well. I did not have to enter a password so assume that TBird gets this in the transferred protocol.
Thanks for your help on this. 

@RobertBirnie

**Comment by cleidigh** [comment]
@RobertBirnie 
Very good!  I will have to get a note on this  into some more documentation.
Reviews  welcome!
@cleidigh

**Comment by RobertBirnie** [comment]
@cleidigh
Mmm - not so sure about this, I tried on a laptop using Mint and it did not appear to function.
Then tried on another laptop using Ubuntu 20.4 and that did not work. Reverted this laptop to 18,04 and after several attempts that did not work either.
I need to get back to basics, use another USB key, create another profile etc. and repeat these tests.
The original setup used for tests is an office type pc and still functions correctly.
Any comments, anyone with experience?

@RobertBirnie

**Comment by RobertBirnie** [comment]
@cleidigh
Spent time checking this out on Ubuntu and Mint and have produced a doc which explains how to make the profile and install in a Linux system.
Using this guide the transfer appears stable.
Any queries drop me a note.
[Ubuntu import TBird profile from PC.docx](https://github.com/thundernest/import-export-tools-ng/files/4825951/Ubuntu.import.TBird.profile.from.PC.docx)

@RobertBirnie
