### ISSUE TITLE
Mbox file import

### ISSUE THREAD

**Issue by aonafedspoi** [thundernest/import-export-tools-ng#122]
When I attempt to import an mbox file I get the following message:  "Impossibile to import in this folder (imap or newsgroup type)".  Since it hasn't given me the opportunity to select a particular folder, I don't even know which folder it is talking about.

A related question:  Once the question above is resolved, will I be able to import all mbox files in a folder or will I need to do it one-at-a-time?

**Comment by cleidigh** [comment]
@aonafedspoi 
Most likely you have a IMAP folder selected (blue or gray if not focused) and you used the Tools/ImportExportTools NG menu. The alert is telling you the extensions does not want to import into an IMAP folder.
If you create and select a local folder with the right click pop-up menu it will then asked you how you want to import.  It will import multiple mbox files , including structure.
let me know how it goes.
@cleidigh

**Comment by aonafedspoi** [comment]
That did the trick!  Thanks very much.

**Comment by cleidigh** [comment]
@aonafedspoi 
Excellent, I like problems that are not really problems ;-)
Curiosity question:
one of the big things I did for 4.1.0 was to introduce for the first time built in help. Fully localized!
It still has a long way to go, but I do describe each menu/menu option
I am curious if you saw the help , and if so how helpful it was.
I am slowly trying to build it out more.
@cleidigh

**Comment by aonafedspoi** [comment]
I hadn't noticed it before, but it *does *look helpful.

**Comment by cleidigh** [comment]
@aonafedspoi 
good to hear!
closing
