### ISSUE TITLE
Imap syncronization issue

### ISSUE THREAD

**Issue by dexker** [thundernest/import-export-tools-ng#124]
Hi, after all, regards for you great job.
The problem it's i can import perfectly my mbox file to my local folder. ( 8 gb of 45,000 emails).
But when i try to move or copy to imap folder  ( yahoo mail ), just copy arround 1000-2000 emails, and the process stop without any fail message. so i have to take a lot of time copy in little blocks of email and its a lot of work. do you have any solution for this issue?

Thanks for your support.

**Comment by cleidigh** [comment]
@dexker 
Thanks! Glad to hear your large import went well.
The movement of e-mail to a  different folder is a Thunderbird operation , not the extension.
Moving massive amounts of emails to the server folders creates a ton of communication.
I would think you could go folder by folder.  I can think of two things to suggest:
- Go off-line for each folder, then go back online , one by one
- I think the extension below may also be of help
https://addons.thunderbird.net/en-US/thunderbird/addon/copy-folder-mod/?src=search
let me know how it goes
@cleidigh

**Comment by dexker** [comment]
@cleidigh
Thanks for your support, you are rigth its not a extension issue, teh extension works really well, but your recomendation do not work,  be cause de problem its on yahoo server,  its stop response and the process stop. its no way to solve this. i had to resignation, and copy only on blocks of 1k mail,  even do that i have to restar thunderbird each 5 times to keep copyng.
The addon of copy folder its native on version 68.9.  so this addon now its incompatible.

Thank for all
