### ISSUE TITLE
v 4.1 ENHANCEMENT - export all as PDF - change printing window as non modal or log

### ISSUE THREAD

**Issue by artofit** [thundernest/import-export-tools-ng#128]
Hi,

Currently:
When one is exporting all mails as a PDF, a print window appears for each email saved as a PDF.

It's great to export all mails as PDF, however the window is really annoying to a point that I leave the PC to this sole task.

**Solutions**
1. Change the printing windows as non modal.
2. Change to a single non modal printing window, in which it's display as a log file every printed mail.
3. Abandon the printing window(s) for a simple log file dump.

Many thanks

**Comment by cleidigh** [comment]
@artofit 
I maybe confusing this with PrintingTools which I just upgraded, I thought there was a silent mode.
will check.

**Comment by artofit** [comment]
Personnaly,
a non modal window having a count of nb of printed emails versus total, e.g. "2 of 124"
and possibly with
an utf8 log flush having start time and if completed without fealure

Log allows to know if it happens power cut, a crash, whatever, if the job is completed successfully or not.

utf8 text log file's name proposal:
_<folder>_<date now>.log

**Comment by artofit** [comment]
@cleidigh 
Fixed in v10b13
