### ISSUE TITLE
Export HTML with Attachments doesn't export attachments

### ISSUE THREAD

**Issue by jessejmorrow** [thundernest/import-export-tools-ng#13]
I have been successfully using ImportExportTools with a pre-68 version of Thunderbird to export email messages as HTML with attachments. This is a very useful and critical feature for me and is the main feature of the extension that I use.

When I upgraded TB to version 68 and installed ImportExportToolsNG, the HTML exports properly, however no attachments are exported and there are no attachment links in the HTML that is exported.

My system is Windows 10 Pro, 64-bit, Intel.

I did note that Thunderbird installed as a 32-bit version. Not sure why or if this would make a difference. All other features in Thunderbird seem to work fine.

While I am a computer programmer, I am not familiar with Thunderbird extensions at all. I did try debugging and stepping through the code and what I noted is that it never executes myTxtListener.onStopRequest68() under exportAsHtml(), which is where the code that sets up the Attachment folder is.

Thanks for the help,
Jesse

**Comment by cleidigh** [comment]
@jessejmorrow 
Thanks for finding this .  Just taking over this extension was significant work but I am not surprised I missed this.
I can reproduce this under the 32-bit version as well, I will add it to on the maintenance release list.
cheers
Christopher

**Comment by cleidigh** [comment]
@jessejmorrow 
I have the attachment error fixed.  Was a silent conditional  on String.trim the generic string function just deprecated in Gecko 68, I was totally unaware of this.  I will be posting a beta shortly.
Because you use the HTML export, I'd like to ask your question on your use method and something I found while fixing this bug:

The HTML e-mail export shows a box around image attachments and uses a source pointer to
mailbox:///..file
This only works if you are viewing the e-mail within Thunderbird which you would not normally do with an HTML export, I am assuming that you review exported e-mails in your browser of choice (not Thunderbird).  Is that correct?  When I view the exported e-mails in a browser the image link is invalid since the browser has no reference for "mailbox".  I just get a placeholder image which is the same thing if using the Thunderbird 60 or 68.  I am surprised this is the original behavior.

I think I have figured out a way to use CSS to show the image correctly if you are in the browser or Thunderbird.  I will use the mailbox if viewing in Thunderbird  and a local file link if you're in the browser.

Does the behavior above match what you see/saw with the original extension?
Is my proposed fix an improved solution?
Thanks Again

**Comment by jessejmorrow** [comment]
Hi Christopher,

Thanks for your fast help on this.

In reviewing HTML pages with attachments from the prior version, I found:

The <img> tag has src="imap://email@example.com:143/fetch ... type=image/jpeg@filename=...jpg>

There is just a placeholder icon.

Below that are links to the actual downloaded files.

Thanks,
Jesse

**Comment by cleidigh** [comment]
besides the paperclip attachment icon
do you see and attached image inside a box?
it's the mailbox:/// image pointer that I don't think can ever work in a browser that I think I should change to a link to the attachment folder, you agree that made sense?

**Comment by cleidigh** [comment]
@jessejmorrow 
WIP beta
https://github.com/thundernest/import-export-tools-ng/blob/4.0.2-Update/xpi/import-export-tools-ng-4.0.2-b1-tb.xpi

**Comment by cleidigh** [comment]
@jessejmorrow 
I figured out the correct modifications for the attachments in line.
First screenshot shows the placeholder icons outside the group box.
Second is 4.0.2-b2 which correctly saves and displays the attachments and images in the group box.
Note:  second shows a different e-mail with just an additional attachment.
(add XPi pointer)

I will clean up and submit tomorrow if possible.
![image](https://user-images.githubusercontent.com/25272315/64500531-92ff4200-d28b-11e9-8958-3ed4c62917c9.png)

![image](https://user-images.githubusercontent.com/25272315/64500609-dc4f9180-d28b-11e9-93a5-ed1739718e9a.png)

**Comment by cleidigh** [comment]
@jessejmorrow 
All set, it's in the review queue.
if you got a chance to test, let me know about any issues.
Thanks

**Comment by jessejmorrow** [comment]
Hi Christopher,

Thanks very much. So this seems to be working well!

The only thing I'm running into, which is actually separate from the original bug, is that a little modification I was making to the original code to change the attachment folder file names is no longer working.

Because I use this feature extensively and I back up the email messages to the SAME folder so that I have one long running export, I run into the problem that successive uses of the HTML Export start the Attachments folder names back at "Attachments" and "Attachments-1" so that when I copy these to my back up folder, they clobber the earlier "Attachments" and "Attachments-1" folders.

My solution to this was to make a little mod that instead names the folders by date and time: "20190914-1531."

In utils.js I had added this function:

function getAttachmentFolderName(hdr, dirPath) {
	return dateInSecondsTo8601(hdr.dateInSeconds);
}

And in exportTools.js I had modified line 1059:
- attDirContainer.append("Attachments");
+ attDirContainer.append(getAttachmentFolderName(hdr,file.path));

I stepped through the code and this line IS executed, but it has no effect on the attachments folder names, whereas it did in the prior version.

Any ideas?

Best, Jesse

**Comment by cleidigh** [comment]
@jessejmorrow 
I have to look at this more closely, but is it not possible to accomplish what you need with the file naming options?

**Comment by jessejmorrow** [comment]
It is not the exported file name that I am trying to change, it is the Attachments folders that get created to hold the exported email attachments. They are named Attachments, Attachments-1, etc. by default. I'm trying to name them 20190916-1301, etc. to match the email date and time, so that they folder names are relatively unique and won't overwrite each other.

**Comment by cleidigh** [comment]
@jessejmorrow 
yeah, I should read better.  let me take a look at it late tomorrow, I'm about to crash.
if we find something that makes sense, you could do a PR so it's in the core code.

**Comment by jessejmorrow** [comment]
Sounds good.

**Comment by cleidigh** [comment]
@jessejmorrow 
I just did a quick and dirty test adding the date of the folder name, does the screenshot below generally capture what you mean?  I just added the following code:

```JavaScript
							// cleidigh

							var dateInSec = hdr.dateInSeconds;
							var msgDate8601string = dateInSecondsTo8601(dateInSec);
							console.debug(msgDate8601string);
							attDirContainer.append("AttachmentsNG" + msgDate8601string);

							attDirContainer.createUnique(1, 0775);
							footer = '<br><hr><br><div style="font-size:12px;color:black;"><img src="data:image/gif;base64,R0lGODdhDwAPAOMAAP///zEwYmJlzQAAAPr6+vv7+/7+/vb29pyZ//39/YOBg////////////////////ywAAAAADwAPAAAESRDISUG4lQYr+s5bIEwDUWictA2GdBjhaAGDrKZzjYq3PgUw2co24+VGLYAAAesRLQklxoeiUDUI0qSj6EoH4Iuoq6B0PQJyJQIAOw==">\r\n<ul>';
							noDir = false;
						}
						var success = true;
```

![image](https://user-images.githubusercontent.com/25272315/65105118-e109f900-d9a1-11e9-9828-e2a39ea3de00.png)

I realize you copied code into the issue, but a couple of things are unclear:
- you pass in the path into the function, but you do not use it, you just return the second string.
- you said you stepped through the code, it was not clear if you got any attachment folders at all with these changes.  I don't see how they could remain the same , either you get the new name or you would get an error.  as far as that's concerned I wonder if you have a caching issue.  but you said you see the code executed so that's probably not it.
 
Anyway, I will push the above-mentioned change to another branch:
https://github.com/thundernest/import-export-tools-ng/tree/attachment-foldernames

**Comment by jessejmorrow** [comment]
Thank you, this is working.

I installed your fix and then experimented with deleting the "AttachmentsNG" string (just keeping the data folder name). At first, it would not register my changes, still exporting folders with the "AttachmentsNG" prefix. Finally, I did a full uninstall and reinstall of the extension and it picked up my changes.

So, it looks like it was a caching issue to begin with, as you guessed.

Thank you very much for this. This puts me back in operation with this useful tool!

Jesse

**Comment by cleidigh** [comment]
@jessejmorrow 
that's great.
four development always remove/ restart/reload.  there are several caches they can easily bite you.
I also use the command line option -purgecaches which purges the JavaScript cache.

If you are interested in getting this change into the code, you could do a PR.  I think at a minimum it needs some configurability.

Cheers

**Comment by cleidigh** [comment]
@jessejmorrow 
I think I can go and close this yes?
Could I poke you for a review?

**Comment by jessejmorrow** [comment]
Yes of course! Solved and closed.

**Comment by jessejmorrow** [comment]
New to github question: How do I review? 

Jesse

On 2019-09-30 22:27, Christopher Leidigh wrote:

> @jessejmorrow [1]
> I think I can go and close this yes?
> Could I poke you for a review? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3]. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/thundernest/import-export-tools-ng/issues/13?email_source=notifications\u0026email_token=ACNHELUFXCJJZLOJPG55WI3QMLNSVA5CNFSM4ITW4NTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAAACAI#issuecomment-536871169", "url": "https://github.com/thundernest/import-export-tools-ng/issues/13?email_source=notifications\u0026email_token=ACNHELUFXCJJZLOJPG55WI3QMLNSVA5CNFSM4ITW4NTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAAACAI#issuecomment-536871169", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ] @jessejmorrow I think I can go and close this yes? Could I poke you for a review? -- You are receiving this because you were mentioned. Reply to
this email directly, view it on GitHub , or mute the thread . [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/thundernest/import-export-tools-ng/issues/13?email_source=notifications\u0026email_token=ACNHELUFXCJJZLOJPG55WI3QMLNSVA5CNFSM4ITW4NTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAAACAI#issuecomment-536871169", "url": "https://github.com/thundernest/import-export-tools-ng/issues/13?email_source=notifications\u0026email_token=ACNHELUFXCJJZLOJPG55WI3QMLNSVA5CNFSM4ITW4NTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAAACAI#issuecomment-536871169", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
 

Links:
------
[1] https://github.com/jessejmorrow
[2]
https://github.com/thundernest/import-export-tools-ng/issues/13?email_source=notifications&amp;email_token=ACNHELUFXCJJZLOJPG55WI3QMLNSVA5CNFSM4ITW4NTKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAAACAI#issuecomment-536871169
[3]

**Comment by cleidigh** [comment]
@jessejmorrow 
GH is just the repository for the code and tracking issues.  Reviews are done on the actual Thunderbird extension site for the given add-on:
https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/?src=hp-dl-featured
Thanks!
