### ISSUE TITLE
Scheduled backups not occurring...

### ISSUE THREAD

**Issue by spacewrench** [thundernest/import-export-tools-ng#130]
On MacOS-10.15.5, Thunderbird-64 68.9.0, ImportExportTools NG 4.1.0:

I've been using Thunderbird and IETools on Mac for several years.  It used to remind me to back up every 7 days or so, when I close Thunderbird.  Recently, it has not been issuing the reminder.

Is this a known issue?  Is IETools calculating the "last backup" date from something that gets touched all the time?  An incorrect date got cached?  Any other way to figure this out?

Thanks!

**Comment by cleidigh** [comment]
@spacewrench 
Possibly related to #100 
I will have to investigate, I have really done nothing regarding the backup support since taking over the extension.
It is possible changes to Thunderbird have caused the issue
@cleidigh

**Comment by ikcosyw** [comment]
me too
Windows 10 build 1903 (64 bit)
Thunderbird 68.11.0 (32 bit)

I create a directory c:\Thunderbird-Backup
Nothing new goes there but my %temp% directory continually has new files:

![image](https://user-images.githubusercontent.com/28740251/89912707-ddd2b980-dbc0-11ea-8298-133b37dd7c4b.png)

**Comment by cleidigh** [comment]
@spacewrench 
@ikcosyw 
I have done some work on this for the next 78/68 Release
check out the latest:
#143

**Comment by cleidigh** [comment]
b8 as a test frequency at the end of the list
this is about 4 minutes between backups
that should show for the appropriate timing behavior

**Comment by cleidigh** [comment]
Fixed
v10.0.0
