### ISSUE TITLE
Can't export IMAP emails replied and forwarded flags

### ISSUE THREAD

**Issue by tmancini85** [thundernest/import-export-tools-ng#134]
Hello,
first of all thanks again to @cleidigh for this great add-on.

Following [his invitation](https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/reviews/1162451/), I'm opening this issue.

When I export a IMAP remote folder (in any formats: mbox, ecc.), replied and forwarded statuses of every emails are not saved (when I re-import the folder as a local one, blue and orange arrows are missing, and X-Mozilla-Status is set to 0001). I tried with different providers (gmx, live and some Italian local ones) and with different OSs and Thunderbird versions (68.10.0 32 bit with Windows 10, 60.6.1 64 bit with Ubuntu Mate), with same results.

I also tried to find in Thunderbird mbox and msf files where these flags are stored for IMAP folders. My guess is that, as I discovered [digging deep inside bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=373941#c7), flags are not stored in mbox files (often you can find  X-Mozilla-Status also in IMAP mbox files, but it is always set to 0001, and compacting the folder make it disappear without affecting blue and orange arrows). Maybe they are somehow registered in msf files, which pheraps Import-export-tools-ng doesn't find in before exporting a IMAP folder (the flags are surely stored in the remote server, but they must be also somewhere in local files, since you can see blue and orange arrows even opening Thunderbird offline).

Hope this makes sense, if you need other details I'll try to provide them. Thank you!

**Comment by cleidigh** [comment]
@tmancini85 
Thanks for the post and the kudos!
There are several things that are not exported/imported by extension such as tags,star and other things.
The status flags beyond "read" may not be easily accessible.  I have also been asked about the other items but not have an opportunity to really address.
I will see if I can investigate the level of difficulty/possibility.
@cleidigh

**Comment by tmancini85** [comment]
@cleidigh 
Thanks for the reply.
I understand it's not a simple task. If there's something I can do/try/test just tell me.

**Comment by cleidigh** [comment]
@tmancini85 
I have this fixed in b10 for the next release
follow/test
#143 
Christopher

**Comment by cleidigh** [comment]
Fixed w v10
