### ISSUE TITLE
Not working in TB 78.0

### ISSUE THREAD

**Issue by DavidBE-UK** [thundernest/import-export-tools-ng#136]
Sadly not working in the new TB 78.0 released today. Add-ons Manager marks it as incompatible.

**Comment by cleidigh** [comment]
@DavidBE-UK 
Unfortunately due to the large number changes required for 78 it will be sometime for such a Release.
I am working on bringing some of the functionality into core, but that is still lots of work.
I will be working towards this, but it's a big slog.
@cleidigh

**Comment by W4RH4WK** [comment]
Is there a way to support this project via donations?

**Comment by cleidigh** [comment]
@W4RH4WK 
there is a donate button on the extension on page .  I am donating half of all contributions to the ALS Association.
I am currently working on two other extensions and will return to start the conversion of IET NG for 78
soon, however , this should be a nontrivial effort.
@cleidigh

**Comment by Graveen** [comment]
@cleidigh  Thank you, btw.

**Comment by cleidigh** [comment]
@Graveen Thanks!
@W4RH4WK 
@DavidBE-UK 
Don't worry, 78 support is next on my list.
just have to finish ColumnsWizard for 68
I will post a notice as soon as I have beta!
Christopher

**Comment by cleidigh** [comment]
All
I am starting the conversion!
Track: #143 
Christopher

**Comment by thechaosroad** [comment]
@cleidigh 
Hey there, last version not compatible with latest TB 91
Will be released?
