### ISSUE TITLE
Need to confirm features before use

### ISSUE THREAD

**Issue by Researchguy007** [thundernest/import-export-tools-ng#139]
Hi All,

I need to confirm how this add-in works before I use it. I want to import an inbox archive that has tens of thousands of emails. 

First, I want to make sure that this archive does not get imported into any of my existing folders -- getting intermixed with my existing emails -- but *creates its own folder upon import.*

Second, will I be able to delete individual emails from the archive and then re-export to a new MBOX file?

TIA!

Researchguy007

**Comment by cleidigh** [comment]
@Researchguy007 
Thanks for the post.
First, the extension expects that you choose a local folder ( create as you like)
for where you will import.
this will be separate from your inbox.
The most important question is  What is the format and structure of what you wish to import.
there are several edge conditions doing large imports, I have another experimental extension
that has been very effective large EML imports.  once I understand the formats you are using
we can figure out which is the best approach
@cleidigh

**Comment by Researchguy007** [comment]
Thank you so much! 
I don't know much about the format and structure except that it is an MBOX from Gmail. I noticed some warning about tags not being part of the normal structure but someone can write code to handle them. I shouldn't need any tag data, because I exported based on the presence of a single tag. so I already know that all the emails have that tag. 
The MBOX file is about 1.7 GB. I would give you direct access to it so you could be in a better position to advise me, but it contains privileged legal information.

**Comment by cleidigh** [comment]
@Researchguy007 
No need for the access, totally understandable.
Importing the single m box file should be okay, assuming we did not hit any 'oddities.
steps are:
- Create an import folder under local folders
- Right-click on the new folder
- Choose IET NG/Import mbox file
- choose the first option in the dialogue below
- it should report all the e-mail
- after that you can  reexport whatever you need
Christopher

![image](https://user-images.githubusercontent.com/25272315/89454517-ce6def00-d72e-11ea-8ac4-2c1cb5957206.png)

**Comment by Researchguy007** [comment]
Thank you so much! I will try it and get back with you.

**Comment by Researchguy007** [comment]
Stupendous! 5500 emails right where I expected them to be ... and able to multi-select and print to PDF.
Thank you again!
Naturally ... I have another question, or feature request. Is there a way to multi-select emails and print them to PDF so that the emails would be concatenated into a single PDF, so I don't have to keep confirming the folder that each email PDF needs to be saved to? I can work around this limitation using MboxViewer, available on SourceForge. I helped power-test that application and generate that feature. It allows printing multiple emails to a potentially very tall HTML page, which can then be printed to PDF. But it would be nice if the process were more direct -- skipping the HTML step.

**Comment by cleidigh** [comment]
@Researchguy007 
sorry for the delayed response, forgot to answer your question.
currently I am not sure the  PDF library supports concatenating files.
you are not the first to request this I will be looking into it in the future.
First have to get to 78!
Christopher
