### ISSUE TITLE
Bug: Importing to a non-active folder imports the currently active folder.

### ISSUE THREAD

**Issue by jtagcat** [thundernest/import-export-tools-ng#140]
1. Have folder A open
1. Right click on folder B, Import all messages from a directory
1. Items are imported to folder A, instead of the expected folder B

**Comment by cleidigh** [comment]
@jtagcat 
I was able to reproduce your issue thanks!
I will have to add a right click override for the selected folder.
@cleidigh

**Comment by cleidigh** [comment]
@jtagcat 
b4  should now fix this
check out:
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.2/xpi/import-export-tools-ng-10.0.2-b4-tb.xpi
thanks
@cleidigh

**Comment by cleidigh** [comment]
Fixed:
v10.0.2
