### ISSUE TITLE
Unable to add import export add-on to Thunderbird 78.2.1

### ISSUE THREAD

**Issue by Kayd55** [thundernest/import-export-tools-ng#144]
Hi Chris- I  recently installed Thunderbird 78.2.1 on Mac OS High Sierra 10.13.6 with the goal to export Gmails to CSV.

I do NOT have any previous versions of Thunderbird, version 78.2.1 is my first.

I am unable to add the adds-on" ImportExportTools NG" to Thunderbird and I am getting the error that is not compatible with the Thunderbird version- see attached screenshot.

 In addition, the ImportExport Tool adds -on-page is grayed-out, why is this happening and how can I add the adds on tool to thunderbird? Please advice

![Import_export Tools Adds on greyed-out](https://user-images.githubusercontent.com/70857750/92333693-84419b80-f055-11ea-9263-e0fabbf6f9a8.png)

**Comment by cleidigh** [comment]
@Kayd55 
Currently the v4.1.0 extension version is only compatible up to 68.
I am right in the middle of doing the update for 78
you can track and actually download beta already but I cannot guarantee
everything is working yet.
Latest information/link:
#143 
Christopher
