### ISSUE TITLE
Exporting entire threads?

### ISSUE THREAD

**Issue by grafiti14** [thundernest/import-export-tools-ng#147]
Hi!  Is it possible to export entire threads of an email, including responses from me to the sender?  If so, what is the best way to import?  I would love to export all of my email threads to a folder on my PC that I can read, without having to import them back into Thunderbird.  It looks like HTML is the best way to do this - correct?
thanks!
Kristi

**Comment by cleidigh** [comment]
@grafiti14 
I think I understand your question to be how do I export such that you can use the output WITHOUT Thunderbird
or anything else special on another PC.  Assuming that's correct:
You have three choices:
HTML, PDF as well as plain text.

One thing you should understand is that these types of exports can currently only be done for one folder  at a time.
This is a limitation that I am hoping to improve soon.
There is also the possibility of creating an  HTML index that can optionally be generated.
as you mentioned HTML is probably the way to go
Christopher
