### ISSUE TITLE
No Backup take Place when TB is closed via File - Exit

### ISSUE THREAD

**Issue by Boersenfeger** [thundernest/import-export-tools-ng#154]
Hi, a backup only takes place when TB is closed via the X. If you close the program via File-Exit, no backup is started. Is this intended or could it be improved?
Sorry for bad English. Im using Deepl for Translate
Thx and Greets Bo

**Comment by cleidigh** [comment]
@Boersenfeger 
Thanks!
backup problems are next to my list!
there are several I will combine and post on referencing this and other similar backup issues
Christopher

**Comment by cleidigh** [comment]
@Boersenfeger 
if you can try this the beta File/exit 
should work
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.2/xpi/import-export-tools-ng-10.0.2-b1-tb.xpi

**Comment by Boersenfeger** [comment]
Hi, Christopher,
thank you so much, this fixed the Problem
Greetz
Bo

**Comment by Boersenfeger** [comment]
Hi Christopher, when using the beta version it seems that the back-up planning does not work correctly now. It is now set that a backup should be created daily. It is a fact that a backup is created every time you quit the program, no matter if you quit the program by using the closing cross or by using File quit.
Maybe you can check this again.
Thx

**Comment by cleidigh** [comment]
@Boersenfeger 
yes I realized I fixed the exit issue ,but forgot to remove the logic to run each time for testing
I will fix in the next beta
Christopher

**Comment by cleidigh** [comment]
@Boersenfeger 
b2 should fix the schedule and the  exit
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.2/xpi/import-export-tools-ng-10.0.2-b2-tb.xpi

**Comment by Boersenfeger** [comment]
Hi Christopher, thank you, the problem is fixed! 
Note: I posted the problem in the German Thunderbirdforum and I'm regularly updating your phenomenal support. Thanks so lot!

https://www.thunderbird-mail.de/forum/thread/84706-tb-78-0-inkompatible-add-ons/?postID=467802#post467802

**Comment by cleidigh** [comment]
@Boersenfeger 
Thank you very much!
now on to next conversions ;-)
Tsuch
Christopher

**Comment by cleidigh** [comment]
Fixed:
v10.0.2
