### ISSUE TITLE
Import choices are disabled

### ISSUE THREAD

**Issue by mcdan333** [thundernest/import-export-tools-ng#156]
I can't select "Import mbox file" or "Import messages" because the menu options are grayed out / disabled.

Thunderbird 68.10.0 (64-bit Linux Mint)
ImportExportToolsNG 10.0.0

**Comment by cleidigh** [comment]
@mcdan333 
do you have a local folder  selected?
from my mintVM
Christopher
![image](https://user-images.githubusercontent.com/25272315/94999703-330bc580-0589-11eb-93c5-0e9b2bfa6729.png)
