### ISSUE TITLE
IET NG 10.0.0 not appearing under Add-on Preferences in the Add-ons menu, nor taking Backups

### ISSUE THREAD

**Issue by JohnHag** [thundernest/import-export-tools-ng#157]
Hi,
I'm running Thunderbird 68.10.0 (64-bit) under Linux Mint 20 Ulyana.
After upgrading to IET NG 10.0.0 it didn't appear under Add-on Preferences in the Add-ons menu, however it did show in 'Manage Your Extensions' .
This was the case whether installed by 'Find more extensions' and 'Add to Thunderbird', or by 'Install Add-on From File'.
It also failed to run 'Import Export Tools NG- Backup' when 'Quit'-ing TB.
I uninstalled 10.0.0, reinstalled 4.1.0 and can now take daily backups, etc.
Only tangentially connected to the above - IET NG often fails to take a backup because the script that runs my daily backups closes TB a second or two short of 24 hours since the last backup. Allowing a tolerance of a minute or two would save me a load of hassle.
Regards,
John

**Comment by cleidigh** [comment]
@JohnHag 
I am now working on the set of backup issues.  it would be great if you can help with some testing.
I have to primarily work on window so doing debugging on Mint is very tedious
I believe I have fixed the backup for Windows with 10.0.1  ,but L/OS X have different shutdown paths

concerning your shutdown script, I can easily add some hysteresis to the backup time no reason  it has to be exact
thanks
Christopher

**Comment by cleidigh** [comment]
@JohnHag 
b2 should fix the schedule and the  exit
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.2/xpi/import-export-tools-ng-10.0.2-b2-tb.xpi

also added -5m hysteresis for backup time
Christopher

**Comment by cleidigh** [comment]
@JohnHag 
Any chance you have had a chance to try b2 ?
C

**Comment by JohnHag** [comment]
Hi Christopher,

I tested it a couple of hours after your last email.

I assume you haven't got my email reply so I'll re-send it shortly.

Regards,

John

**Comment by JohnHag** [comment]
Hi Christopher,

It appears I only replied to your personal email and not the reply 
address - sorry.

Regards,

John

**Comment by cleidigh** [comment]
@JohnHag 
thanks for this testing.  not sure how we got stuff into e-mail but going forward let's keep her all here
I would like to regroup a bit to make sure we discuss each issue clearly:
1 - extension options menu access
2 - backups not occurred when using File/exit
3 - backups not occurring regardless of exit mode
4 - backup timing relative to your script

b2 should address all of these however you seem to indicate there are still issues and I just want to clarify on each one
1 - I got 68 backup on my mint VM (v19?) - you could see the options under the main menu/tools
    I recently realized from a user people are going to the tools menu under the hamburger menu
    the extension just not install in the menus there.  you can get to options from the main menu as shown below
    or have also added the options you every other menu (contexts) I am hoping this explains your issue
    it's a separate menu option currently-may be able to improve later
2 - I verified that the extension did not trigger any backups when file/exit was used.  b2 specifically fixers this
    and I have several other people that have verified this. I do not think you mentioned this specifically
    but it is obviously relevant to good backup operation
3 - I believe this is the most significant issues you face.  
    with many changes to support 78/68 were several issues with the backups
    I have just retested Windows as well as Mint  with success I also added
    Time Now so you can test backup on immediate exit
4 - there is now five minutes hysteresis on the backup time hopefully that makes your scripts work every time

hopefully this clarifies things and helps us us to know what is working and what is not
Christopher
![image](https://user-images.githubusercontent.com/25272315/96792299-1d3f3280-13c8-11eb-8df0-6b9527a36187.png)

**Comment by JohnHag** [comment]
Hi Christopher,

I re-downloaded b2 from github and reinstalled it.

I can't get to the IET menu from the hamburger but I can from the Tools 
drop-down.

Once I'd set it to TestNow it took a backup however I closed TB - using 
File => Quit; hamburger -> Quit; top right corner X; right click, Close 
on the Taskbar; and xdotool key --window {TB window ID} --clearmodifiers 
ctrl+q (from my script).

I'll keep an eye on it over the next few days so I can confirm that the 
backup time tolerance is working OK - I've no reason to suspect it won't.

A thought:
I had initially assumed that TestNow would initiate a backup when OK was 
pressed and that it would then reset to its previous value.
However, as it doesn't take the backup until TB is closed, and the value 
persists over a reload, then it's effectively a 'backup on every close' 
(until it's reset manually).
That's quite a useful option. You may want to rename it to highlight the 
fact.

Many thanks for your effort in maintaining and improving IET.

If I can ever be of assistance - beta testing or whatever - just let me 
know.

Regards,

John

**Comment by cleidigh** [comment]
@JohnHag 
excellent thanks
you are correct about the TimeNow I put it in for testing
with no thought of the name
I am thinking of keeping it and changing to `Backup on exit`
how does that sound?
looking forward to hearing your script works

**Comment by JohnHag** [comment]
Hi Christopher,

'Backup on exit' sounds fine.

My script runs @ 22:30 each evening and successfully ran version 4.1.0 
yesterday before I re-installed b2.

I'll take a manual 'Backup on exit' before today's run - it's already a 
useful feature.

The script should then take a backup tomorrow and on subsequent runs.

I'll monitor the IET backup times and script TB close times and get back 
to you once I've got some evidence.

Regards,

John

**Comment by JohnHag** [comment]
Hi Christopher,

Just to confirm, IET backs up (on a 1 day cycle) when TB closedown time 
is equal to or less that 24 hours after previous backup.

Regards,

John

IET Last backup @ 23/10/2020, 22:30:10
run_FFS TB close @ 2020_10_24 @ 22:30:10
backup taken

IET Last backup @ 24/10/2020, 22:30:10
run_FFS TB close @ 2020_10_25 @ 22:30:09
backup taken

IET Last backup @ 25/10/2020, 22:30:09

**Comment by cleidigh** [comment]
Fixed:
v10.0.2
