### ISSUE TITLE
Greek Characters

### ISSUE THREAD

**Issue by djosain** [thundernest/import-export-tools-ng#158]
Hello, i am trying to extract a mail as plain text with attachments in a folder. 
It is exporting with wrong encoding in txt for all the Greek Characters.
If i extract as PDF it is OK but without attachments, i have to do it separately. 
Any ideas?

**Comment by cleidigh** [comment]
@djosain 
Thanks for the post, my first Greek issue (my wife is from Crete ;-)
this appears to be the same encoding issue for Japanese referenced by #153 
I working on it and will try and post beta shortly
Yasou!
Christopher

**Comment by cleidigh** [comment]
@djosain 
I have something for you to try (load the zip manually)
if you can send a screenshot good or bad that would be helpful
[import-export-tools-ng-10.0.1-b1-etest-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5331238/import-export-tools-ng-10.0.1-b1-etest-tb.zip)

**Comment by djosain** [comment]
[image: image.png]
When i am trying to save as text it is ok with the zip you sent me.
When i am trying to save as text (with Attachments) it is like the image.
Also ...greeting to your wife from Athens.
Greek women need a lot of patience ...

Στις Τρί, 6 Οκτ 2020 στις 6:32 π.μ., ο/η Christopher Leidigh <
notifications@github.com> έγραψε:

**Comment by cleidigh** [comment]
@djosain 
Apithano, progress!
your image attachment did not work if you repost
meanwhile I will investigate the attachments

**Comment by djosain** [comment]
![1](https://user-images.githubusercontent.com/9141181/95246032-98c3b000-081c-11eb-97e6-d7788695269a.png)

**Comment by cleidigh** [comment]
@djosain 
could you possibly send me an example e-mail in Greek with a dummy attachment as well as the example screenshot
my first look was unsuccessful,possibly more subtle issue
what was the type of attachment?

**Comment by djosain** [comment]
Check your email

**Comment by cleidigh** [comment]
excellent, because I was able to reproduce with your email, able to get it
here is my output now of your e-mail 
![image](https://user-images.githubusercontent.com/25272315/95377276-56e44980-08b0-11eb-8eab-06196038922d.png)

try 
[import-export-tools-ng-10.0.1-b1-etest2-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5343316/import-export-tools-ng-10.0.1-b1-etest2-tb.zip)

**Comment by djosain** [comment]
Yeap, it worked smoothly! ... Thank you

**Comment by cleidigh** [comment]
@djosain 
thanks for your help was important to solve
I will be posting an official b1 shortly

**Comment by cleidigh** [comment]
@djosain 

I'm finally ready to release .  if anyone is able to do a couple quick checks that would be great, then I will post for review
thanks!
Christopher

https://github.com/thundernest/import-export-tools-ng/blob/v10.0.1/xpi/import-export-tools-ng-10.0.1-b1-tb.xpi

**Comment by cleidigh** [comment]
Fixed v10.0.1
