### ISSUE TITLE
bug in scheduled backups

### ISSUE THREAD

**Issue by 4sv6foto** [thundernest/import-export-tools-ng#159]
Release 4.0.4 of the Thunderbird addon import-export-tools was the last version, where scheduled backups work correctly. Also with the actual version 10.0.0 there is no action, if it's time to make an automatic scheduled backup. Changing the scheduling parameters, like periodicy, backup file path and others, don't change the situation. The backingup-job do not run. Thunderbird Version 68.12.1 with Enigmail on Mac OS 10.11 is used, acutal with falling back to import-export-tools Version 4.0.4.

**Comment by cleidigh** [comment]
@4sv6foto 
thanks, I working through these issues, a backup problem has actually been posted
clarification:
4.1.0 also does not work?

**Comment by cleidigh** [comment]
@4sv6foto 
v10.0.1 works on my Mint VM at least for my first test
can you give that to try?
Christopher

**Comment by 4sv6foto** [comment]
Sorry, Backup is not working.

Testing on OSX 10.13; TB 68.12.1; today October 16:
1. Deinstallation Version 4.0.4
2. Installation Version 10.0.1.
3. Thunderbird restart
4. Thunderbird exit => i-e-tools-ng should make a backup (period type = daily; last backup = October 13)
5. no Backup is working

Regards, Dominik

**Comment by cleidigh** [comment]
@4sv6foto 
what was the exact method used to exit Thunderbird?
I think there's still an issue with some exit methods

**Comment by 4sv6foto** [comment]
German has been used normally. For testing I changed language to English (US) for a common understanding. I used the exit-method under toolbar on top <Thunderbird> - <Quit Thunderbird> or the keys cmd + Q. With Version newer than 4.0.4 no backup will run, also when backup period is expired. With Version 4.0.4, before Thunderbird disappears after quit, the decision window from i-e-tools-ng appears, if backup period is expired and a backup will fall due.

I noticed after upgrading from Version 4.0.4 to 10.0.1 and afterwards deinstalling Version 10.0.1, the decision window appears a last one, if backup period is expired. TB needs to be restarted to execute the deinstallation. On the other hand, when installing and deinstalling Version 10.0.1 on a blank Thunderbird without i-e-tools, there is no backup during restarting TB. For this reason I suppose <restart> and <cmd + Q> could have a different code.

**Comment by cleidigh** [comment]
@4sv6foto 
I think that was the issue.  given that I am not a big Mac user and I am disabled program by voice
the methods I used to exit are sometimes different than others
to fix for windows still File/exit looks like it takes care of the OS X Command-Q also
I will post b2 shortly

**Comment by cleidigh** [comment]
@4sv6foto 
b2 should fix the schedule and the  exit
tested  the commandQ as well as the red ball
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.2/xpi/import-export-tools-ng-10.0.2-b2-tb.xpi

**Comment by 4sv6foto** [comment]
Compliments -  that's an ultra fast updtate! I will test Version 10.0.2 on Sunday, because I can't change period faster than daily and my last backup was some hours ago.

**Comment by cleidigh** [comment]
you can actually use the last test option
Testnow
for just that test

**Comment by 4sv6foto** [comment]
Great, it works! I updated to V 10.0.2-b2 and period <TestNow>. Then quit TB with cmd + Q and the backup was running as expected. Many thanks, Dominik.

**Comment by 4sv6foto** [comment]
The period was <TestNow>.

**Comment by 4sv6foto** [comment]
The period was TestNow.

**Comment by cleidigh** [comment]
Excellent
this was an important issue to solve
I appreciate testing help
I will clean up and post for review

**Comment by cleidigh** [comment]
Fixed:
v10.0.2
