### ISSUE TITLE
Version 4.03, export all messages/as single text file produce HTML format

### ISSUE THREAD

**Issue by c3pee** [thundernest/import-export-tools-ng#16]
after updating to ng-Version 4.03:
export all messages in folder/as single text file produce a file in  HTML format.

**Comment by cleidigh** [comment]
@c3pee 
Thanks for posting this issue!  I can reproduce the problem.  It looks like an interface may have changed on me.  I will work on it for 4.0.4 and report my progress here.  I always try to post a beta as soon as I can before a new submission.

**Comment by cleidigh** [comment]
@c3pee 
I am going to do more testing, but I have a beta.  Indeed an interface change that silently failed.
XPI below.

https://github.com/thundernest/import-export-tools-ng/blob/master/xpi/import-export-tools-ng-4.0.4-b2-tb.xpi

**Comment by c3pee** [comment]
Thank you guys for this fast fixing!
With _import-export-tools-ng-4.0.4-b2-tb.xpi_ the single text file export is working again. (for me and my parser...)

**Comment by cleidigh** [comment]
@c3pee 
Thanks!
@cleidigh
