### ISSUE TITLE
ImportExportTools NG has disappeared from my tools menu ...

### ISSUE THREAD

**Issue by Nikilet2** [thundernest/import-export-tools-ng#160]
and I can not access it. I've clicked on everything to see if I can find it. I use this all the time, and it hasn't been that long since I used it and it was fine. Now it's just not there.

I have Windows 10 and presently have Thunderbird 68 (64bit).

Hope someone can help me. I have an extensive folder system and export the really important folders so that I always have a backup.

**Comment by Nikilet2** [comment]
Solved ... I decided to do the update 68.12.1 to Thunderbird and after I did that, ImportExportTools NG appeared on my right-click menu again. 

I haven't been keeping TBird up to the very latest version because about a month ago that caused me to lose a couple of the add ons that I love and use.

**Comment by cleidigh** [comment]
@Nikilet2 
Great!
shall I close?
Christopher

**Comment by Nikilet2** [comment]
Yes, thank you.
