### ISSUE TITLE
in CSV export (all messages in folder) the date format has changed

### ISSUE THREAD

**Issue by Frank-from-Berlin** [thundernest/import-export-tools-ng#161]
When exporting all messages from a folder to a csv file in the old version of import-export-tools-ng I've got the messages' dates in my locale. Example (from 1 month ago): 
"Message headline";"Sent from <mail@domain.de>";"Sent to <xyz@domain.de>";06.08.2020 16:23; ;

Now I get:
"Message headline";"Sent from <mail@domain.de>";"Sent to <xyz@domain.de>";9/21/2020 17:49; ;

Unfortunately Excel, Google Sheets etc. cannot handle the import of dates in this format in my local version. 

Thanks for this great tool and the effort you're putting into it, Christopher!

**Comment by cleidigh** [comment]
@Frank-from-Berlin 
Thanks!
I have added so many new date options I must've missed a patch for the CSV
shouldn't be too hard to locate.
I am already working on the point release
I need to finish up to other bugs so it might be a couple days
Christopher

**Comment by cleidigh** [comment]
@Frank-from-Berlin 
okay I have a test version for you
[import-export-tools-ng-10.0.1-b1-csvdtest-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5344546/import-export-tools-ng-10.0.1-b1-csvdtest-tb.zip)

I did two things
"I restored" the default CSV date format - it's a new method but should be same result
I also had the ability to utilize the custom index date format so you can customize both the date and time
utilizing the custom date format specification described in the help
this test set on the first Tab
![image](https://user-images.githubusercontent.com/25272315/95398374-8d7f8b80-08d3-11eb-8b02-3220f3eda576.png)

and here is the result of this custom format
![image](https://user-images.githubusercontent.com/25272315/95398457-d8010800-08d3-11eb-9e71-2da80b7a3688.png)

now this is the default is no index format is set (matches the original format)
![image](https://user-images.githubusercontent.com/25272315/95398863-e865b280-08d4-11eb-8efc-fb2bb3d8b1fa.png)
