### ISSUE TITLE
Export to plain text with UTF-8 produces unknown encoding!

### ISSUE THREAD

**Issue by Honza-G** [thundernest/import-export-tools-ng#163]
I am using Thunderbird-81.0 on "Linux Mint 19.1 Tessa". Recent update to 10.0 release brought a very bad surprise to me.
Mails exported as plain text (without attachment) have all non-ascii characters encoded in strange format, not in UTF-8 as set in configuration. See example:
This is octal dump of the first row of the text file with exported mail (using current release of 
import-export-tools-ng :
`
0000120  123 165
          S   u
0000140 142 152 145 143 164 072 040 123 120 040 067 064 070 067 067 063
          b   j   e   c   t   :       S   P       7   4   8   7   7   3
0000160 065 040 055 040 047 123 122 126 055 114 130 117 123 110 112 116
          5       -       '   S   R   V   -   L   X   O   S   H   J   N
0000200 113 104 105 126 064 060 063 040 055 040 166 172 156 151 153 040
          K   D   E   V   4   0   3       -       v   z   n   i   k
0000220 303 203 302 203 303 202 302 272 303 203 302 204 303 202 302 215
        303 203 302 203 303 202 302 272 303 203 302 204 303 202 302 215
0000240 164 165 040 050 061 170 051 047 040 142 171 154 040 160 303 203
          t   u       (   1   x   )   '       b   y   l       p 303 203
0000260 302 205 303 202 302 231 151 144 303 203 302 204 303 202 302 233
        302 205 303 202 302 231   i   d 303 203 302 204 303 202 302 233
0000300 154 145 156 040 166 141 303 203 302 205 303 202 302 241 303 203
          l   e   n       v   a 303 203 302 205 303 202 302 241 303 203
0000320 302 203 303 202 302 255 040 163 153 165 160 151 156 303 203 302
        302 203 303 202 302 255       s   k   u   p   i   n 303 203 302
0000340 204 303 202 302 233 012
        204 303 202 302 233  \n
`
And this is the same dump of the same mail exported via the same addon, release 4.1 
`
0000000 123 165 142 152 145 143 164 072 040 123 120 040 067 064 070 067
          S   u   b   j   e   c   t   :       S   P       7   4   8   7
0000020 067 063 065 040 055 040 047 123 122 126 055 114 130 117 123 110
          7   3   5       -       '   S   R   V   -   L   X   O   S   H
0000040 112 116 113 104 105 126 064 060 063 040 055 040 166 172 156 151
          J   N   K   D   E   V   4   0   3       -       v   z   n   i
0000060 153 040 303 272 304 215 164 165 040 050 061 170 051 047 040 142
          k     303 272 304 215   t   u       (   1   x   )   '       b
0000100 171 154 040 160 305 231 151 144 304 233 154 145 156 040 166 141
          y   l       p 305 231   i   d 304 233   l   e   n       v   a
0000120 305 241 303 255 040 163 153 165 160 151 156 304 233 012
        305 241 303 255       s   k   u   p   i   n 304 233  \n
0000136
`

The second one is OK.
(Sorry, I do not know hoe to paste nonproporcional font here.)

**Comment by Honza-G** [comment]
Another trial to paste - try yourself to convert into non-proporcional font (to see common  output of  'od -bc'  command):
BAD (r.10.0):

0000138  123 165
           S   u
0000140 142 152 145 143 164 072 040 123 120 040 067 064 070 067 067 063
          b   j   e   c   t   :       S   P       7   4   8   7   7   3
0000160 065 040 055 040 047 123 122 126 055 114 130 117 123 110 112 116
          5       -       '   S   R   V   -   L   X   O   S   H   J   N
0000200 113 104 105 126 064 060 063 040 055 040 166 172 156 151 153 040
          K   D   E   V   4   0   3       -       v   z   n   i   k
0000220 303 203 302 203 303 202 302 272 303 203 302 204 303 202 302 215
        303 203 302 203 303 202 302 272 303 203 302 204 303 202 302 215
0000240 164 165 040 050 061 170 051 047 040 142 171 154 040 160 303 203
          t   u       (   1   x   )   '       b   y   l       p 303 203
0000260 302 205 303 202 302 231 151 144 303 203 302 204 303 202 302 233
        302 205 303 202 302 231   i   d 303 203 302 204 303 202 302 233
0000300 154 145 156 040 166 141 303 203 302 205 303 202 302 241 303 203
          l   e   n       v   a 303 203 302 205 303 202 302 241 303 203
0000320 302 203 303 202 302 255 040 163 153 165 160 151 156 303 203 302
        302 203 303 202 302 255       s   k   u   p   i   n 303 203 302
0000340 204 303 202 302 233 012
        204 303 202 302 233  \n

GOOD (r. 4.1):
0000000 123 165 142 152 145 143 164 072 040 123 120 040 067 064 070 067
          S   u   b   j   e   c   t   :       S   P       7   4   8   7
0000020 067 063 065 040 055 040 047 123 122 126 055 114 130 117 123 110
          7   3   5       -       '   S   R   V   -   L   X   O   S   H
0000040 112 116 113 104 105 126 064 060 063 040 055 040 166 172 156 151
          J   N   K   D   E   V   4   0   3       -       v   z   n   i
0000060 153 040 303 272 304 215 164 165 040 050 061 170 051 047 040 142
          k     303 272 304 215   t   u       (   1   x   )   '       b
0000100 171 154 040 160 305 231 151 144 304 233 154 145 156 040 166 141
          y   l       p 305 231   i   d 304 233   l   e   n       v   a
0000120 305 241 303 255 040 163 153 165 160 151 156 304 233 012 123 165
        305 241 303 255       s   k   u   p   i   n 304 233  \n   S   u

**Comment by cleidigh** [comment]
@Honza-G 
I am currently working on this. see #153 
for a link to a test version 
that should fix their main encoding problem
but there is still an issue if also exporting attachments

**Comment by cleidigh** [comment]
@Honza-G 
@djosain
@midoribashikk 
@Hideki2103 
@Shoko-1234 

I just posted what I believe fixes the final issue on encoding
see #158 for the link 
this also affects HTML output
if I get confirmation after effects for both Japanese and Greek
I will be able to put out a revision officially

**Comment by midoribashikk** [comment]
@cleidigh 
I tried import-export-tools-ng-10.0.1-b1-etest2-tb.zip.
It worked very well. Thank you!

**Comment by cleidigh** [comment]
@midoribashikk 
thank you very much testing!
I will be posting an official beta soon

**Comment by cleidigh** [comment]
Fixed v10.0.1

**Comment by Honza-G** [comment]
Well, import-export-tools-ng-10.0.1-b1-etest2-tb.zip looks good. Thnx. H.
 
----------------------------------------------------------
One World. One Web. One Program. - Microsoft promotional advertisement
Ein Volk, ein Reich, ein Fuhrer! - Adolf Hitler
 
______________________________________________________________
> Od: "Christopher Leidigh" <notifications@github.com>
> Komu: "thundernest/import-export-tools-ng" <import-export-tools-ng@noreply.github.com>
> Datum: 07.10.2020 21:31
> Předmět: Re: [thundernest/import-export-tools-ng] Export to plain text with UTF-8 produces unknown encoding! (#163)
>
 
@Honza-G <https://github.com/Honza-G>
 @djosain <https://github.com/djosain>
 @midoribashikk <https://github.com/midoribashikk>
 @Hideki2103 <https://github.com/Hideki2103>
 @Shoko-1234 <https://github.com/Shoko-1234>
I just posted what I believe fixes the final issue on encoding
 see #158 <https://github.com/thundernest/import-export-tools-ng/issues/158> for the link
 this also affects HTML output
 if I get confirmation after effects for both Japanese and Greek
 I will be able to put out a revision officially
