### ISSUE TITLE
I want to import *.mbs  data into Thunderbird

### ISSUE THREAD

**Issue by custos2003** [thundernest/import-export-tools-ng#167]
Hello,

is there any way to import my OperaMail E-Mails into Thunderbird?
I already created *.mbs files but I cant import these files with import-export-tools-ng.

can anybody help?

Thanks in advance!

**Comment by cleidigh** [comment]
@custos2003 
to be honest I have never used Opera so I am unfamiliar with its export achievement abilities
I took a quick look and it sounds like it might utilize mbox files with a mbs extension
can you create sample and post here?
otherwise I have no way to test if it needs conversion
Christopher

**Comment by custos2003** [comment]
Hello cleidigh,

sorry for my rude comment in the rating area. I will change that!

here is a sample.

Thanks for helping

[test.zip](https://github.com/thundernest/import-export-tools-ng/files/5387073/test.zip)

**Comment by cleidigh** [comment]
@custos2003 
Sorry  accepted, I just expect people to describe their problem not just gripe ;-)
first question - did you check out help I added in the last version, it still needs much more content, but it covers all of the menu options as well 

the good news is the individual final imports fine.  the file is accepted as a mbox format file 
which can be imported by the `Import mbox file` menu option

next question:
what is the folder structure you have ?
are the messages in one file or separate?

![image](https://user-images.githubusercontent.com/25272315/96172998-342be380-0ef5-11eb-99f1-889dcfc61b5f.png)

**Comment by custos2003** [comment]
at the moment thunderbird is completely untouched. there is no structure at the moment. I have to mbs files (inbox and paper bin)

TB looks like this:

![TB](https://user-images.githubusercontent.com/72941044/96176362-889e8580-0f2c-11eb-9e6c-2f5310434e5f.jpg)

I cant open a import directory :/ to import mbs or mbox

**Comment by cleidigh** [comment]
video computer
Heart video computerif you cancel opening an account you should get a single default Local Folder
right-click on that, create two subfolders inbox, f2 or whatever
now right click on the inbox. folder, you'll see the ImportExportTools
menu, choose import mbox file
choose this will file option
pick your file and should import

**Comment by custos2003** [comment]
If I press the menu import mbox data nothing happens. No additional menu appears :/

![Bild_2020-10-15_213118](https://user-images.githubusercontent.com/72941044/96177197-c2bc5700-0f2d-11eb-9fe1-7339f481a109.png)

**Comment by cleidigh** [comment]
you have to have the local folders selected on the folder view
![image](https://user-images.githubusercontent.com/25272315/96177714-44938c80-0efc-11eb-94bf-d0351f903e11.png)

**Comment by custos2003** [comment]
Yes, great. It worked. this really helped me a lot !
You are a kind man and I am insensitive donkey.

Thank you so much!!

**Comment by cleidigh** [comment]
@custos2003 
Excellent!
you just proved even donkeys can use it ;-) !
truth is really needs a manual there are so many different ways to use it
I took over the extension a year and half ago and have only had to do the built-in help file
some day I hope to get more
shall we close?

**Comment by custos2003** [comment]
yes close. I am so lucky now. I can delete the good old OperaMail  :( (no support anymore and therefore not safe. But I realy liked the structure and handling of this small nice program).

**Comment by cleidigh** [comment]
@custos2003 
Yes, I think you will like Thunderbird
cheers
glad to get you over
Christopher
