### ISSUE TITLE
Prefix name of attachments folders with text to identify associated email

### ISSUE THREAD

**Issue by jeron1** [thundernest/import-export-tools-ng#172]
Would it be possible to have attachments saved in a folder that is named something similar to the email it is associated with?
E.g., I export an email that is saved with the following name:
20201024-Your payment was successful-162557.eml
The email also has attachments which saved to a folder name "Attachments". Instead of saving attachments in folder named "Attachments" I would like to be able to save as something like "20201024-Your paym_Attachments" (which just has added a truncated portion of the associated email file name before the word "Attachments").
This would be helpful in organizing the directories where I save exported emails & attachements. This function is included in https://www.encryptomatic.com/messageexport/ which I use on Windows with outlook (I'm trying to move more to linux and am impressed with the ImportExportTools plugin for Thunderbird).

**Comment by cleidigh** [comment]
@jeron1 
actually I you will be pleased to know this already is already supported.
have you checked out the internal help?  I asked for two reasons, first I think many people don't see
it which I have added to the end of every menu .  it could include a lot more however this is on the long list
secondly, it has two relevant sections for you
the filename token section which describes the tokens for filenames and date formats
there is also another section on experimental options
these are not found in the options UI, another to do
are you familiar with the config editor?
that is the low-level way to set options
there you can set the format for attachments and embedded images
check it out and let me know it's clear enough
@cleidigh

**Comment by jeron1** [comment]
It's great. I was testing it out this evening. This will help me get more of my workflow on linux (and out of virtualbox/windows). I would note that I could get ${sender_email} or ${sender} to flow into the exported email name, but only ${sender} in the attachment name (${sender_email} appeared in the name as "${sender_email}"). I also tried to set lower character limits for subject and name (i.e., 10), but it didn't seem to have an effect (although maybe I missed something). Either way, this is very helpful, so thank you for the response!  I'm using Thunderbird 68.12.0 on Manjaro.

**Comment by cleidigh** [comment]
@jeron1 
Excellent.  it's great to have somebody  utilizing the token system
sender e-mail was a recent addition and I must've missed it for attachments
I will check them out and let you know
Christopher

**Comment by jeron1** [comment]
Thanks again. I just made a small contribution.

**Comment by cleidigh** [comment]
@jeron1 
thank you very much! 
I just verified that indeed I missed the two new tokens for attachment filenames.
I am close to releasing 10.0.2 mainly taking care of backup issues, I will get this fix in as well.
Will probably post a beta...
@cleidigh

**Comment by cleidigh** [comment]
@jeron1 
created separate issue #174 
@cleidigh
