### ISSUE TITLE
msgFolder is undefined during import TB 68.12; IETNG 10.0.1

### ISSUE THREAD

**Issue by slrslr** [thundernest/import-export-tools-ng#173]
Hello, in TB 68.12.0 (64-bit) - Linux Manjaro(Arch) i clicked to show the toolbar, clicked Tools / Import export NG (10.0.1 from official TB addon store) / Import all messages from a directory / also from its sub-directories / selected the Local folders which contains sub-folders like Inbox containing .eml files.

I see the icon to stop export(import) operation, i see no action for two hours, so i clicked to stop it and opened the dev. tools/error log and see:

```
Skipping ravenJS installation
TypeError: msgFolder is undefined
6 menufunctions.js:190:9
    IETsetMBmenu2 chrome://mboximport/content/mboximport/menufunctions.js:190
    onpopupshowing chrome://messenger/content/messenger.xul:1
TypeError: msgFolder is undefined
mboximport.js:1091:4
    buildEMLarray chrome://mboximport/content/mboximport/mboximport.js:1091
    RUNimportALLasEML chrome://mboximport/content/mboximport/mboximport.js:1051
    importALLasEML chrome://mboximport/content/mboximport/mboximport.js:1038
TypeError: msgFolder is undefined
5 menufunctions.js:190:9
    IETsetMBmenu2 chrome://mboximport/content/mboximport/menufunctions.js:190
    onpopupshowing chrome://messenger/content/messenger.xul:1
[Exception... "Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsIPrefBranch.getComplexValue]"  nsresult: "0x80004002 (NS_NOINTERFACE)"  location: "JS frame :: chrome://messenger/content/aboutDialog.js :: init :: line 31"  data: no] aboutDialog.js:31:42
    init chrome://messenger/content/aboutDialog.js:31
    onload chrome://messenger/content/aboutDialog.xul:1
TypeError: msgFolder is undefinedmenufunctions.js:190:9
    IETsetMBmenu2 chrome://mboximport/content/mboximport/menufunctions.js:190
    onpopupshowing chrome://messenger/content/messenger.xul:1

```

similar looking error was seen by other member [here](https://github.com/thundernest/import-export-tools-ng/issues/42#issuecomment-647347764) but different addon/TB versions likely.

**Comment by cleidigh** [comment]
@slrslr 
from reading your post I think you might not have a folder selection on the left side as a target for the import
usually the process is to use the right-click context menu folder that you want to import to
I have to catch the scenario where the user test not have a folder selected and give a warning
10.0.2 will have this
@cleidigh

**Comment by cleidigh** [comment]
@slrslr 
I am still trying to reproduce.  can you comment on any other steps, whether a folder selected on the Left?
I probably need to add more output

**Comment by vj000** [comment]
@cleidigh i am sorry, i forgot to mention that i **had blank freshly installed TB with no e-mail account added**. Maybe that is why the error appeared.

But i tried again now after adding e-mail accounts and clicked one of the e-mail accounts name in the left TB menu and again tried IET NG import from the Tools menu (again directory&subdirectory method).
It is doing something per the task manager thunderbird disk activity. Also it was stuck at unresponsive script notice: mboximport.js
After a while it said "A folder with that name already exist. Please enter a different name."
(I see, it was possibly unable to insert messages because "Local Folders" existed :-/ )
So i renamed this folder in TB and also renamed the directory on disk.
It asked TB restart, after restart i clicked to go to Inbox of one mail account and from Tools menu select directory&subdirectory IETNG import. Now it worked and shown growing number of new mails in folders of one account (the one which Inbox i had opened before starting import). I somehow expected the imported content will either go to correct account (if mail is sent to different account, it should import to that one) or into the folder Local Folders (the name of folder i selected to import).
Dev. error console shows no error btw. (despite the error shown in first post of this issue when no mail account existed)

**Comment by slrslr** [comment]
@cleidigh i am sorry, i forgot to mention that i **had blank freshly installed TB with no e-mail account added**. Maybe that is why the error appeared.

But i tried again now after adding e-mail accounts and clicked one of the e-mail accounts name in the left TB menu and again tried IET NG import from the Tools menu (again directory&subdirectory method).
It is doing something per the task manager thunderbird disk activity. Also it was stuck at unresponsive script notice: mboximport.js
After a while it said "A folder with that name already exist. Please enter a different name."
(I see, it was possibly unable to insert messages because "Local Folders" existed :-/ )
So i renamed this folder in TB and also renamed the directory on disk.
It asked TB restart, after restart i clicked to go to Inbox of one mail account and from Tools menu select directory&subdirectory IETNG import. Now it worked and shown growing number of new mails in folders of one account (the one which Inbox i had opened before starting import). I somehow expected the imported content will either go to correct account (if mail is sent to different account, it should import to that one) or into the folder Local Folders (the name of folder i selected to import).
Dev. error console shows no error btw. (despite the error shown in first post of this issue when no mail account existed)

**Comment by cleidigh** [comment]
@slrslr 
Good sounds like progress
two comments
I am still working on warning
from your last comment is sounds like you are importing into an IMAP folder?
I always suggest importing to a local folder 
the imports just not look at accounts as this could be anything
do I understand correctly you now have a successful import?

**Comment by slrslr** [comment]
Yes, import was successful (into one of the POP3 e-mail accounts). I have not known i have to first click the account to set it as a import target and then go to Tools menu to import. I expected it will import into Local folder but it not happened as described. I think there is room for improvement so TB or the import tool ask where messages should be placed. And also if there is no account, recognize it and import to local folder or ask user to create e-mail account.

**Comment by cleidigh** [comment]
@slrslr 
the trick is that the normal way to choose the important location is to first right-click The target import folder
then choose the import method
each of the menus is described in the built-in help
which of course could even be more detailed
I agree there could be more prompts
Never enough time for everything!

**Comment by slrslr** [comment]
Sorry that i repeat myself, i wanted to post this for clarity.
When i right click "Local folders", IETNG menu, the option to import from folder is gray, only allows mbox import. But when i use the Tools menu, the folder import option is available and results in message "A folder with that name already exist. Please enter a different name." (the folder that contains my messages for importing has same name - "Local Folders".
This is what you have been talking about, it can be handy if the IET instruct user what to do or allow import to local folders.

**Comment by cleidigh** [comment]
@slrslr 
Actually sorry for the lack of clarity my part I have to do voice dictation which sometimes results in bad output!
just curious if you looked at the help it's completely localized
anyway I think I need to Clarify
you have to create an actual folder under the "Local Folder" account
then import folder

![image](https://user-images.githubusercontent.com/25272315/97637559-49cefc00-1a11-11eb-810f-5929718d91f1.png)

**Comment by slrslr** [comment]
Indeed, that worked.

**Comment by slrslr** [comment]
Yes, when i right click subfolder of Local folders the import folde roption is ther and worked for one already pre-created folder. But for mine created suibfolder it now returned following during import, and imported no mail:

> Exception importing message # 0
> 
> [Exception... "Component returned failure code: 0x8052000d (NS_ERROR_FILE_IS_DIRECTORY) [nsIMsgLocalMailFolder.addMessage]"  nsresult: "0x8052000d (NS_ERROR_FILE_IS_DIRECTORY)"  location: "JS frame :: chrome://mboximport/content/mboximport/mboximport.js :: writeDataToFolder :: line 1393"  data: no]

**Comment by cleidigh** [comment]
great
I am wondering if I should just remove the import export functions from the tools Menu
since you have to pick for Folder first anyway
what do you think?

**Comment by cleidigh** [comment]
one worked
Second failed?
now I am confused

**Comment by slrslr** [comment]
I think that it not worked (the error in my previous reply) may be because it may not be sufficing to just right click desired sub-folder, but you have to first left click and then right click it (... and select IET import). Because when i left click "Local Folders" and then right click different sub-folder (in my case Drafts) and select import of the folder (with eml files), then i see that error in my previous reply.

The best would be if user is notified about what he should do and if he do otherwise, he should be notified on how to do properly.
ideas:
1) if possible add IET to hamburger, Tools menu.
2) remove import function from the folder right click menu (user will search Tools menu where he will be either suggested on how to import properly or better - asked to create/select folder to import to).

**Comment by condorsf** [comment]
I'm running TB 78 on OS X. I was able to reproduce this issue:

1) Install ImportExportToolsNG and restart Thunderbird.
2) Do not click on anything in the left pane.
3) On the menu bar, click Tools, then ImportExportTools NG, then Import mbox file. You will not see a dialog box open. Instead, you'll see the "msgFolder.isServer is undefined" error in the error log.

When I select Local Folders in the left pane, it works. But new users (myself included) won't know to click something in the left pane. All they see is that the expected dialog box didn't open, i.e. it looks like nothing happened, and many users won't know to look in the error log. If msgFolder.isServer is not defined, I suggest you pop an alert saying "Select a folder in the left pane and try again" or something like that.

**Comment by cleidigh** [comment]
@condorsf
Thanks! 
you are correct.
I'm working on this now, I'm going to have an alert if no folder selected
the other problem of the right-click (TB selection anomaly) I'm still working on.
May have a beta tomorrow
@cleidigh

**Comment by cleidigh** [comment]
@slrslr 
@condorsf 
after some election distractions I am posting b4 tonight
besides addressing some other things,  I have several fixes for these issues
- doing a right-click on a folder while another is selected should now choose the former
- for the situation where no folder is selected (empty install example) now has a
top menu entry that indicates no-folder selected, If selected info warning
note -alert only works in US locale until I finish localization
here's how the menu looks:


![image](https://user-images.githubusercontent.com/25272315/98766766-42163c80-23ad-11eb-8dba-dd4237dcc873.png)

**Comment by slrslr** [comment]
I can not test since when i add it, it says the addon is not compatible with TB 68.12.0.
I plan to install TB 7x but not yet researched on how to do it on Manjaro/Arch without loosing my profile and e-mails.

**Comment by cleidigh** [comment]
@slrslr 
whoa!  should not be the case!
I will see if I reproduce
don't do any upgrading

**Comment by cleidigh** [comment]
@slrslr 
just retested b4 on Windows/TB 68.12.2
maybe uninstall,Close,reinstall?
the only thing I did were some bug fixes
and temporarily allowed Max version to test 8x versions
Christopher

**Comment by slrslr** [comment]
I am on Linux (Arch), so i tried to restart, then shutdown TB and reinstall it:
```
$ pamac reinstall thunderbird
Preparing...
Warning: thunderbird-68.12.0-1 is up to date -- reinstalling
```
it launched into my previous profile, i see no IET active, so in addons tab i select to installa ddon from file (import-export-tools-ng-10.0.2-b4-tb.xpi) - i tried to re-download it. Yet the result is message addon is not compatible with TB 68.12.0.

**Comment by cleidigh** [comment]
if you roll Back to b3 does work ?
also is there anything in the console ?

**Comment by cleidigh** [comment]
b5 has a couple other localization changes
just tested it on my mint VM
just out of curiosity if you are not using the English locale
try that temporarily
[import-export-tools-ng-10.0.2-b5-tb.zip](https://github.com/thundernest/import-export-tools-ng/files/5534800/import-export-tools-ng-10.0.2-b5-tb.zip)
this is not official

**Comment by slrslr** [comment]
@cleidigh I'm sorry, i am not a developer and i am rather newbie to TB. I can not see b3 here on github and i do not know how to process/use the yours mentioned .zip archive contents.

**Comment by cleidigh** [comment]
@slrslr 
sorry I should never assume things
here is a link to b5 xpi
for your reference xpi is actually a zip format for extension files
you can actually load the same as xpi
I posted the testing zip above because that's an allowed file type here

**Comment by slrslr** [comment]
My TB interface is in english. TB reports same issue (not compatible with TB 68.12.0) for this b5. My TB interface is in english.

During the activation, new error in dev. console:
```
1605396874893	addons.xpi	WARN	Invalid XPI: [Exception... "Component returned failure code: 0x8052000b (NS_ERROR_FILE_CORRUPTED) [nsIZipReader.open]"  nsresult: "0x8052000b (NS_ERROR_FILE_CORRUPTED)"  location: "JS frame :: resource://gre/modules/addons/XPIInstall.jsm :: XPIPackage :: line 324"  data: no] Stack trace: XPIPackage()@resource://gre/modules/addons/XPIInstall.jsm:324
get()@resource://gre/modules/addons/XPIInstall.jsm:236
loadManifest()@resource://gre/modules/addons/XPIInstall.jsm:1518
init()@resource://gre/modules/addons/XPIInstall.jsm:2047
createLocalInstall()@resource://gre/modules/addons/XPIInstall.jsm:3003
getInstallForFile()@resource://gre/modules/addons/XPIInstall.jsm:4194
XPIProvider[meth]()@resource://gre/modules/addons/XPIProvider.jsm:3130
promiseCallProvider()@resource://gre/modules/AddonManager.jsm:236
getInstallForFile/<()@resource://gre/modules/AddonManager.jsm:1932
getInstallForFile()@resource://gre/modules/AddonManager.jsm:1945
getInstallForFile()@resource://gre/modules/AddonManager.jsm:3993
doCommand/<()@extensions.js:1527
```
re-downloading does not help
​

**Comment by cleidigh** [comment]
okay that's good we have an error
it says the file is corrupt
does earlier version like v4.x work ?
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.2/xpi/import-export-tools-ng-4.1.0-tb.xpi 
I am having trouble thinking of other issues

**Comment by slrslr** [comment]
@cleidigh yes, this 4.1.0 is activated without issue ("not compatible with TB 68.12.0" is not shown)

**Comment by cleidigh** [comment]
@slrslr 
I should have also asked if any of the 10.0.2-bx beta versions install correctly?
I am wondering if there's an issue when you use extensions not downloaded from the store.

**Comment by slrslr** [comment]
@cleidigh it had to be some weird network/software problem on my end, because all versions i am trying now works, and i see the ones that not worked yesterday has significantly lower size, like 93kB where same version files i downloaded today from apparently same URL are like 400kB. So i think there is problem on my side and i am sorry i have bothered you. Firefox not notified me that the download was broken (if was) :roll_eyes: if interested [here is](https://bin.disroot.org/?231b08628e095c9a#AUVZNPg5CZye2X9f7Pnh5PuPjp6UnUtjEtDL4kFj1bzR) the 93kB file content.

so i installed latest b5 OK

> doing a right-click on a folder while another is selected should now choose the former

i confirm, it works this way. It is good fix

> for the situation where no folder is selected (empty install example) now has a
> top menu entry that indicates no-folder selected,

When i right click some mailbox on the left, (i mean e-mail address, not Inbox, or Trash or such child folders), then the IET menu does not allow me to import messages from a dir, only mbox file (that entries are grayed out). That may be confusing. But it is not grayed out when i am on the Addons tab, not mail tab. Strange.
And i do not see the menu entry that would indicate no folder is selected as was shown on your image
![](https://user-images.githubusercontent.com/25272315/98766766-42163c80-23ad-11eb-8dba-dd4237dcc873.png)
Maybe due to me already set mail accounts and imported mail.
Sorry for my bad english, it is not my primary language.

**Comment by cleidigh** [comment]
@slrslr 
great!  I was wondering if something like that was happening.  glad you figured it out
okay, I need a little bit more clarity in the last issue.  are you saying when an "Account"
is selected you do not get all the options?  if that is what you are seeing, that is correct
because it will only import mbox if no message folder is selected
does that make sense?

**Comment by cleidigh** [comment]
@slrslr 
b6 shows the right menus for me
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.2/xpi/import-export-tools-ng-10.0.2-b6-tb.xpi

![image](https://user-images.githubusercontent.com/25272315/99199042-6c2f7c00-276a-11eb-98ec-07d69fd6560b.png)

**Comment by slrslr** [comment]
I see same thing as you on your last image. I thought that regarding the image in my previous comment you said that you made an adjustment so this state is less confusing, so the user is suggested he need to select some sub-folder. As your last image does not suggest why "import messages and"import all messages from a directory" menu entries are unavailable.
I would expect something like "Import .eml (Unavailable. Select folder first)".
Also better would be if it is not needed to select folder as i am importing eml folder with subfolders like Inbox Sent , so it would be placed automatically or after confirmations into appropriate subfolders of the mail account..

**Comment by cleidigh** [comment]
@slrslr 
I agree that some of the menu options need to be improved, but I think it's not typical or good to have to give a reason for the greay  menu, help talks about selecting a folder
I also think eventually I have to make it more like a wizard as the menu is not clear and getting too long
I'm going to hold off doing anything more until I can do it really correctly.
hopefully I can poster for review tonight

**Comment by cleidigh** [comment]
Fixed:
v10.0.2
