### ISSUE TITLE
Comma and quote character should be supported in Custom Filenames

### ISSUE THREAD

**Issue by Wileecoyoteig** [thundernest/import-export-tools-ng#175]
I am using Extended Format for filename exports.

I would like a comma as shown below:
${subject}, ${date_custom}

How can this be done?

**Comment by cleidigh** [comment]
@Wileecoyoteig 
good to hear people using the new tokens!
I just investigated and for some reason the original code replaces `,` with the `_` despite it being a valid character
I am putting out b3 tonight which will also include This fix
thanks
@cleidigh

**Comment by Wileecoyoteig** [comment]
Correct, I was getting a '_' instead of ','.

The new tokens are perfect for my workflow.
I was renaming the files manually with my own date and time format every time I saved an EML message using TB.
With ImportExportTools, the save filename is fully automated using custom tokens.

Questions:
1) Besides alphanumeric, what other characters are supported?
2) What is b3 and how do I get it?

Thank you for the great add-on!

**Comment by cleidigh** [comment]
@Wileecoyoteig 
that's great!  I really like to hear the new feature is critical for workflow ;-)
this is one of my biggest contributions after taking over from the original author
now your questions:

1. if you have the alphanumeric character option only disabled (first checkbox)
you can use all valid filename characters , the invalid characters from's (substituted by `_` are:
` \ / : < > | ? * '  "`

2. I was referring to the third beta for 10.0.2 which I will release this evening
I will post a link to where you can download
then one I do the official you will have to manually upgrade
cheers
Christopher

**Comment by Wileecoyoteig** [comment]
Just for accuracy although I never use, single quote (') is a valid Windows filename character.

**Comment by cleidigh** [comment]
@Wileecoyoteig 
absolutely correct.
the original author decided `, ` as well as `'` should not be allowed
I enabled the, I don't really like `'` But it is valid
Any opinion

**Comment by cleidigh** [comment]
just posted b3 allowing `,`
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.2/xpi/import-export-tools-ng-10.0.2-b3-tb.xpi

**Comment by Wileecoyoteig** [comment]
As I mentioned above, I personally never use single quote (').

However,
All software written for Windows should adhere to all Windows standards, that's my opinion.
That's what 100% compatibility is all about.
So I would enable the single quote (').

Thanks for your excellent support.

**Comment by cleidigh** [comment]
I agree,however, I would support openly to common set across OS'
I just did a quick check `'` is flight for OS X and *nix
I think I will go ahead and support it
Thanks !

**Comment by cleidigh** [comment]
@Wileecoyoteig 
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.2/xpi/import-export-tools-ng-10.0.2-b4-tb.xpi
contains both fixes
have not updated help
@cleidigh

**Comment by cleidigh** [comment]
Fixed:
v10.0.2
