### ISSUE TITLE
Issues with Mac Terminal and expanding executable folder email

### ISSUE THREAD

**Issue by davekfhss** [thundernest/import-export-tools-ng#178]
Thanks for this plugin! It seems to have exported all the folders into big, executable files. (which all seem to be appropriate sizes) I'm assuming the executable expands the file into a folder with all the email? Unfortunately - when I run the exec - I run into some errors. I was hoping you could shed some light on this. 

This is the output:

Last login: Wed Nov 11 09:59:35 on ttys000
/Volumes/Admin/Technical\ Support/Kevin_Mail_Test2/iPro\ WolfConnect ; exit;
dave@KFHSSs-iMac ~ % /Volumes/Admin/Technical\ Support/Kevin_Mail_Test2/iPro\ WolfConnect ; exit;
From: can't read /var/mail/-
/Volumes/Admin/Technical Support/Kevin_Mail_Test2/iPro WolfConnect: line 2: X-Mozilla-Status:: command not found
/Volumes/Admin/Technical Support/Kevin_Mail_Test2/iPro WolfConnect: line 3: X-Mozilla-Status2:: command not found
/Volumes/Admin/Technical Support/Kevin_Mail_Test2/iPro WolfConnect: line 4: syntax error near unexpected token `qmail'
/Volumes/Admin/Technical Support/Kevin_Mail_Test2/iPro WolfConnect: line 4: `Rec'ived: (qmail 17730 invoked by uid 30297); 21 Nov 2016 19:51:30 -0000 

I'm using a Mac and it is executing the command with the Terminal app. 

Thanks!

**Comment by cleidigh** [comment]
@davekfhss 
thanks for the post.
I think I'm in need some more details.
first can you identify the Thunderbird version/extension version

next I think I need to better understand what you are trying to do.  For instance I don't understand the references to"executable folder e-mail" .
also I don't understand what you mean by "executing the command"

the import export tools ng extension has no relationship with terminal commands so that confuses me.
@cleidigh

**Comment by davekfhss** [comment]
Sure, I'm using 78.4.1 (64 bit) on a Mac running Catalina. 
Your add-on is V10.0.1
I've attached the results of running the add-on. That is what I'm seeing. 
![Screen Shot 2020-11-11 at 3 38 20 PM](https://user-images.githubusercontent.com/74311695/98861943-18ecbf00-2434-11eb-815b-654a03a3c197.png)

I guess my expectation from running the add-on would results in folders with individual .eml files or a zip of a folder that could be unzipped into a folder with emails? 

The execute command... If I click on one of the files shown above it appears like it is trying to execute some unix? commands but isn't finding them and therefore (I'm guessing) not expanding the file into a folder with .eml files.

Thanks again.

**Comment by cleidigh** [comment]
@davekfhss 
okay, what method did you use for exporting?
the files see above without extensions are mbox files which contain one or more e-mails
OS X is interpreting them as executables even though they are not
recently I and did the first-ever help just curious if you check that out
it is by no means complete, it's a never-ending to do
you can see there are options for EML operations
Christopher

**Comment by davekfhss** [comment]
Hmm. I changed one of "executables" by just adding the .mbox extension. Can I then just tools> import > Mail?

I think i used all the default settings for my add-on export.

**Comment by davekfhss** [comment]
It says successful Apple Mail Import but the folder is empty.

**Comment by cleidigh** [comment]
I think you may be crossing the internal "limited" import methods from the actual add-on
the extension as a menu under the main tools menu (not the hamburger)
for doing imports I suggest creating a top-level subfolder under Local folders
select that folder then right-click choose IETng\import mbox file
then in the dialogue choose with structure (last option)
in the file picker choose the top-level directory containing the e-mail
do not rename the files!
Christopher

**Comment by davekfhss** [comment]
Awesome! That does it. Just add the .mbox extension then I was able to use Apple Mail > Import Mailboxes > Files in Mailbox Format and it imports all the mail. 👯

**Comment by cleidigh** [comment]
okay now I'm confused
are you moving from Thunderbird to Apple mail?

**Comment by davekfhss** [comment]
Was just testing that first. Your method also work perfectly and as you said I don't need to change the extension.
So.. Create a Folder under Local Folders > Right click select your Addon > Import Mbox file > Import directly one or more file > Select the file (the "executable" without an extension) and it imports as expected.

Thanks for helping. This is a godsend!

**Comment by cleidigh** [comment]
@davekfhss 
Excellent!
someday I will have enough help to describe these things!
shall we close?
Christopher

**Comment by davekfhss** [comment]
Yes! And again - this is helping immensely. Thank you.

**Comment by cleidigh** [comment]
glad to help
cheers
