### ISSUE TITLE
no MBOX import option

### ISSUE THREAD

**Issue by mygitness** [thundernest/import-export-tools-ng#18]
I am running Thunderbird 68.1.0 (64 bit) and version 4.0.4-tb of your software, and when I go through the menus to import MBOX email (after installing your xpi), there are no options other than Becky! Internet Mail and Outlook. Your add-in is listed in the add-in manager.

Am I missing something ?

**Comment by cleidigh** [comment]
@mygitness 
@sciencetn

Thanks for the posting.  I usually use test with x32 so I installed the extension under the 64-bit version.
I was able to export and import.  Reading your issue I believe the menu you are referring to is the built-in Import menu item.  ImportExportTools NG installs its menus in several places.  
Settings are accessed under the tools menu/add-on options
Import/Export is usually done with the context menus.  Below is a screenshot of the menu right clicking on a folder, in this case subfolder under local folders.
![image](https://user-images.githubusercontent.com/25272315/65102681-d481a280-d999-11e9-8753-5aee435cf5c7.png)

You can also right-click on an individual message for export.  There you get both the import-export functions but also the profile import and export.

While this set up is pretty normal for extensions, I do think there is some confusion with a built-in very limited import menu /functionality.  I probably need to add some more documentation now.
Please let me know if this addresses your issue.  I am trying very hard to keep up with the changes in the new Thunderbird versions.  
Cheers

![image](https://user-images.githubusercontent.com/25272315/65102731-01ce5080-d99a-11e9-9277-1c7c339f8f2f.png)

**Comment by mygitness** [comment]
Thank you for the reply.

Do the files need to have a .mbox extension in order to be recognized as such ?

**Comment by mygitness** [comment]
update: I selected a folder with a bunch of mail items, but it didn't appear to import anything. I then selected a folder in which all of the files have a .mbox extension, and it still didn't see anything to import, unless I'm looking in the wrong place. Where do imported mail items show up ?

**Comment by cleidigh** [comment]
here is one test and get familiar with the process:
- create a new folder under Local Folders
- copy a few random e-mails into it
- right click on the folder name
- Choose ImportExportTools NG/Export Folder
- Choose the OS directory to export the e-mails
- Note - this option does not export subdirectories (use with structure for that)
- Create another subfolder for import
- Right-click on the new subfolder
- Choose Import mbox file
- Choose first dialogue option
- Pick the file you created during export
- the e-mails will be imported under the sub folder name of the file
The mbox file does not typically have an extension when exported, doesn't matter if it does

**Comment by cleidigh** [comment]
@mygitness 
any update?
