### ISSUE TITLE
Import mbox not working

### ISSUE THREAD

**Issue by gucu** [thundernest/import-export-tools-ng#188]
Hi All

I exported using Export Folder and then tried to import using Import Mbox Folder. The error I get is Javascript Application: Impossibile to import in this folder (imap or newsgroup type) OK.

Is there anyway of getting around this please?

Thanks

Rich

**Comment by cleidigh** [comment]
@gucu 
what you want to do is import into the local folders account (after creating a subfolder)
Importing into an imap would create lots of server activity undesirable  during the import
Cheers
Christopher

**Comment by gucu** [comment]
Thanks Christopher, that worked
