### ISSUE TITLE
.dbx import issue

### ISSUE THREAD

**Issue by oldmail** [thundernest/import-export-tools-ng#19]
Hi, I've got thunderbird version 60.9.0 32bit and need to import .dbx files, is it possible?
Thanks a lot.

**Comment by cleidigh** [comment]
@oldmail 
As far as I could tell dbx is the native storage type for Outlook express.  Currently IET NG only understands mbox and EML , this is the same as the original extension.  Can you get a EML formatted file?  That should be available in Outlook, I'm wondering if you could import them reexport as EML?
Christopher
