### ISSUE TITLE
Only one date format is used for export.

### ISSUE THREAD

**Issue by b4piotr** [thundernest/import-export-tools-ng#198]
I suggest that by default the date format is taken from the program / system settings and that it can be defined in the settings. Currently, the format is MM DD YYYY, and I would like the DD MM YYYY or YYYY MM DD format much better. I am using export with index to HTML with attachments.

**Comment by cleidigh** [comment]
@b4piotr 
The date format for export filenames is completely configurable.  if you look at the built-in help which is in every menu, it describes the formatting.
At the bottom of the help that describes the currently hidden setting for the internal index dates.
I have not had the opportunity to get this in the UI
Christopher

**Comment by b4piotr** [comment]
Ahh... In Tools menu - ok, now I see.
Thanks.
