### ISSUE TITLE
Unable to import exported files from 2018

### ISSUE THREAD

**Issue by TWS2021** [thundernest/import-export-tools-ng#201]
Hi,

in January 2018 I used ThunderbirdPortable_52.5.2 and ImportExportTools-3.2.5 to export two folders of emails. It created two files, each with a size of about 500 to 600 MB, any file extension is missing.

I tried to import one of these backups now without any working result.

1.) Same software configuration as in 2018
I pick one of the exported files, it loads only one email but if I click it a small loading strip at the bottom appears but Thunderbird is constantly not reachable until it crashed totally (also, use of RAM rises, CPU is about 8 to 10% only).

2.) Thunderbird 78.6.1 with Import Export Tools NG 10.0.4
It says "Importing Mails" but nothing else follows. RAM rises from about 125 to 725 MB but CPU Usage is 0%.

I'm looking forward for help, many thanks.

**Comment by cleidigh** [comment]
@TWS2021 
I am assuming you exported a single mbox file per folder (which does not have an extension)
to import choose an import folder (created under local folders)
then choose "import mbox file"
if you still have problems check the console and post here
Christopher

![image](https://user-images.githubusercontent.com/25272315/105617031-a724e000-5da9-11eb-95dd-2c9570928413.png)

**Comment by TWS2021** [comment]
@cleidigh
Ah, I see. I wasn't aware it's an so-called mbox file which is why I always chose "Import messages" instead and picked the file then manually. Everything worked perfectly fine now, many thanks!
