### ISSUE TITLE
Import EML with first header without space after ':' fails

### ISSUE THREAD

**Issue by Jane22Jane22** [thundernest/import-export-tools-ng#214]
Hi, next problem. Need to import 1784 EML's into Local Folder. Only 815 are loaded, and 969 give error and are thus not uploaded. Have tried first the full set with folders and subfolders, with almost 50% missing in upload. For simplicity sake, re-did the work for 1 folder only, the above figures are from that 1 folder as test.
Also - reading some issues in this community - I have tried the setting in Options "subject max length = 50" changed to 150, no resolution, same problem. I do have an Error Log.

Can someone help ? Appreciated !

W10
Mozilla Thunderbird 78.8.0
ImportExport 10.0.4

**Comment by cleidigh** [comment]
Can you post the log

**Comment by Jane22Jane22** [comment]
[console-export-2021-3-3_23-31-55.txt](https://github.com/thundernest/import-export-tools-ng/files/6079584/console-export-2021-3-3_23-31-55.txt)

**Comment by cleidigh** [comment]
it looks like an unknown EML  format, what was the source files?
 can you post a couple of files that fail and one that works

**Comment by Jane22Jane22** [comment]
[EML examples.zip](https://github.com/thundernest/import-export-tools-ng/files/6082025/EML.examples.zip)

EML 2011-11-14 18-03-09 Eta.eml = error #2 
EML 2011-11-27 13-36-01 RE_ Eta.eml is loaded OK
All 1784 mails are same format, the older ones originally from WLM, then moved to eMClient, exported to EML format. The importing OK versus Not-OK goes quite randomly it appears, throughout all mails.
Perhaps one interesting aspect could be: all mails from some few specific senders (at least more than 3) are not imported, where one of them even switched provider inbetween (!).

**Comment by Jane22Jane22** [comment]
Btw, if I open the not-loaded EML files with eg. Mail or other mail programs, no problems, opens OK, is OK.

**Comment by cleidigh** [comment]
@Jane22Jane22 
Thank you for the log and files. it made diagnosing the problem easy.
your e-mails had the first header  without a space (not seen before)
I have posted b4 beta with this fix which you can download and try:
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.5/xpi/import-export-tools-ng-10.0.5-b4-tb.xpi
Christopher

**Comment by Jane22Jane22** [comment]
Hi, test done and succesfully loaded / imported all EML's. Thanks !
Note: the version title reads 10.0.5 however the version text reads 10.0.2.
However, another problem is introduced (which did work properly in 10.0.4): when using "import all messages from directory > just from the directory" it only imports the EMLs and not any more the folder structure, where before it loaded the folder + EML's.

**Comment by Jane22Jane22** [comment]
Any suggestions ?
Thanks,

**Comment by cleidigh** [comment]
@Jane22Jane22 
you want you use the option with subdirectories
Christopher
![image](https://user-images.githubusercontent.com/25272315/110386077-d330b380-802d-11eb-8902-dc4648a2ce51.png)

**Comment by Jane22Jane22** [comment]
Correct. That one and also the option "also subdir" result in a upload of EML's only, without the folder structures. In v.10.0.4 that was running OK, now it is not any more.

**Comment by Jane22Jane22** [comment]
Apparently I am not clear. I have Folder X, subfolder Y, and subsubfolder Z with all my eml's to import. I want to upload Subfolder Y and its contents to TB Local Folder. In v.10.0.4 it worked as follows: I select Folder Y to import, and in TB I get Folder Y created as a subfolder to my Local Folder, and then in that Folder Y all relevant EML's. Now in this current version (10.0.5 but text reads 10.0.2) it does NOT create the Folder Y, it plainly uploads all EML's from the folder Y into the Local Folder itself.

So this means (if I do want to do a selected import of my Subfolders under my root Folder X) I have to create in TB Local Folders first the Subfolder Y, and then do the import, and subsequently same for all my other selected subfolders under my root Folder X. Yes, doable, but far more hassle, while it worked fine in v.10.0.4.
 
If I would want to include Subsubfolder Z under the import of Subfolder Y, then that pertains to your options Just from Dir or Also Subdirs, in the first Z is not included, in the 2nd Z is, that is clear to me.

**Comment by cleidigh** [comment]
@Jane22Jane22 
I believe I understand your explanation.  I cannot think why 10.0.4 would behave differently.
Let me do some tests.  any errors in the console?

Christopher

**Comment by Jane22Jane22** [comment]
No errors whatsoever.Thanks,


    On Tuesday, March 9, 2021, 09:28:58 PM GMT+1, Christopher Leidigh <notifications@github.com> wrote:  
 
 


@Jane22Jane22
I believe I understand your explanation. I cannot think why 10.0.4 would behave differently.
Let me do some tests. any errors in the console?

Christopher

**Comment by cleidigh** [comment]
@Jane22Jane22 
I just successfully imported a basic structure using your names w 10.0.5-b5
FolderX-source (the top level folder in the file system to import)
   subfolderY (4 EML 'messages)
   subfolderZ (3 EML 'messages)

FolderX (folder created under LocalFolders - TB import location)

steps to import with structure:
- create import folder under local folder FolderX
- highlight this folder, right-click and selects the import messages/' with subdirectories
- the file dialog will show, choose the source folder FolderX-source
- the result should look like below
if you cannot reproduce we will have to add some debugging information
Christopher
![image](https://user-images.githubusercontent.com/25272315/110574449-1e7cbc00-812b-11eb-94a3-15717e8a9556.png)

**Comment by Jane22Jane22** [comment]
OK, via the other way I have uploaded my local EML's. Your beta solution however is almost perfect, but not completely. Attached email is being refused to import, whatever I try. Out of 10546 files, some 35 are not uploaded. 

[EXAMPLE.ZIP](https://github.com/thundernest/import-export-tools-ng/files/6122222/EXAMPLE.ZIP)

However, from the EML file itself (in Windows Explorer), I can open it with TB ... Strange. Can you please have a look. 
Thanks !

**Comment by cleidigh** [comment]
good,progress!
appreciate your patience
I will look at the e-mails that failed, did the 35 show up as errors?

**Comment by cleidigh** [comment]
@Jane22Jane22 
I was able to import the single message.   have to keep searching, some of the other 35?
I also wonder if you repeated import if the same messages would be a problem.

![image](https://user-images.githubusercontent.com/25272315/110849870-4bd97f00-827d-11eb-97b8-0921c276fc87.png)

**Comment by cleidigh** [comment]
I just had another thought.  the subject length  is very long. if the filename exceeds 250
that would be in error.

**Comment by Jane22Jane22** [comment]
Interesting development. Total folder 1081 eml's. Upload done 3/10, uploaded 1049. Upload done today 1036.  See Example.zip. 

Wrt. subject length too long: Mail can handle, Outlook can handle, WML could handle, eM Client can handle, why can't you ? I would say cut-off @ 50 or 250 chars is quite strange, if not unworkable. But secondly I put the Options > Subject max length at 150, altering settings appears not to have any impact ?
Of the 1081 EML's, some 24 have subject lengths > 250 chars (incl spaces). Does not explain the full gap. Also a mail with 212 chars (incl spaces) is not uploaded today, but was in my first test (!!).
[EML examples.zip](https://github.com/thundernest/import-export-tools-ng/files/6137694/EML.examples.zip)

**Comment by Jane22Jane22** [comment]
Please delete the zip file from this board, thanks

**Comment by Jane22Jane22** [comment]
[EML examples.zip](https://github.com/thundernest/import-export-tools-ng/files/6137748/EML.examples.zip)

**Comment by cleidigh** [comment]
@Jane22Jane22 
downloaded and deleted.
my comment about the subject len was probably confusing and not be issuing this case.
in my experience it is usually the case that there is some slight e-mail encoding issue
that is not yet contemplated by the import.  did you capture any errors?
the other thing is to try to get a small subset of e-mails where you always care failures
then we will will Try to create some debugging output

**Comment by Jane22Jane22** [comment]
Hi, any update on your factfinding tour ? thanks !

**Comment by cleidigh** [comment]
@Jane22Jane22 
from my last post, I was hoping you were able to experiment to isolate the e-mails for causing problems.  ideally you could reliably reproduce the problem and then hopefully I can identify the issue.  also I don't have your debug output when the 35 e-mails fail.
Christopher

**Comment by jobisoft** [comment]
Uplifted this fix to v10.1.0-b5

https://github.com/thundernest/import-export-tools-ng/issues/264
