### ISSUE TITLE
Problem with importing eml file to Thunderbird

### ISSUE THREAD

**Issue by mikeych76** [thundernest/import-export-tools-ng#227]
Hi

I have exported Mails from single folders into eml file and trying now to import them into new Laptop. Unfortunately it appears that all messages has been merged into one single mail instead of several ones. I have missed to backup profile folder and the messages on old laptop I already deleted (to fast, dumb guy). So I can now only deal with this eml files.

Any "digital chainsaw" available to fix/slice that into several pieces (messages) again?

Thanks for help

**Comment by cleidigh** [comment]
@mikeych76 
is it possible you exported to mbox format which supports multiple e-mails
Can you post a partial example of the file  ?
Christopher

**Comment by mikeych76** [comment]
the orginal mails does not exist anymore that's why I can't do another export. Thank you anyway

**Comment by cleidigh** [comment]
@mikeych76 
if you are still interested, put since you have the exported e-mails let's figure out what the format is. I was not suggesting a new export. I was asking if possibly the original export was mbox .  can you post part of the file here so we can figure out the format?

Christopher
