### ISSUE TITLE
length of 250 characters path + file name with extension

### ISSUE THREAD

**Issue by bj-v-berg** [thundernest/import-export-tools-ng#228]
Hi
I have the following problem when exporting individual emails in eml format:
The file name is shortened.
Apparently only a total length of 250 characters (path + file name with extension) is permitted.
Is there a way for me to lift this restriction?
Thanks in advance for the support.

**Comment by cleidigh** [comment]
@bj-v-berg 
thanks for your patience!
you are correct about the file path name/name limitation of 250  characters.
this is actually an ancient Windows limitation and believe it or not remains the default
in Windows 10.  theoretically you can configure an increase , But however, this is not simple
checkbox stuff and I would guess that Thunderbird may not handle the increase.
if you really wish to try,I can locate the documentation for increasing the length
just no promises it will work!
Christopher

**Comment by bj-v-berg** [comment]
Hello Christopher, thanks for your answer.
I have already tried to remove the restriction in Windows 10 via group policies and the registry - unfortunately without success (is there another option?).
As it stands, your guess is correct that Thunderbird cannot act.
After doing some research on the Internet, I read some comments that pointed to possible problems after this restriction has been lifted - some files suddenly cannot be found by the system (file explorer), etc.
If that's really the case, I'll probably try to shorten the paths.

**Comment by cleidigh** [comment]
@bj-v-berg 
you found the same information as I did. 
I am 99% 6certain that  Thunderbird will not handle it.
I would recommend doing it.
Christopher

**Comment by bj-v-berg** [comment]
Hello Christopher,
thank you again for your effort.
I will try to shorten my file paths.
have a nice Sunday
