### ISSUE TITLE
How to merge two profiles

### ISSUE THREAD

**Issue by cleidigh** [thundernest/import-export-tools-ng#240]
I have two separate profiles and I want to merge them. Your import does not import Thunderbird emails and folders, correct? So first I have to export from one profile to eml files and then import to the other? Do I export to one directory or one file? 

Will this keeps all the emails in the correct folders on exporting? 
If there are two folders with same name does it just combine into one after the merge?

Also, since you know Thunderbird, where can I get a detailed explanation of what the each entry in Profile.ini means?

Thanks for the help,
Doug
@decroft

**Comment by cleidigh** [comment]
@decroft
first couple of points:
- my posts may look rough,I have to dictate everything as I am disabled, I don't correct everything
- can you give me a version information OS/TB et cetera
- also what are you sourcing from and destination profile versions
- I assume you are just trying to combine the e-mails?
- importing into local  folder 's this always the safest at that point
Christopher

**Comment by jobisoft** [comment]
I do not recommend to mess with profile.ini or manually merge profile files.

As Christopher has stated, if you want to merge emails, importing into local folders this always the safest thing to do.
