### ISSUE TITLE
Import All Messages from a Directory and emlx files

### ISSUE THREAD

**Issue by philosoraptorx** [thundernest/import-export-tools-ng#241]
The _Import Messages_ option allows emlx files in a single directory to be imported. The _Import All Messages From a Directory | Also from it's subdirectories_ option does not support addition of emlx files from a folder/subfolders.

Is it possible to implement importing emlx files recursively from a directory and subdirectories thereof?

Thank you.

**Comment by cleidigh** [comment]
@philosoraptorx 
playing catch-up.. 
but me check this out, should not be a problem.  I assume an oversight.
Will report back
Christopher

**Comment by cleidigh** [comment]
@philosoraptorx 
indeed this was an oversight from some time ago.
I am working on a new Release and I fixed this in the b5 beta
feedback welcome
https://github.com/thundernest/import-export-tools-ng/blob/v10.0.5/xpi/import-export-tools-ng-10.0.5-b5-tb.xpi
Christopher

**Comment by jobisoft** [comment]
Uplifted this fix to v10.1.0-b5

https://github.com/thundernest/import-export-tools-ng/issues/264
