### ISSUE TITLE
Thunderbird Version 91 -- ImportExportTools and the future?

### ISSUE THREAD

**Issue by Al-NN4ZZ** [thundernest/import-export-tools-ng#242]
I've been trying to follow the progress on the new version ( 91 )  of Thunderbird that is coming (estimated by the end of 2021).  
Here is one of the links:  https://www.ghacks.net/2021/02/10/thunderbird-team-outlines-plans-for-the-email-client/

It sounds like there are many major changes to to the architecture and user interface if I've read correctly.   Do you expect to update the ImportExportTools extension for V91?  At some point I think you mentioned that you may be working with the Thunderbird to team to integrate the feature directly into Thunderbird.  

Anyway I was wondering if you could provide some comments on what you know so far and any feedback you have on the effort.

Thanks...Al

**Comment by cleidigh** [comment]
@Al-NN4ZZ  
Hope all is well, I just finished a printing tools update And now trying to catch up with
IET. apologies for the slow response.  just a quick note today, I will embellish some tomorrow when my voice is hopefully better.

- on v91 compatibility: I'm taking a look at having an official beta for this, I am hopeful the current structure will be supported without too much effort
- No progress on the backup yet, I might be able to combine with structured export
more tomorrow
Christopher

**Comment by Al-NN4ZZ** [comment]
Hi Christopher,

Any updates?

Thanks...Al

**Comment by Al-NN4ZZ** [comment]
Hi Christopher,
I saw your reply on another post about be sick for a month and hope you are feeling better.  I figured there was something going on and understand why it will take you a while to catch up.  Please take care and take it slow.

Regards, Al

**Comment by warmphase** [comment]
I found this thread, looking for the same thing.  Looking to import a heap of google take-out data into Thunderbird 91.01.

**Comment by jobisoft** [comment]
Closing in favor of
https://github.com/thundernest/import-export-tools-ng/issues/264
