### ISSUE TITLE
Exporting will remove some of "from" part

### ISSUE THREAD

**Issue by foloinfo** [thundernest/import-export-tools-ng#25]
When I export emails with CSV, some of it's "from" part is broken.
For example, an email from google cloud has `Platform Notifications <PlatformNotifications-noreply@google.com>` but exported as `Platform Notifications <PlatformNotifications-nor`

Is this expected behaviour?

**Comment by cleidigh** [comment]
@foloinfo 
The example 'from' address output:
Platform Notifications <PlatformNotifications-nor
is exactly 50 characters.  You can set the maximum length (truncation point) for the subject, sender and recipient names.  It's  on the first tab for the add-on options:
let me know if this is not the case

![image](https://user-images.githubusercontent.com/25272315/67425257-ab11f300-f5a5-11e9-9864-e96278e7a00f.png)

**Comment by foloinfo** [comment]
@cleidigh I didn't notice there was a config in the menu!
Thank you! That solved my problem.

**Comment by cleidigh** [comment]
@foloinfo 
Excellent, I like fixing problems and are really problems 👍
