### ISSUE TITLE
Cannot get program to recognize top-level MBOX folders

### ISSUE THREAD

**Issue by mbressman** [thundernest/import-export-tools-ng#252]
I'm trying to convert lots of locally stored emails from Apple/Mac Mail to PST or Office 365.  

I copied over hundreds of thousands of files from a Mac to a PC (top-level MBOX folders containing tons of nested files/folders) that the Mac had been using in Apple/Mac Mail.  I did this initially to try and convert existing emails using a software package that only ran on PC's, but it didn't quite work.

Now trying to use Thunderbird with the ImportExportTools NG extension to maybe import these files/folders to Thunderbird and then export as PST, but no matter what I try I can't get the extension to recognize them since it's a top-level folder called MBOX but contains tons of subfolders and files.

When you try and do an MBOX Import using the extension, you get 4 options - but no matter which option I select and then select the top-level MBOX folder or folder location, nothing happens.  

Any thoughts/help?  Do I perhaps have to run this extension on the Mac that is running Apple/Mac Mail and can't use just copied over MBOX files/folders on a PC?

Thanks!

**Comment by sfhowes** [comment]
The actual mbox file is contained in the .mbox folder exported from Mail app.

https://bugzilla.mozilla.org/show_bug.cgi?id=688166#c23
