### ISSUE TITLE
Import of EML folder with subfolders fails

### ISSUE THREAD

**Issue by kosli** [thundernest/import-export-tools-ng#259]
I am trying to import a folder structure of EML files into TB by using the "Import all message from a directory" -> "also from its subdirectories"

Almost immediately I see the following error in the error console and nothing more happens:
![image](https://user-images.githubusercontent.com/203928/129232963-5e317685-8ff4-4cd2-8dad-eda763f04abd.png)

What could be the issue? Where to start debugging?

TB 78.13.0 on Linux Mint with ImportExportTools NG 10.0.0.4

**Comment by jobisoft** [comment]
I added the fix for this issue to beta3 of the testversion for TB91.
https://github.com/thundernest/import-export-tools-ng/pull/268#issuecomment-919232666

**Comment by kosli** [comment]
@jobisoft  I had only the possibility and need to use it with IMAP folders, so I don't know if it happens only exclusively with IMAP folders.
Thanks for the fix, I will try it in the next few days.

**Comment by jobisoft** [comment]
Further development for TB91 is documented here
https://github.com/thundernest/import-export-tools-ng/issues/264

Please help and check frequently for new beta releases and test them, so we can release an official version soon.

**Comment by kosli** [comment]
@jobisoft  I was not able to test it, as it requires TB91 and I don't have TB91 yet on my Ubuntu system. I will need to see if I can install TB91 somewhere and test the new release of the add-on.

**Comment by jobisoft** [comment]
You need v11 for TB91. Can you retry?
https://github.com/thundernest/import-export-tools-ng/releases/tag/v11.0

**Comment by jobisoft** [comment]
Please use beta 1 for your further tests:
https://github.com/thundernest/import-export-tools-ng/files/7318244/IETools_11_1b1.zip
