### ISSUE TITLE
java script error on search export text

### ISSUE THREAD

**Issue by aar02** [thundernest/import-export-tools-ng#266]
Tools->ImportExportTools NG->search and export->select folder->select search term->select desired messages->export as text->export selected
No file results. instead
JavaScript error: chrome://mboximport/content/mboximport/sdOverlay.js, line 139: TypeError: emlsArray is undefined
-------
java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Comment by jobisoft** [comment]
I added the fix for this issue to beta3 of the testversion for TB91.
https://github.com/thundernest/import-export-tools-ng/pull/268#issuecomment-919232666

**Comment by jobisoft** [comment]
Further development for TB91 is documented here
https://github.com/thundernest/import-export-tools-ng/issues/264

Please help and check frequently for new beta releases and test them, so we can release an official version soon.
