### ISSUE TITLE
ImportExportTools NG not added to "Tools" menu

### ISSUE THREAD

**Issue by jim-moe** [thundernest/import-export-tools-ng#267]
opensuse tumbleweed
Thunderbird 91.0.1

IETNG is no longer added to the end of the Tools menu. It worked in TB 78.x; not in the new version.

Is there another way to invoke IETNG to import mail?

**Comment by jim-moe** [comment]
IETNG v10.0.2

**Comment by bjo81** [comment]
Duplicate of #264

**Comment by jobisoft** [comment]
This is by design. Add-ons should have their options in the add-on manager (indicated by the new wrench symbol), so that the add-on manager is the central place to manage add-ons.

If add-ons need an additional UI entry point, they can use a toolbar button. The tools menu is mostly no longer visible.

**Comment by jim-moe** [comment]
> This is by design.
>
What is by design? The lack a of way to actually use IETNG? I see no wrench icon. The add-on page management options have nothing at all about adding an IETNG button/icon/link anywhere.

**Comment by jobisoft** [comment]
This is the wrench icon for the options, which I was referring to:

![grafik](https://user-images.githubusercontent.com/5830621/133134362-e126c5f9-2508-489d-bcff-d508ab0a6e1f.png)

The IET menu in tools was this:
![grafik](https://user-images.githubusercontent.com/5830621/133134798-f78e2a0a-32d1-412f-8bf5-b6f0150d1a73.png)

But the use of the tools menu is discouraged, and at some point the IET menu should be moved out of there. But probably not yet with the TB91 release.

I was assuming Christopher was already following that new UI concept, but it looks like the version you were running was broken and did not add any UI elements. That is of course not as intended.

The version from https://github.com/thundernest/import-export-tools-ng/tree/v10.1.0 is not full working in TB91, but is adding the menu (for me at least)

**Comment by jim-moe** [comment]
Okay. I will try the dev version.

TB v91.0.3 has neither the menu item on the Tools menu, nor the wrench icon.
![tb-v91-ietng-v10 0 4-2021-09-13](https://user-images.githubusercontent.com/3834167/133144107-dba65724-19be-4860-b532-2f0a12748d94.png)

**Comment by jim-moe** [comment]
Yay! The dev version works! Wrench icon and menu item are there.

**Comment by jim-moe** [comment]
Ah, well damn. The dev IET does not actually import messages. I followed the usual path through directory listings. selected *.eml files, selected Open, and ... nothing.

**Comment by jobisoft** [comment]
That is what I meant with "it is not working". I will try to support Christopher in the next days.

**Comment by jobisoft** [comment]
Whoever has the power to close this issue, please close, as this is basically a "does not work in TB91" and that is covered here (with a new test version in the mentioned pull request):
https://github.com/thundernest/import-export-tools-ng/issues/260#issuecomment-918943962

**Comment by jim-moe** [comment]
Ah. At least it is visible now.

**Comment by jobisoft** [comment]
Further development for TB91 is documented here
https://github.com/thundernest/import-export-tools-ng/issues/264

Please help and check frequently for new beta releases and test them, so we can release an official version soon.

**Comment by AFowle** [comment]
Not clear to me how to install the betas (zip files not xpi). Would love to help test and get this working.

**Comment by jobisoft** [comment]
XPI is ZIP. TB accepts them directly, no need to rename the file.

Instead of downloading the files, you can just drag the link into thunderbirds add-on manger. If you have an older beta, you do not need to remove it, just drag the link of a newer beta and it will update.

**Comment by AFowle** [comment]
Two useful bits of info in one email!

Thank you. All installed now.

*Adrian*
*
*
*
*

**Comment by AFowle** [comment]
Initial observations in Thunderbird 91.0.3 (64-bit) on Opensuse Tumbleweed and IETNG v10.1.0-b5
IETNG has options in Add-ons wrench menu, and working commands in Tools menu
Automatic backup took 10- 20 mins 2.6 GiB and 17,886 files
Manual export just after took only 10s 2.6GiB and 17894 files. Not sure what the difference was!
