### ISSUE TITLE
Can't import zipped backup

### ISSUE THREAD

**Issue by Roen1** [thundernest/import-export-tools-ng#270]
I used IE Tools NG as follows:

Right click on a folder in Thunderbird>ImportExport Tools NG>Export folder (zipped)

Now I need to import the zipped backup, yet I can't get it to work.
Via Thunderbird>Extra>ImportExport Tools NG>Import messages>All file types

Opening the selected backup leads to no result unfortunately.

Can anybody help me solve this problem?

**Comment by mirekgab** [comment]
Hi @Roen1 
Try to do this:
1. unzip zipped backup outside TB
2. in TB choose import mbox file and select unzipped file
