### ISSUE TITLE
I can't import anything!?

### ISSUE THREAD

**Issue by phonebotco** [thundernest/import-export-tools-ng#279]
Hi,
I made an export of all my mails using your extension. Everything is located in a folder.
[https://prnt.sc/1vl9503](https://prnt.sc/1vl9503)
When I want to import, I have 3 options:
Import MBOX doesn't work
Import eml file doesn't see any eml file
3rd option is same than 2nd

Why is it so complicated to import an export I did 5 minutes before?
Please help me.

**Comment by jobisoft** [comment]
[IETools_11_1b1.zip](https://github.com/thundernest/import-export-tools-ng/files/7318244/IETools_11_1b1.zip)
That should update the tree after folders have been added. Can you try? Drag and drop the file link into the Thunderbird Add-On Manager to install it.
