### ISSUE TITLE
AppleMail mbox import issue with structure

### ISSUE THREAD

**Issue by cleidigh** [thundernest/import-export-tools-ng#28]
Issue where mbox files from Apple Mail that have a folder structure do not import the structure.

**Comment by cleidigh** [comment]
( from William)
This is what I know:

- ImportExportTools NG version: 4.0.4
- Thunderbird version: 68.2.0 (32-bit)
- Export from Apple Mail options/file format: There are no options to select. All I do is choose a folder to store the structure.
- Confirm you were using import (mbox?) With subfolders: I am using "Import one or more mbox-files with subfolders" which is option 2.

I am using MacOS Catalina Version 10.15 and Apple Mail version 13.0 (3594.4.19).

My folders are NOT named *. sbd! Just normal folder names.

Top level looks like this:

Folder "Test"
File (which turns out to be a folder as well): "Test.mbox".

**Comment by cleidigh** [comment]
Can you try exporting a simple folder structure with just a couple test e-mails and see if that imports correctly.  YouCould then send me that file so that I can test it as well

**Comment by WilliamNxt** [comment]
Hi Chris
I've created a folder structure looking like this:
Top Level
   Level 1
      Level 2

Each folder holds one email only.

I don't seem to be able to send you the folders, but I have attached some screen shots illustrating how things look from my side.

Let me know how I can get the folder structure across to you.

Text is in Danish (but that is pretty straight forward :))

![Screenshot 1](https://user-images.githubusercontent.com/57028168/67617497-f6194980-f7e3-11e9-88e5-3a4932455f08.png)
![Screenshot 2](https://user-images.githubusercontent.com/57028168/67617499-f6194980-f7e3-11e9-932a-918ea98ee32b.png)
![Screenshot 3](https://user-images.githubusercontent.com/57028168/67617500-f6194980-f7e3-11e9-9838-65cf88ddbb27.png)
![Screenshot 4](https://user-images.githubusercontent.com/57028168/67617501-f6b1e000-f7e3-11e9-97fb-1753b6d7edb2.png)
![Screenshot 5](https://user-images.githubusercontent.com/57028168/67617502-f6b1e000-f7e3-11e9-8075-79ff809ed9fc.png)

**Comment by cleidigh** [comment]
@WilliamNxt 
Thanks!  I assume even with simple export none of the above works in terms of import, correct?
if you enable the debugger under advanced settings are there any errors?
I think I can also create a test export to test.

**Comment by WilliamNxt** [comment]
I've replied by email.

**Comment by cleidigh** [comment]
@WilliamNxt 
I was able to export an inbox folder from Apple Mail 12.0 on Mojave.
it successfully imported on Thunderbird 68.2
I have created a test folder for people to be able to test "controlled" input files.
Can you try to import this file? it contains a single file with about five messages.
https://github.com/thundernest/import-export-tools-ng/tree/master/tests/import/AppleMail/INBOX.mbox

**Comment by cleidigh** [comment]
@WilliamNxt 
Any update/ success?

**Comment by WilliamNxt** [comment]
I'm sorry, but I still need to know how to download the files in inbox.mbox.

**Comment by cleidigh** [comment]
sorry I forget giving or not giving instructions on this
when you get to an individual file there will be able to use the "Raw button", right click on that and bring up able menu where you can save as.
BTW I just went through a couple other issues on OS X with no problem importing so I think we will get to the bottom of this.

**Comment by WilliamNxt** [comment]
This is what it looks like in my folder after save using raw. Can't import.

Could you send me the file and the folder by normal email, please?

![Screen shot after RAW-save](https://user-images.githubusercontent.com/57028168/68183345-7423e000-ff9c-11e9-973e-117ac7641368.png)

**Comment by WilliamNxt** [comment]
Sorry, just found it in my mail folder.

It contains 6 mails, but as you can see, the name of the folder is "mbox.txt".
![Mailbox import 1](https://user-images.githubusercontent.com/57028168/68183556-10e67d80-ff9d-11e9-8930-a7679c9fe162.png)
![Mailbox import 2](https://user-images.githubusercontent.com/57028168/68183557-10e67d80-ff9d-11e9-85f5-b1a8390ea9a5.png)

**Comment by Joergen** [comment]
The reason the folder is named "mbox.txt" is that Windows append the file extension (.txt) to the file when you download / save it to your computer. You might not see the file extension when you look at the downloaded file because Windows hide file extensions for known file types by default.

**Comment by cleidigh** [comment]
@WilliamNxt 
After taking into account the correct comment by @Joergen , it seems as if you imported the mailbox okay.  Any success with your real mail import?

**Comment by WilliamNxt** [comment]
@Joergen's comment unfortunately doesn't change anything.

Please read through my posts again.

I have **never** had a problem importing a **single** mbox-file with a number of emails.

I have two problems:

1.
 The name of the imported folder has the name structure "mbox###" and **not** the folders name, e.g. "Mom" or whatever name the folder had in macMail and when it was eksported. Please note that my posts above I have included a screen shot with a folder with the name "Test Top Level". This is the name the mailbox should be given when imported, not "mbox###". So, problem number 1 is INCORRECT NAMING of imported folders.

2.
Structures are **not** imported as a structure but as "mbox###"-files that are all imported to the same folder in TBird. So, problem number two is NO STRUCTRE.

**Comment by cleidigh** [comment]
@WilliamNxt 
can you e-mail me a simple structured export with junk e-mail so I could test exactly what you are using
test1@kokkini.net

**Comment by cleidigh** [comment]
@WilliamNxt 
I found out that there is a specific option required to export subfolders.  the option button within the dialogue when you save the folder.
I just tested that successfully with a top and 1 subfolder .

I found a reference about the naming structure and some of its oddities.
http://www.needhelp4mac.com/2016/05/export-apple-mail/

**Comment by WilliamNxt** [comment]
Hi Chris

I am on holiday - will be back by Sunday.

Med venlig hilsen / Best regards


cand. jur. William Feely, HD
+ 45 50 50 22 83

**Comment by cleidigh** [comment]
enjoy your holiday!
(good time to forget about e-mail)

**Comment by obar** [comment]
I discussed this topic [in the wrong thread](https://github.com/thundernest/import-export-tools-ng/issues/85#issuecomment-617410968) (oops) and have a python script to reformat mbox exports from Apple Mail. Just tying the background info to the correct issue here.

**Comment by jobisoft** [comment]
Time to close this. See:
https://github.com/thundernest/import-export-tools-ng/wiki
