### ISSUE TITLE
Error message when trying to import mbox file

### ISSUE THREAD

**Issue by android57640** [thundernest/import-export-tools-ng#282]
I got this error message when I try to import a mbox file:
(java script application)
impossible to import in this folder (IMAP type or discussion group)

My softwares:
Windows 10 Family 64 bits: 21H1, build: 19043.1288
Thunderbird version: 78.14.0 (64 bits)
Import/export tools NG: 10.0.2

Any help on this issue ?
Patrice PFEUTY

**Comment by jobisoft** [comment]
The add-on does not allow to import into imap folders, but only into local folders.
