### ISSUE TITLE
Feature Request: Export Single Message

### ISSUE THREAD

**Issue by BewilderedAgain** [thundernest/import-export-tools-ng#297]
I'd like to export a single email with the filename set as specified according to a custom format rules in one step. 

 To make this work at the moment is rather long winded. You have to copy the message to a temporary folder,  then "Export all messages in folder" and finally delete the copy of the message from the temporary folder.

**Comment by jimspoon** [comment]
Try right-clicking single message > Save Selected Messages > select desired export format > select export destination folder.

**Comment by BewilderedAgain** [comment]
Perfect! Thanks.
