### ISSUE TITLE
Cannot get ImportExportTools NG to install in Thunderbird 68.2.0

### ISSUE THREAD

**Issue by ochayethenoo** [thundernest/import-export-tools-ng#30]
I can't use this highly recommended add on yet as it will not install for me.
I've tried several times.  The error message I get in debugging with Firefox is ''_Reading manifest: Error processing xpi-name: An unexpected property was found in the WebExtension manifest._''

**Comment by cleidigh** [comment]
@ochayethenoo 
The error you are referencing is actually a nonfatal warning concerning a manifest entry I use.  I am looking for a better wayit's not a problem.
What version of the extension are you using?  The extension is definitely compatible with 68.2
D o you see the new menus added to Tools or the message and folder menus?
Christopher

**Comment by ochayethenoo** [comment]
Thanks for the swift response.  Interestingly, as a result of your response, I opened Thunderbird to check the version of the extension and was presented with an update to Thunderbird, V 68.2.1.
On updating, I found that ImportExportTools 4.0.4 was now installed.
Although I seem to be able to import individual emails, I am uncertain how to bulk import folders.  Do you have a 'user guide'

**Comment by cleidigh** [comment]
@ochayethenoo 
Excellent.  I agree there should be user guide.  Currently I am just trying to keep up with the changes Thunderbird.  I adopted this to extension when the original author abandon it so I have a lot of catch up.

What type of import do you want to do?  Currently only mbox and EML imports can use subfolders.
these can be imported as complete folders.

**Comment by ochayethenoo** [comment]
I appreciate your help.  I have used an NSF to EML converter to convert snd export my IBM Notes emails, hoping to add them to my Thunderbird email account.  I have one NSF folder containing 124 NSF subfolders each containing a number of EML imports (so probably thousands of files in total).   Is there any way of batch importing  all the EML files?

**Comment by cleidigh** [comment]
@ochayethenoo 
the screenshot below shows the import menu ( with subfolders) for EML messages.
I have heard some issues with massive imports so you might need to stage the imports
That is if you have a problem
![image](https://user-images.githubusercontent.com/25272315/68076118-2a15e100-fd87-11e9-8f61-54470377c31c.png)

**Comment by ochayethenoo** [comment]
I think I may have selected the wrong option originally.   It certainly is working this time.
Very many thanks for your prompt help and advice.

**Comment by cleidigh** [comment]
Great
I'm going to make an enhancement issue for a basic user guide, the extension is complex enough to deserve that.
Reviews are always appreciated on the main Thunderbird site!
cheers

**Comment by cleidigh** [comment]
no problem - reviews on the Thunderbird site are always appreciated!
closing
