### ISSUE TITLE
Thunderbird 98

### ISSUE THREAD

**Issue by SamAtlantic** [thundernest/import-export-tools-ng#305]
Are there any plans to make IE compatible with Thunderbird 98 and beyond.  Some of the responses say IE is not going to be supported going forward.  If not thanks for your past efforts.

**Comment by cleidigh** [comment]
@SamAtlantic 
Working on 102 support now, first beta soon.
Track here
- #324 
@cleidigh

**Comment by cleidigh** [comment]
Closed with v12

**Comment by SamSxty** [comment]
You know I have to thank the open source community for doing this and working over the holiday weekend.
