### ISSUE TITLE
Spanner glyph not displaying

### ISSUE THREAD

**Issue by Scifisicko** [thundernest/import-export-tools-ng#314]
Merging 2 profiles in 91.8.0 (64-bit), exported mail successfully from the host profile with this tool (event though it was displaying as disabled in Manage your Extensions, imported from the donor as .pcv using Mozbackup, went to add the host email back into the profile and the spanner glyph is no longer visible
[No spanner glyph](https://user-images.githubusercontent.com/103465282/162846323-0fffb901-2ece-4a9e-a946-5939dd7c49f9.jpg)

**Comment by Scifisicko** [comment]
Tried this again. This time using the tool to export mail from the donor machine. After successfully exporting mail from the donor, I imported the host's .pcv file into the donor's thunderbird. I went to add back the original donors mail and the spanner glyph had vanished again. Now I have the donors emails on the host machine and the hosts emails on the donor machine....

**Comment by cleidigh** [comment]
@Scifisicko 
Playing catch up.
Can you give version information 
@cleidigh

**Comment by cleidigh** [comment]
Fixed with v12
