### ISSUE TITLE
Compatibilité Thunderbird V 91.8.1

### ISSUE THREAD

**Issue by Pabout39** [thundernest/import-export-tools-ng#316]
Bonjour, J'ai essayé de télécharger/ installer votre module "import-export-tools-ng". L'installation m'est refusée avec le message "n'a pas été installé car n'a pas été vérifié". Y a-t-il une solution? Avec mes remerciements

**Comment by jobisoft** [comment]
You tried to install the add-on in Firefox, which does not work. It is a Thunderbird add-on.
