### ISSUE TITLE
Mbox file size limit?

### ISSUE THREAD

**Issue by JeffCoHale** [thundernest/import-export-tools-ng#323]
I'm trying to import a Gmail mbox file generated from takeout. I did this previously with my account (an 8gig file) and it worked fine. Now I'm doing it for my friend who has a much larger (32 gig) mbox file. When I try to add it nothing seems to happen. When I restart Thunderbird I see a new folder under Local Folders (name of the mbox file) but nothing is there. Is there a limit on the mbox file for import?

**Comment by JeffCoHale** [comment]
Thanks for the feedback. I was able to get around the issue by splitting my file into multiple small files.

**Comment by cleidigh** [comment]
@JeffCoHale 
Excellent, I will close then.
@cleidigh
