### ISSUE TITLE
v12.0.0 (TB 102) Release Status

### ISSUE THREAD

**Issue by cleidigh** [thundernest/import-export-tools-ng#324]
Release : 

https://github.com/thundernest/import-export-tools-ng/blob/master/xpi/import-export-tools-ng-12.0.0-tb.xpi

Status : 

- b1
- 102 compatibility 
- Fix export directory save
- Remove SessionRestore for 102, bypass in 91, chk impl for #284 
- fix pdf/printsettings changes
- b2- Fix SessionRestore race condition 
- b3 - clean, EML export issue  
- b4 -  multi platform fix for import issue 
- v12.0.0 Released 

Issues:

**Comment by TeslaMagic** [comment]
I'm not sure if this is where I should reply to your question; "Also what pref did you change?"

The "Browse" buttons under "Export directories" do not function (at least in Linux). You can select a folder but it does not enter them into the dialog boxes. I've attached a screenshot showing the dialog box after I manually entered the directories into the TB prefs.js file.

Here are all the TB v91.10.0 (64-bit) prefs.js entries for Import-Export-Tools-NG:

user_pref("extensions.importexporttoolsng.autobackup.save_mode", -1);
user_pref("extensions.importexporttoolsng.export.filename_pattern", "%s-%D-%e");
user_pref("extensions.importexporttoolsng.export.use_container_folder", false);
user_pref("extensions.importexporttoolsng.exportEML.dir", "/home/mint/Downloads");
user_pref("extensions.importexporttoolsng.exportEML.filename_format", 2);
user_pref("extensions.importexporttoolsng.exportEML.use_dir", true);
user_pref("extensions.importexporttoolsng.exportMBOX.dir", "/home/mint/Downloads");
user_pref("extensions.importexporttoolsng.exportMBOX.use_dir", true);
user_pref("extensions.importexporttoolsng.exportMSG.dir", "/home/mint/Downloads");
user_pref("extensions.importexporttoolsng.exportMSG.use_dir", true);
user_pref("extensions.importexporttoolsng.printPDF", false);

The lines containing "/home/mint/Downloads" are the ones I either modified or added.

This is only for the Linux version of Thunderbird. I have not tested Windows or Mac.

Thank you for this extension/add-on! It's the most important one, in my opinion.

![Export Directories](https://user-images.githubusercontent.com/16181192/174397238-39a1fc59-902b-477f-82b1-3ec459692a7e.png)

**Comment by TeslaMagic** [comment]
Not sure if this is of any help...

Import-Export-Tools-NG v11.2 does not function in Thunderbird candidates 102.0b8 or 102.0.

The v11.2 manifest.json "strict_max_version" error was corrected before installing.

The extension installed but there was no configuration (wrench) option. If you try export an email, as an example, there is no dialog other than Thunderbird's.

But, after updating the Import-Export-Tools-NG v11.1 manifest.json "strict_max_version" to handle TB 102; it installs, and everything appears to be working except for the "export directories" issue.

**Comment by cleidigh** [comment]
Released
