### ISSUE TITLE
Save selected messages > PDF format .... now prints to default printer

### ISSUE THREAD

**Issue by pivotman** [thundernest/import-export-tools-ng#330]
Hi,

I'm running Thunderbird 91.9.1 (64-bit) with ImportExportTools NG 12.0.0, all under Linux Mint 20.3 Cinnamon. Now any attempts to save an email as a PDF file result in the document being printed on the default printer instead. The dialog to set the output folder is not utilised, even if I change the default printer to a PDF device (cups-pdf:/).

This change has happened in the last day, probably when the ImportExportTools NG plugin was automatically upgraded from 11.2 to 12.0.

Please let me know if you need any more information or want me to test anything further.

Many thanks for your work on this.

Regards,
Brian

**Comment by jeron1** [comment]
Hi, I am having same issue after an update today. Running tb 91.9.1 kde neon 5.25. I use import-export-tools-ng every day. Your work is appreciated.
Geoff

**Comment by cleidigh** [comment]
@pivotman 
I heard about some potential pdf issues,but not sure they are related.
You can roll back while I look into this.
@cleidigh

**Comment by cleidigh** [comment]
@pivotman 
@jeron1 
I just did a quick check  Before crashing using my Mint 20.3 VM and a pdf save worked.  I will try some other things tomorrow and see.
@cleidigh

**Comment by cleidigh** [comment]
@pivotman 
@jeron1 
I am hoping that one change I made for PDFs due to 102 is the issue,
possibly only on Linux.
I can't reproduce it, but who knows...
Track v12.0.1 here:
- #331 

Let me know.
@cleidigh

**Comment by pivotman** [comment]
@cleidigh 
Thank you very much for the quick reply and beta version. I'm thrilled to report that the problem is now solved! Cheers.

**Comment by cleidigh** [comment]
@pivotman 
Excellent, thanks!
Not sure why I cannot reproduce, but I will take it.
My fix is really a reversion for 91 that I could not see.
I will wait for a bit to see what else pops up.
@cleidigh

**Comment by cleidigh** [comment]
@pivotman 
@jeron1 
v12.0.1 with this fix was just released last night.  You may have to manually update.
@cleidigh

**Comment by jeron1** [comment]
It works!! Thank you so much for the speedy update!

**Comment by cleidigh** [comment]
@jeron1 
Good to hear!
Will close up.
@cleidigh
