### ISSUE TITLE
export all messages / just index csv – doesn't export anything at all

### ISSUE THREAD

**Issue by EdStauff** [thundernest/import-export-tools-ng#335]
When I select "Export all messages in the folder" → "just index (CSV)", it asks me to specify a (file system) folder, which I do, but nothing appears in that folder.  It works for "just index (HTML)", but I need CSV.  I tried it both from the context menu of the Tb folder I want to export, and from "Tools" in the main menu bar.
Thunderbird version: 91.11.0 (32-bit)
ImportExportTools NG version: 12.0.1
O.S.:  Microsoft Windows 10.0.18362.959

**Comment by cleidigh** [comment]
@EdStauff 
I did a sanity check with my 91.11 and it looks good.
The export creates a folder under the selected folder. The folder is named according to the filename rules.  The index.csv file is then output to the folder.
If you don't see this then look at the debug console to see any possible output.
@cleidigh
