### ISSUE TITLE
Attachment folder names need file char escaping

### ISSUE THREAD

**Issue by vguogis** [thundernest/import-export-tools-ng#339]
Hello,

Sometimes exporting a folder or bunch of messages to plain text with attachments breaks. I have catched single message of this type, but not sure why it breaks. Couple of messages were exported till this message was reached. Then routine breaks. Please find it as Mbox file in attachment.

[test.zip](https://github.com/thundernest/import-export-tools-ng/files/9231945/test.zip)

**Comment by vguogis** [comment]
And here is another one which breaks. 

[test2.zip](https://github.com/thundernest/import-export-tools-ng/files/9232020/test2.zip)

**Comment by vguogis** [comment]
Maybe as a hint - it looks like a message to undisclosed-recipients could break the routine. My pattern for extended filename and folders is _${date_custom}_-${sender_email}_+${recipient_email}_=${subject}_

**Comment by cleidigh** [comment]
@vguogis 
Your hunch was correct 🥇 
The attachment folder naming lacked the illegal character escaping (with _ )
The undisclosed recipients has a colon, semicolon at the end.
The colon needs escaping.
Note, this may change your search logic.
I also fixed a ui issue toggling the formats.

https://github.com/thundernest/import-export-tools-ng/blob/v12.0.2/xpi/import-export-tools-ng-12.0.2-b2-tb.xpi

@cleidigh

**Comment by vguogis** [comment]
@cleidigh 
Thank you, just tested with emails to undisclosed-recipients and it works as expected.

**Comment by cleidigh** [comment]
Addressed with v12.0.2 Release
