### ISSUE TITLE
Problem with eml import

### ISSUE THREAD

**Issue by Dominiq34** [thundernest/import-export-tools-ng#340]
I cannot import any elm messages from Windows Mail. In the menu, any options concerning eml import are inactive. I have Thunderbird 102, and the newest release of import-export-tools. Windows 10

**Comment by cleidigh** [comment]
@Dominiq34 
Just checked 102.1.2 with IETNG 12.0.1
When right clicking on the import folder you get import messages in the context menu for eml messages.
is that the method you are using?
@cleidigh
