### ISSUE TITLE
export message as eml using a key command (tbkeys)

### ISSUE THREAD

**Issue by librelegal** [thundernest/import-export-tools-ng#341]
As a long standing user of https://github.com/thundernest/import-export-tools-ng/ I need to export messages very often. To do this I need to "walk" along the selected message by mouse and chose export as eml, then the folder (desktop folder). The file name is then as set in https://github.com/thundernest/import-export-tools-ng, at the moment the file name is "name of recipient - reference - date.eml". I would like to do that with keys and had a custom key for a long time but the respective addons were neo longer available for newer versions. Now I use tbkeys but do not know how to form the command correctly. Therefore I asked and got an answer: https://github.com/wshanks/tbkeys/issues/108 

But I do not know how to apply the advice also it seems you as the developer know more about the correct command. Could you please help me out?

**Comment by librelegal** [comment]
There is progress: Will Skanks showed me the right way (see https://github.com/wshanks/tbkeys/issues/108).

**Comment by cleidigh** [comment]
@librelegal 
Good to see you back.
How are you progressing?
There is also a hidden set of hotkeys in IETNG (see end of help)
@cleidigh

**Comment by librelegal** [comment]
Yes, the issue can be closed, thank you.
