### ISSUE TITLE
Cannot import some EML

### ISSUE THREAD

**Issue by Carmina16** [thundernest/import-export-tools-ng#343]
In version 10.0.4, some WLM messages cannot be imported. The Error console contains many error messages like this:
`FirstLine x-store-info:sbevkl2QZ (more base64 content follows)`

**Comment by cleidigh** [comment]
@Carmina16 
Can you indicate OS, tb and IETNG versions.  If possible can you post a non personal eml that fails with the full console output.
if you can't post you can email to me: 
test1@kokkini.net
@cleidigh

**Comment by Carmina16** [comment]
Seems to be fixed in 12.0.1
