### ISSUE TITLE
Subfolder import fails for some folders

### ISSUE THREAD

**Issue by Carmina16** [thundernest/import-export-tools-ng#344]
Import from WLM message store works inconsistently. Some folders do not get imported at all, like this before:

`<import from here>\Storage Folders (2)\Xxxxxxxxxxx xxx\xxxxxxxxx xxxxx\xxxxxxxx\Xx xxxx\XXXXXXXX-XXXXXXXX.eml`

It works when imported directly, so there must be some traversal error.

**Comment by cleidigh** [comment]
@Carmina16 
Can you give some more detail perhaps an exact path, console info etc
@cleidigh
