### ISSUE TITLE
Can't Import Directory Structure

### ISSUE THREAD

**Issue by pdolc** [thundernest/import-export-tools-ng#345]
For email accounts with folders and subfolders, export creates a files structure of '.sbd' folders and email files. That looks right. But none of the import options recreates the same structure and/or populates the subfolders with emails. Either it flattens the entire folder structure, or doesn't populate the subfolders. My use case is: 1) I work on a project (e.g. "ProjectX") where someone gives me an email account (e..g "joe@projectx.com"), where I create folders/subfolders for email; 2) the project is ending and I'll be losing access to the account, but I want access to the email, so I do an export with ImportExportToolsNG; 3) I create an email folder in "Local Folders" (or some IMAP account I 'own') called ProjectX; 4) I highlight that account, and try all the various import options in ImportExportToolsNG, but none recreate the folder structure with email. Seems like a "standard" use case: 1) Export; 2) Import. Can't figure out what I'm doing wrong.

**Comment by cleidigh** [comment]
@pdolc 
Thanks for the post.
With TB102 and IETNG 12.0.1 you should be able to do the following : 
- Export your tree to structured mboxes (i think you have this)
- For importation choose Import mbox
- In the dialog choose the second option import with structure 
- in the file picker choose the top mbox file, the sbd tree will then be imported.

I am currently working on a rewrite of this with more progress and handling of some message errors. I can give that for testing as well.
@cleidigh

**Comment by pdolc** [comment]
Really appreciate the reply, but the fourth bullet in your suggested direction doesn't really work as you describe. When I choose the 2nd option (import with structure), I *do* get a file picker, but when I select the top-level directory (the directory that contains the export), it just opens that top-level directory and shows me the content, and wants me to pick from within the directory. There's not really a "top level" mbox file. See below.
<img width="548" alt="Screen Shot 2022-09-06 at 6 50 58 PM" src="https://user-images.githubusercontent.com/1354591/188753905-db87b1b1-d831-4d63-8d2a-c8b5f475e762.png">

**Comment by cleidigh** [comment]
@pdolc 
With option 2 you are choosing one or more mbox files, if these have sbd directories they are imported recursively. The fourth option is something I am working on.
I think maybe you would like the directory import which you might consider "top level"
Does that work for you?
@cleidigh
