### ISSUE TITLE
problem with use then auto repaired

### ISSUE THREAD

**Issue by dindoun** [thundernest/import-export-tools-ng#346]
Hi,
I had installed import-export-tools-ng long time ago without use
I needed it today, but it has disappeared from tools menu ( outils in french ) 
I tried update , nothing
I uninstalled then install : nothing 
I uninstalled then install : the menu is back

(Thunderbird 91.13.0)

**Comment by cleidigh** [comment]
@dindoun 
Sorry for the confusion.
As I understand now you are all set and working?
Sometimes updates just have issues.
Doing a restart after uninstall is usually a good thing to do.
@cleidigh
