### ISSUE TITLE
Thunderbird debug error message

### ISSUE THREAD

**Issue by JohnC654** [thundernest/import-export-tools-ng#35]
I get this debug message in the current version of TB, for v4.0.4 of this extension: "Reading manifest: Error processing xpi-name: An unexpected property was found in the WebExtension manifest." Thought you would want to know.

**Comment by cleidigh** [comment]
@JohnC654 
Thanks for the heads up!  Actually this is really a Warning (nonfatal/no problem created)
it's actually the extension loader griping about a custom entry I have in the manifest file.
you can ignore warning it causes no problems.  But I'm working on a solution that doesn't throw a warning.

**Comment by JohnC654** [comment]
Glad I could help, Christopher. I actually created a Github account just so I could communicate the info to you. I'm not a programmer.

Regards,
John Corliss


     On Thursday, November 7, 2019, 3:12:22 PM PST, Christopher Leidigh <notifications@github.com> wrote:  
 
 
@JohnC654
Thanks for the heads up! Actually this is really a Warning (nonfatal/no problem created)
it's actually the extension loader griping about a custom entry I have in the manifest file.
you can ignore warning it causes no problems. But I'm working on a solution that doesn't throw a warning.

**Comment by cleidigh** [comment]
@JohnC654 I appreciate you doing that.
the truth is tracking bugs/issues/enhancement requests are the real use of GH beyond the obvious source.  It's great for that, great for developers, but kind of awkward to have to set up an account as a pure product user to post a bug.  We (the Thunderbird team)  are looking at improvements.
probably dedicated support e-mails.
Thanks for using the extension and Thunderbird!
I will go and close
