### ISSUE TITLE
`From:` field silently dropped on `eml` export

### ISSUE THREAD

**Issue by fvanmaele** [thundernest/import-export-tools-ng#350]
This happened to me with certain outlook where `From:` looks like this:
```
From: Ferdinand Vanmaele
	<IMCEAEX-_O=FIRST+20ORGANIZATION_OU=EXCHANGE+20ADMINISTRATIVE+20GROUP+28FYDIBOHF23SPDLT+29_CN=RECIPIENTS_CN=0003BFFD022DD2F4@sct-15-20-4755-11-msonline-outlook-03a34.templateTenant>
```
the exported `eml` only has:
```
	<IMCEAEX-_O=FIRST+20ORGANIZATION_OU=EXCHANGE+20ADMINISTRATIVE+20GROUP+28FYDIBOHF23SPDLT+29_CN=RECIPIENTS_CN=0003BFFD022DD2F4@sct-15-20-4755-11-msonline-outlook-03a34.templateTenant>
```
I've attached the email exported by Thunderbird and the one from import-export-tools.

[sample_email.zip](https://github.com/thundernest/import-export-tools-ng/files/9597955/sample_email.zip)

**Comment by cleidigh** [comment]
@fvanmaele 
Thanks for the post.
From lines have issues as they are used as message delimiters.
I am currently working on several improvements and rewrites in this area. This has not been reported thus far.
Couple of questions to help me : 

You referred to Outlook above, how does this relate to a TB export?
Can you id the OS, TB and IETNG versions.
@cleidigh

**Comment by fvanmaele** [comment]
Hi, thanks for the quick reply. I use Thunderbird with an outlook.de 
account, containing the mentioned emails. I exported the emails with IETNG.

Versions:
OS: Windows 10 21H1 19043.2006
Thunderbird: 91.13.0 (32-Bit)
IETNG: 12.0.0

**Comment by cleidigh** [comment]
@fvanmaele 
Thanks.
I should have asked also if this message always exports without the From or is it inconsistent. Are there other messages that do this?

I will try to reproduce, however, I cannot reproduce your environment exactly so we will see.
@cleidigh

**Comment by fvanmaele** [comment]
The message exports consistently as described. It also occurs with 
messages with a similar From: field (long address placed on a separate 
line, below From: Name).

I have not observed the behavior with other messages (shorter address 
placed directly after From: Name).

Am 20/09/2022 um 00:05 schrieb Christopher Leidigh:

**Comment by cleidigh** [comment]
ok
How about if you copy the email to a local folder then export from there?
The db may have an issue that might be corrected with a copy.
@cleidigh

**Comment by fvanmaele** [comment]
When I copy the email to a local folder, the following fields are appended:

X-Mozilla-Status: 0001
X-Mozilla-Status2: 00000000
X-Mozilla-Keys:

and the export with IETNG is correct.

When I place the message in the outlook mailbox, the fields above are 
not appended, and the export drops the From field as mentioned before. I 
have also tested with a different mailbox and a new Thunderbird profile 
with the same result.

Am 20/09/2022 um 00:33 schrieb Christopher Leidigh:

**Comment by cleidigh** [comment]
Good that gives us some more clues. I have to try some experiments.
@cleidigh

**Comment by cleidigh** [comment]
@fvanmaele 
I cannot find a way to get the email into my system. Anything that gets modified like an import does not help.
I have one other test idea.
If you can make a test folder (under imap) with another non private message plus the message in question - now see if exporting from there still produces the problem.  If so I can help you grab that mbox and I may be able to get that into my system.
@cleidigh

**Comment by fvanmaele** [comment]
Sorry for the delayed response. I made a test folder as requested. Exporting from there (`ImportExportToolsNG > Export all messages in the folder > EML format`) still produces the problem - however, the sender is partially displayed in the generated `index.html`.

I'm attaching the mbox of that folder and the exported output.
[test.mbox.zip](https://github.com/thundernest/import-export-tools-ng/files/9654531/test.mbox.zip)
[test_20220927-1219.zip](https://github.com/thundernest/import-export-tools-ng/files/9654510/test_20220927-1219.zip)

**Comment by cleidigh** [comment]
@fvanmaele 
I got sidetracked with a critical pdf bug...
I reproduced it!
I can get the same export results now.
I will look at debug results.
From my experience this is an odd format.
@cleidigh

**Comment by cleidigh** [comment]
@fvanmaele 
I tracked it down, here is a beta, it successfully exports your email on my system.

https://github.com/thundernest/import-export-tools-ng/blob/v12.0.2/xpi/import-export-tools-ng-12.0.2-b7-tb.xpi

@cleidigh

**Comment by fvanmaele** [comment]
I can confirm the beta version fixes my issue.  Thank you very much!

**Comment by cleidigh** [comment]
@fvanmaele 
Excellent, thanks for testing so quickly!
Watch #338 for the release status. Reviews always appreciated  ;-}
@cleidigh
