### ISSUE TITLE
PDF export fails on TB 102.2.2 Linux - [Beta fix]

### ISSUE THREAD

**Issue by davemosk** [thundernest/import-export-tools-ng#351]
Attempting to export a single message to PDF fails on TB 102.2.2 on Linux. it fails silently, without any error indication - just no file exported. I'm happy to provide more info, just tell me what you need.

**Comment by davemosk** [comment]
![image](https://user-images.githubusercontent.com/2114157/191656819-c4e02ff7-4f23-42de-b491-ed085a36ecfd.png)

**Comment by cleidigh** [comment]
@davemosk 
I will fire up my Mint vm...
In the meantime can you id the IETNG version?
Also can you confirm other operations work such as eml export.
Did this work previously?
@cleidigh

**Comment by davemosk** [comment]
I'm on IETNG 12.0.1 - thanks for looking into this!

**Comment by cleidigh** [comment]
@davemosk 
So my sanity check on Mint 23, IETNG 12.0.1, TB 91.11 works.
I forgot that the last rev was specifically to address pdf output on *nix platforms. I suspect some driver change. I will see about 102.2
@cleidigh

**Comment by davemosk** [comment]
Thanks so much @cleidigh

**Comment by cleidigh** [comment]
@davemosk 
When you stated above about working in a previous version did you mean a prior version of TB or IETNG.
I ask because it looks like TB internal pdf driver is at issue so this makes it a lot more ambiguous to solve.
@cleidigh

**Comment by davemosk** [comment]
I believe the update to the new version of TB triggered the add-on upgrade. Is there any more info I can gather that would help?

**Comment by cleidigh** [comment]
@davemosk 
Thanks.
Since I can reproduce it i have what I need for now.
It works in Windows and so I already can see it's inside the print engine on Linux, probably OSX, have to check.
I have to look at a workaround, I am working on that, but it won't be a quicky.
I will post something when I have it.
@cleidigh

**Comment by davemosk** [comment]
Thanks @cleidigh !

**Comment by cleidigh** [comment]
@davemosk 
So i am down the rabbit hole...
No luck yet. I am crossing my fingers as Save to pdf works through the ui.
@cleidigh

**Comment by cleidigh** [comment]
@davemosk 
Well you probably were giving up on me, but I have been working on this nonstop.  I actually was giving up this morning when I had one more try.
It was a buried TB change that crossed windows and Linux.
This is beta I have some more things to do before I will release.
https://github.com/thundernest/import-export-tools-ng/blob/v12.0.2/xpi/import-export-tools-ng-12.0.2-b6-tb.xpi
@cleidigh

**Comment by davemosk** [comment]
@cleidigh 
I never gave up on you mate, I know you're super busy. I've installed the new xpi and it works like a charm! Profuse thanks!
Let me know if you'd like me to do further testing before you release.
With gratitude and warm regards - @davemosk

**Comment by cleidigh** [comment]
@davemosk 
Thanks for testing, excellent!
I will post subsequent beta.
This was a big relief as this is a key feature. I am going to add some progress output that has been sorely missing.
Reviews are always welcome  ;-}

@cleidigh

**Comment by atmelino** [comment]
This fixed it for me on Ubuntu 22.04 as well!
Thank you so much!

**Comment by cleidigh** [comment]
@atmelino 
Great.
Watch for the release here : 
- #338 

@cleidigh

**Comment by BjornW** [comment]
Just letting you know the beta fix works for me as well. Running TB 102.2.2 on Ubuntu 22.04. Thank you!

**Comment by cleidigh** [comment]
@BjornW 
Great.
I should be releasing soon.
@cleidigh

**Comment by cleidigh** [comment]
v12.0.2 is in the review Q

**Comment by cleidigh** [comment]
Addressed with v12.0.2 Release
