### ISSUE TITLE
WHAT is saved and HOW to re-Import

### ISSUE THREAD

**Issue by AdiMiraMichaels** [thundernest/import-export-tools-ng#363]
Import...tools 12.0.0
Thunderbird 102.5.0
Win 10 Pro

Debug
1669209684752	addons.xpi	WARN	Checking C:\Program Files (x86)\Mozilla Thunderbird\distribution\extensions for addons
tb.account.size_on_disk - Trying to set an unsigned scalar to a negative number. 14
Start: ExportFolders (mbox) [mboximport.js:754:10](chrome://mboximport/content/mboximport/mboximport.js)
   Subfolders: false [mboximport.js:757:10](chrome://mboximport/content/mboximport/mboximport.js)
   Structured:  false [mboximport.js:758:10](chrome://mboximport/content/mboximport/mboximport.js)
   Local:  true [mboximport.js:759:10](chrome://mboximport/content/mboximport/mboximport.js)
   Zip:  false [mboximport.js:760:10](chrome://mboximport/content/mboximport/mboximport.js)
Array [ XPCWrappedNative_NoHelper ]
[mboximport.js:761:10](chrome://mboximport/content/mboximport/mboximport.js)
Using exportSingleLocaleFolder [mboximport.js:792:11](chrome://mboximport/content/mboximport/mboximport.js)
Start: exportSingleLocaleFolder [mboximport.js:853:10](chrome://mboximport/content/mboximport/mboximport.js)
   SrcPath:  C:\Users\Michael\AppData\Roaming\Thunderbird\Profiles\8tyhyz60.IETimport\Mail\smart mailboxes\Inbox [mboximport.js:854:10](chrome://mboximport/content/mboximport/mboximport.js)
   Folder:  Posteingang [mboximport.js:855:10](chrome://mboximport/content/mboximport/mboximport.js)
Start backup check
WebExtensions: Open dialogue [messengerOL.js:298](chrome://mboximport/content/mboximport/messengerOL.js)
WebExtensions: openModel [messengerOL.js:300](chrome://mboximport/content/mboximport/messengerOL.js)
NS_ERROR_FAILURE: No directory for uri=jsaddrbook://impab-1.sqlite [AddrBookManager.jsm:266](resource:///modules/AddrBookManager.jsm)
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>".
3 [blank](about:blank)
LoadsHelp [help.js:4:10](chrome://mboximport/content/mboximport/help.js)
WebExtensions: Open dialogue [messengerOL.js:298](chrome://mboximport/content/mboximport/messengerOL.js)
WebExtensions: openModel [messengerOL.js:300](chrome://mboximport/content/mboximport/messengerOL.js)
Start backup check
profile start
profile start 2
Der Aufruf von 'preventDefault()' auf einem Ereignis des Typs ‘DOMMouseScroll’ von einem als 'passive' registrierten Listener wird ignoriert. [browser-custom-element.js:1438:19](chrome://global/content/elements/browser-custom-element.js)
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>".
5 [blank](about:blank)
Diese Seite befindet sich im Fast-Standards-Modus ("almost standards mode"). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>".
[{9bfd36f5-a018-4908-8451-7579b4da613b}](moz-nullprincipal:{9bfd36f5-a018-4908-8451-7579b4da613b})
Diese Seite befindet sich im Fast-Standards-Modus ("almost standards mode"). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>".
[blank](about:blank)
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>".
[INBOX>160](imap://y311323_0-verindrach@imap.1blu.de:993/fetch%3EUID%3E/INBOX%3E160)
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>".
5 [blank](about:blank)
1669217144480	addons.webextension.dropbox-cloudfile@darktrojan.net	WARN	Loading extension 'dropbox-cloudfile@darktrojan.net': Reading manifest: Warning processing cloud_file.data_format: This property is deprecated
1669217144480	addons.webextension.dropbox-cloudfile@darktrojan.net	WARN	Loading extension 'dropbox-cloudfile@darktrojan.net': Reading manifest: Warning processing cloud_file.service_url: This property is deprecated
1669217144483	addons.webextension.dropbox-cloudfile@darktrojan.net	WARN	Loading extension 'dropbox-cloudfile@darktrojan.net': Reading manifest: Warning processing cloud_file.data_format: This property is deprecated
1669217144483	addons.webextension.dropbox-cloudfile@darktrojan.net	WARN	Loading extension 'dropbox-cloudfile@darktrojan.net': Reading manifest: Warning processing cloud_file.service_url: This property is deprecated
1669217145588	addons.webextension.dropbox-cloudfile@darktrojan.net	WARN	Loading extension 'dropbox-cloudfile@darktrojan.net': Reading manifest: Warning processing cloud_file.data_format: This property is deprecated
1669217145588	addons.webextension.dropbox-cloudfile@darktrojan.net	WARN	Loading extension 'dropbox-cloudfile@darktrojan.net': Reading manifest: Warning processing cloud_file.service_url: This property is deprecated
1669217145590	addons.webextension.dropbox-cloudfile@darktrojan.net	WARN	Loading extension 'dropbox-cloudfile@darktrojan.net': Reading manifest: Warning processing cloud_file.data_format: This property is deprecated
1669217145591	addons.webextension.dropbox-cloudfile@darktrojan.net	WARN	Loading extension 'dropbox-cloudfile@darktrojan.net': Reading manifest: Warning processing cloud_file.service_url: This property is deprecated
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. [cleidigh](https://addons.thunderbird.net/de/thunderbird/user/cleidigh/)
Das Cookie "sessionid" verfügt über keinen gültigen Wert für das "SameSite"-Attribut. Bald werden Cookies ohne das "SameSite"-Attribut oder mit einem ungültigen Wert dafür als "Lax" behandelt. Dadurch wird das Cookie nicht länger an Kontexte gesendet, die zu einem Drittanbieter gehören. Falls Ihre Anwendung das Cookie in diesen Kontexten benötigt, fügen Sie bitte das Attribut "SameSite=None" zu ihm hinzu. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. [cleidigh](https://addons.thunderbird.net/de/thunderbird/user/cleidigh/)
Content Security Policy: Ignorieren von "'unsafe-inline'" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "https:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "http:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "'unsafe-inline'" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "https:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "http:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "'unsafe-inline'" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "https:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "http:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "'unsafe-inline'" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "https:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "http:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "'unsafe-inline'" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "https:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "http:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "'unsafe-inline'" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "https:" innerhalb script-src: 'strict-dynamic' angegeben
Content Security Policy: Ignorieren von "http:" innerhalb script-src: 'strict-dynamic' angegeben
Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>".

Hey,
I made a mistake. I moved a domain and forgot to move the older mails before. Now they are deleted. Shit happens.
But I created backups every few weeks. I was an IMAP-Account.
1) WHAT was backed up?
2) HOW to get it back? Nearly all import-options are "grey" -- no function.

Regards
Michael

**Comment by cleidigh** [comment]
@AdiMiraMichaels 
Can you give me a little more context?
You made full profile backups and now...
Are you trying to just restore the old mail?
@cleidigh
