### ISSUE TITLE
ng 12.0.2 incompatible with TB 109.0b2 (32-bit)

### ISSUE THREAD

**Issue by horseshelpinghorses** [thundernest/import-export-tools-ng#373]
Will not install, says incompatible.
109.0b2 (32-bit)

**Comment by cleidigh** [comment]
@horseshelpinghorses 
Currently IETNG is compatible with Thunderbird 91.* & 102.*
It is not compatible with beta versions, that will come later.
@cleidigh

**Comment by cleidigh** [comment]
Can I close this?
