### ISSUE TITLE
Import-Export-Tools NG

### ISSUE THREAD

**Issue by discodiver** [thundernest/import-export-tools-ng#374]
Any news?
I want to email you directly but dont know yours...

Many of us still use eudora, with the modifications done from Hermes...
https://sourceforge.net/projects/hermesmail/

install and test with the above for any MBX samples.

With the new oauth2 being forced on all of us, a converter is desperately needed to get the hermes eudora version usable on Thunderbird v102.x, as hermes is not making an oauth2 update.

what you offer now does not work, as it does not see MBX files properly.

Thunderbird does not read what ANY converter produces that I have found.

SysTools was the most promising with the different types mentioned, but failed.
https://www.systoolsgroup.com/mbox-to-outlook-converter.html

and i refuse to use Outlook, provider forces you to use their email service if i did.

Like many others, i have decades of email saved via eudora... if i have to, use both for referencing old and writing new.

**Comment by cleidigh** [comment]
@discodiver 
This is the same issue as #368 , yes?  I would like to roll it together so we keep the discussion in one place.  There I had asked a couple of questions.
You can email me at:
test1@kokkini.net
I will ask a couple more questions in #368 
@cleidigh

**Comment by cleidigh** [comment]
Closing as dup
