### ISSUE TITLE
Export with folder

### ISSUE THREAD

**Issue by miho-png** [thundernest/import-export-tools-ng#377]
Hello, I use thunderbird on pop3. Now I need to move the current e-mail to imap, but I can't do it. I can't figure out how to create an export with folders. Thank you for your help.

**Comment by cleidigh** [comment]
@miho-png 
If I understand your question, you want to export your pop account, change your account to imap and then re-import your messages?

If so the easiest way is to export the entire account and then import the individual folder mboxes you need.
To export the entire account, right click on the account name in the folder tree, choose Import export tools\Export Folder with structure and choose the location.

@cleidigh

**Comment by miho-png** [comment]
> @cleidigh 
please can you advise me?

**Comment by cleidigh** [comment]
@miho-png 
For import you must use a local folder for the import location.
Right click on the import folder and choose the Import mbox file. Then in the dialog choose the first option for a single mbox file.
Then do this for any mbox files you exported that you now want to import.
@cleidigh

**Comment by miho-png** [comment]
Impot mbox file reports to me.

Impossible to import in this folder (imap or newsgroup type)

**Comment by cleidigh** [comment]
As I said you have to import to a folder under Local Folders, not to an imap folder.
@cleidigh

**Comment by miho-png** [comment]
Where can I find the local folder part? Or do I have to create one? I'm stuck at this point.

**Comment by cleidigh** [comment]
@miho-png 
In the folder \ Account tree at the bottom there will be a pseudo account called Local Folders, right click and choose New Folder.  This will be the folder you import to from my instructions above.
@cleidigh

**Comment by miho-png** [comment]
Thank you, that's how it goes. But I have a problem that I can't import everything. It always stops at one and the same point (folder) and then no more data can be inserted into IMAP

**Comment by cleidigh** [comment]
@miho-png 
Can you capture the console output to see if there are any Errors?
@cleidigh

**Comment by miho-png** [comment]
Good day,

export to local folders worked. The only thing I had to change was the name. I couldn't drag a file with a dot in the name from the local folder to the target folder.

**Comment by cleidigh** [comment]
@miho-png 
Great I am glad you got everything working!
Is it ok to go ahead and close this issue?
@cleidigh

**Comment by miho-png** [comment]
Yes thank you.
