### ISSUE TITLE
Unable to install to Ubuntu Thunderbird 102.4.2

### ISSUE THREAD

**Issue by hdbikeroh** [thundernest/import-export-tools-ng#379]
I get the permissions warning box with 'Cancel/Add', but neither does anything.  I can only dismiss that screen by hitting the ESC key.

This behavior is the same if I use the '+Add to Thunderbird' button or if I download the 12.0.2-tb.xpi file from GitHub and use the 'Install from File' methods.

**Comment by cleidigh** [comment]
@hdbikeroh 
Have you tried installing other extensions?
Have you looked at the console output?
@cleidigh

**Comment by moltra** [comment]
I am not sure if this is related, because I do get the installed complete.  

![image](https://user-images.githubusercontent.com/1578492/216098279-2c618da2-0bd3-40f2-b2ca-2fad32e03c3a.png)

**Comment by cleidigh** [comment]
@moltra 
So you installed and are able to use the extension?
I test on my Mint vm without issue.
@cleidigh

**Comment by cleidigh** [comment]
@hdbikeroh 
What about installing other extensions, does that work?
The errors you see do look relevant.
@cleidigh

**Comment by hdbikeroh** [comment]
Thanks.  I have reported the problem to Thunderbird, as I am unable to install any extensions (a few others have reported the same issue).

**Comment by cleidigh** [comment]
Great, good luck
@cleidigh
