### ISSUE TITLE
import window only offers outlook and Becky 

### ISSUE THREAD

**Issue by revlry** [thundernest/import-export-tools-ng#38]
I just downloaded the latest version of Tbird 68.2.1 and the latest of this add on. When I go to the import tool it does not allow me to select mbox files location. The only options are Outlook and Becky.

**Comment by cleidigh** [comment]
@revlry 
you are actually looking at the built-in 'Import' menu of Thunderbird, not for extension menus.
See #18 
I know this is a little bit confusing.  when I get a moment I'm going to be doing small user guide.
#33

**Comment by revlry** [comment]
Ok I see the menu within the mail folder. However, when I selected import mbox files I received the error "Impossibile to import in this folder (imap or newsgroup type)"

**Comment by cleidigh** [comment]
menus get installed on Tools, message and folder menus as well as search
import to a local folder, some operations are not for the server folders.  to be honest I have not determined all of the issues with that yet

**Comment by cleidigh** [comment]
@revlry 
I thought I would reiterate that the extension explicitly tells not allow importing into the server folders.
you should import to a localfolder

**Comment by cleidigh** [comment]
closing as I understand no problem...
