### ISSUE TITLE
backup instructions

### ISSUE THREAD

**Issue by Robintes** [thundernest/import-export-tools-ng#384]
can you pls advise (publicly) the exact procedure - not only for creating a scheduled backup of TB ac BUT  also exactly how to import said latest backup in the event of a HDD crash or other such disaster - assume that the backup is kept on usb stick/disc say

perhaps this already works but I found that say CnP a roamin/ TB/profile from explorer didnt work - unless you also had the .ini file with it (they didnt say that)

**Comment by cleidigh** [comment]
@Robintes 
Can you elaborate on your last statement, I don't know what CnP... Is.
Also what .Ini file?
Thanks 
@cleidigh

**Comment by Robintes** [comment]
Hi Chris - love your app its what we need

CnP cut and paste. standard explore file operations

profiles.ini file this sits alongside the Profiles folder

[image.png]

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by cleidigh** [comment]
@Robintes 
Thank you!
I am not on my dev computer so I want to check a couple of things tomorrow. I will do a bullet like explanation as it's hard for me to do long prose being disabled.

Are you working with a standard profile? In your cut and paste statement you had the word roamin, not sure if you meant roaming?
Just want my facts straight.
@cleidigh

**Comment by Robintes** [comment]
yes roaming (finger trouble), standard mode.

I had real trouble trying to migrate my TB account across to a new machine. Lots of the so called web help is utter rubbish, made real hard work of it and were mostly out of date with current TB version and also (written by tech journos - I hate these people, waste your time with bogus dead end issues only to try and sell you some solution. It took me hours down wasted paths. It turned out the task was really simple but needed an order of precedence for actions (including the profiles.ini whi all the waste of space wizards didnt mention)

Now i need to be sure that the buckup and restore feature actually works start to finish. Dont want to find my backup folder wont restore at the final count. Do I remove and reinstall TB? app, including old profiles, cookies? I kept arriving at my old set up not my transfer set up that I wanted. TB also confuses you with its help sites as you can have several profiles with different uses, eg domestic vs business etc. I wasted hours on it all for a simple purpose

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by cleidigh** [comment]
@Robintes 
I have been looking at a couple of things since much has changed in 102.
I also have not worked on the backup in a long time and wanted to see what is the latest. I am having difficulty getting a test setup as my computer has tons of Thunderbird versions and 20+ profiles.

I probably need to get a win vm up to have a clean environment.
To get a starting point, are you assuming a totally fresh start? No TB installed?

Like you found there is a lot of twists to this.  TB102 has a couple of new import methods, however, upon testing they seem to not include Extensions and their data, go figure.

Did I understand you did a manual copy and then copied profiles.ini ?
I am trying to see the best, least manual way with 102.
@cleidigh

**Comment by Robintes** [comment]
Hi Chris BTW I have TC 102.7.0 64Gb

Im glad you see my point about the dilemma we all face when a crash happens. I suddenly realised how vulnerable we are unless we have made a retrievable local backup. I have accumulated 10Gb over a decade of personal stuff and most of it is probably fit for trash, but deciding what is far more difficult than just leaving it on file. Never know when some old file might be needed syndrome. Today storage is cheap and a 64Gig stick is easy.
I dont know how TB files are stored in profile but I see stuff can be kept as readble HTML. How 10Gig of that would pan out?

Yes I cleaned out my TB on my pc and started with a fresh installation. I manually copied profile across and didnt use any of the TB wizards. Ensuring I had the same file structure with the Profiles Folder and the Profiles.ini file alongside. The TB seemed to power up ok
That procedure if written down properly was actually quite simple. All the other stuff on the Web was crap - I hate Tech Journos as a species - blatantly deceitful and time wasting , always with a personal angle "look how smart I am " but dont tell you the whole story and leave out vital steps/info so you fail, then offer to help you with some product like Minitools $$ that will help.

Trying to make it all auto from your app may not be the best way - lots of your time and wont work with previous vers of TB etc. IMHO a simple manual system. Most people who would use your app would surely handle that.

I have a duplicate pc coming in a few days which I shall use as a sandbox. So Id be happy to help try out your revised app with its tweaks to help. I know that you can be too close to your baby to see the issues in front of a User - common problem.
Certainly your app deserves much more exposure cos its an essential part of such an Email system. Im surprised it hasnt surfaced more prominently in the public domain. I guess - like I did - you take email security for granted. BTW Gmail is a lot less cooperative given their obsession with market domination
Certainly Im going to make a donation to the cause. I see you are in bed with TB so thats a good sign😜

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Robintes** [comment]
OBTW Chris do you have any views on this type of equipment for use as a keylogger.
https://www.keelog.com/keygrabber-pico/

Let me say straight away that I have no malicious intent whatsoever in such a practice. It would only ever by used myself on my private machine as a means of recording what keystrokes I make during coding and s/w installation. For example, it would have been extremely useful in my battle with trasnferring TB. It could show me exactly what I did as I cant rely on my memory as to what I did a few hours back or ysterday.
Its even more frustrating dealing with awful Google which gets you so sign in with an asteric window but doesnt show what you have done. you get several pages along only for it to tell you that you failed and you cant check why or if its a typo.

I looked at the s/w solutions but all the commercial ones are disallowed on W11. (W10 apparently had an inbuilt keylogger as part of their spell check untill they found people using it as spyware. M $ really are dumb at times. I dont like the idea of installing service type code to do what is a simple job - made difficult by M $

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by cleidigh** [comment]
@Robintes 
I am not sure what you mean by in bed with TB, but I have been on the TB council and am an associated team member focusing on add ons. I also work with the addon module owner and core team for TB, so yeah I guess I am in bed...

While I have taken over IETNG for several years,I am not the original author so sometimes I have to really look closely at things. Almost all of my time and additional work has been in the export and import side Which I can do in my sleep. I have not made additions to backup in a while and ironically not had to deal with restore issues so I am doing my best to give you good info.

The extension actually has pretty good visibility as the # 1 extension with 250k users and info on the web.  It does lack documentation and I wish I could do it, but not with my ALS programming by eye gaze...

Your exasperation is noted, there is never enough support and unfortunately there is a disconnect between  TB and extension support.

Anyway I am focusing on verifying the profile import which actually removes the manual stuff. It was done a while ago so I am checking on TB 102 compatibility.
@cleidigh

**Comment by cleidigh** [comment]
@Robintes 
Sorry I have no experience with any keyloggers.
@cleidigh

**Comment by cleidigh** [comment]
@Robintes 

offline yesterday...

So for a manual approach (what you did)

Importing a full profile backup created by IETNG or a manual copy : 

- Install a new copy of Thunderbird, it should be the latest of the same main ESR release used for the backup. 
- When first Running Thunderbird it will start the account wizard to create an initial account. You should cancel.
- Now exit Thunderbird 
- Your Thunderbird profiles are stored in : 
Windows: C:\Users\UserName\AppData\Roaming\Thunderbird\Profiles.
- Open this location, you will see the default release profile directory under the Profiles directory 
- Copy your backup directory under the Profiles directory, Note your backup directory name must be its original id name.
- Now you also need the original backup of the profiles.ini file
- Copy this file over the newly installed file in the parent directory, Thunderbird 
- The backup profiles.ini will point to your original profile
- When you restart Thunderbird it should use your original profile 

Note there is also the method of copying your profile over the initial default.release profile. This method does not require that you have a profiles.ini file nor does it require your original profile id/directory container.

IETNG approach : 
- Install Thunderbird as above, skipping the wizard
- Install IETNG from the tools menu 
- From the tools menu click the new IETNG menu.
- You will see an import profile option, choose that
- Give your directory information and a name for your profile 
- When you restart you can choose your profile in the profile manager and make it your default profile.
- This method avoids any profiles.ini manipulation directly.

If you want any discussion on your sandbox experiments, let me know

@cleidigh

**Comment by Robintes** [comment]
Yes that what I did today - it was a breeze.
[image.png]

Manual method to copy TB profile to new m/c

Importing a full profile backup created by IETNG or a manual copy :

- Install Thunderbird on target m/c, same release as used for the original m/c.

- When first Running Thunderbird it will start the wizard to create an initial account. Cancel this

- Exit Thunderbird

Your Thunderbird profiles are stored in -
Windows: C:\Users\UserName\AppData\Roaming\Thunderbird\Profiles

Open TB location, you will see the Profiles File Folder

-

Rename profiles.inito profiles.bak Paste your original profile.ini in place

- Open Profiles File Folder delete existing .default folder

- Paste original .default file into the Profiles File Folder as replacement

- Open Profiles file Folder and rename the old file to xxxxxxxx.bak

- Restart Thunderbird it should use your original profile

IETNG approach :

There is a method of copying your profile over the initial .default release profile. This method does not require that you have a profiles.ini file nor does it require your original profile id/directory container.

- Install Thunderbird as above, skipping the wizard

- Install IETNG from the tools menu

- From the tools menu click the new IETNG menu.

- You will see an import profile option, choose that

- Give your directory information and a name for your profile

- When you restart you can choose your profile in the profile manager and make it your default profile.

- This method avoids any profiles.ini manipulation directly.

> PS I sent this twice as I havent figure how to send a .doc attachment on this mailer yet . I'll have to use another mail for this

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by cleidigh** [comment]
@Robintes 
It was not clear to me which method you ended up using??
Glad you got up easily.
You can't attach.doc in Github, you would need to zip. 

Maybe now I should go write a biased tech article  %-) 
@cleidigh

**Comment by cleidigh** [comment]
@Robintes 
Can you let me know what method you used?
I assume we can close?
@cleidigh

**Comment by Robintes** [comment]
Yes it was the first method used and it was simple. Hope its ok 4 u pls copy as you wish and give to others

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by cleidigh** [comment]
@Robintes 
Maybe you will try the built-in profile importer sometime also.
No problem sharing .
Reviews are always welcome!
@cleidigh
