### ISSUE TITLE
Backup Files Question 

### ISSUE THREAD

**Issue by amzkodi** [thundernest/import-export-tools-ng#386]
This is working great.  I am using this for email backup.  I have it set to save all files.  But these files are quit huge so I need to delete some to gain storage.  If I delete some of the older backups will it delete the actual emails or my thunderbird profile?  I assume this is totally separate from the profile backups?

**Comment by cleidigh** [comment]
@amzkodi 
The large size files in any backup will be email. I am not sure you want to go partially deleting backups. If you are doing regular backups you could delete your oldest or take it offline to a usb drive.
At some point we all have to limit how much we retain. You also must consider having a backup off your pc in case of hardware failure.
@cleidigh

**Comment by amzkodi** [comment]
I deleted all the old backups and freed up 588gb.  All emails and profiles are still there. Thanks

**Comment by cleidigh** [comment]
@amzkodi 

Excellent.
Reviews always welcome! 
@cleidigh
