### ISSUE TITLE
Usage/Import

### ISSUE THREAD

**Issue by depperm** [thundernest/import-export-tools-ng#399]
I have a .mbox attachment that I'd like to load/backup. I've installed this add on but only see it under the Add-ons Manager. I don't see any menu option, nor does the documentation indicate what the submenu should say (I don't see any submenu under Tools or View).

Is it possible to import mbox without logging into an email?

Thunderbird v 102.9.1
Import-Export Tools NG v 12.0.2

**Comment by cleidigh** [comment]
@depperm 
The menus are well described in the help, but you have to get there %-)
The main menus are context menus via right click on messages or folders.
Additionally we install under the Tools menu of the main window menu which you have to enable with Alt-V then enable the Main menu toolbar.
Currently we don't install under the "Hamburger" menu, we will in the future as the new ui settles.

I will also make the help display on install.
@cleidigh
