### ISSUE TITLE
Import-Export Failed to insatll on Dell Win 11 computer

### ISSUE THREAD

**Issue by 94gandr** [thundernest/import-export-tools-ng#400]
Attempted to install import-export-ng version 12.0.2 into Thunderbird version 102.9.1 on a Dell computer running Win 11 with all current updates installed.  The installation failed.  Can not fine the Save tool anywhere.  Looked under the ToolBar menu for a newly added tool, none found. looked in the previous place under the File menu and the Save choice is grayed out.

**Comment by cleidigh** [comment]
@94gandr 
Unless you get an error or do not see IETNG installed under The Addons page, it should be installed correctly.
See #399 for my comments on menus.
@cleidigh
