### ISSUE TITLE
Thunderbird Crashes when Exporting to CSV

### ISSUE THREAD

**Issue by marusan0303** [thundernest/import-export-tools-ng#421]
Dear Support,

I hope this email finds you well. I am writing to seek assistance regarding a problem I am facing with Thunderbird. When attempting to export data to CSV format using the ImportExportTools NG add-on, Thunderbird crashes unexpectedly.

My Thunderbird version is 102.12.0 (64-bit).

**Comment by cleidigh** [comment]
@marusan0303 
Are you exporting a search folder? This does have an issue. If this is where you are seeing I already have a beta fix.
You can get it here:
https://github.com/thundernest/import-export-tools-ng/blob/v12.0.4/xpi/beta/import-export-tools-ng-12.0.4-b2-tb.xpi

If this is not your issue please give some more detail.
@cleidigh

**Comment by cleidigh** [comment]
@marusan0303 
Any luck or feedback?
@cleidigh

**Comment by marusan0303** [comment]
@cleidigh

Thank you very much. With your help, the problem has been resolved. I apologize for the delayed response. I sincerely appreciate your assistance.

@marusan0303

**Comment by cleidigh** [comment]
@marusan0303 
Thank you for your response and I am glad your problem is resolved.
Can you just clarify for me, was it a problem exporting a search? Was using the beta the solution?
I just wanted to be sure I understand the exact problem.
Cheers
@cleidigh

**Comment by marusan0303** [comment]
@cleidigh
By using the beta version, I was able to export in CSV format.
@marusan0303

**Comment by cleidigh** [comment]
@marusan0303 
Thanks, I will close 
@cleidigh
