### ISSUE TITLE
dovecot maildir dir structure import failure

### ISSUE THREAD

**Issue by schouler** [thundernest/import-export-tools-ng#43]
**Import Export Tools NG/import all messages from a directory/also from its subdirectories**
not functioning.
succeeds importing approx 10% folder structure but NO emails (regardless of whether the emails are dovecot-no-filetype or bulk renamed .eml)
_Granted, am attempting to import 60GB of directories/sub-directories/sub-directories..._ :]

**ps**. not sure if I'm supposed to write the above here so, if not, my apologies.
pps. issue posted at: https://support.mozilla.org/questions/1273518
ppps. realise thunderbird "Maildir is disabled by default because there are still many bugs. It is not 100% ready for users"

**Comment by cleidigh** [comment]
@schouler 
Thanks for the post, sorry for the problems!
I don't have a quick answer actually I'm looking at several possibly similar issues concerning maildir imports. Two questions:
1 - Have you looked at the Debug Console (Shift-Control-J) Try and import operation then
post if any errors
2 - Have you tried a small portion of your source (including some structure)
as you recognize 60GB is an immense amount of data.  When importing Thunderbird has to do large amounts of database operations and indexing.  I cannot personally state any particular limit that is opaque to me.  I have worked with multiple people importing large amounts of e-mails , but I think the max was 10GB which I was told took quite some time.

**Comment by schouler** [comment]
Been working so apologies not replying sooner. Sleep time now so will email
tomorrow.
Briefly though, I think it's related (somehow) to GB's.
I already tried the smaller packets method and got a lot further but it
still balked at one user with 20gb of sub folders.
I'll look at the console (why I didn't think of that I don't know... :()
I'll bore you with lots of details tomorrow.
Kindness
Pils

**Comment by cleidigh** [comment]
@schouler 
No apologies, everybody (minus vampires) needs sleep!
sounds good that you were able to import with the exception of the really large set.
I have to think of some creative ways of testing really large sets.  my guess is that some of the bottlenecks would be within the core of Thunderbird.  I would probably have to do things better at staging large imports
we will catch up tomorrow
 Christopher

**Comment by schouler** [comment]
Hello Christopher
success at last.
process:


   1. Convert all dovecot maildir non-file-ending emails to .eml
   (BRU_setup_3.3.1.0.exe)
   2. Thunderbird (portable): create named folder [TopLevel] in Local
   Folders
   3. Create all 1st level sub-folders (name of person/email account)
   4. ImportExportNG (@TopLevel) each individual sub-folder
   5. For sub-folders with stupid amounts of sub-folders do same as above
   but at next level down...

6500 bleeding emails! DONE!

Oh, and I should make a confession that I did all of this on a usb stick.
*WTF?* I know, I'm sorry. Please don't shout at me. It's a long, long
story. :]

I, in my complete lack of understanding of anything technical, Ioffer up a,
possibly useless perspective, that there may be a relation between DWM
(desktop windows manager) and the UI thread. is the lack of a 'progress UI'
assisting/causing this hanging? it's supposed to be a 'background task'
isn't it. But I don't think Thunderbird treats it as such. This is all 'gut
feeling' nothing more. :]

Thank you for your (kind and understanding) responses.

happyhappyjoyjoy

Pils

**Comment by cleidigh** [comment]
I think with massive imports or exports there are just too many ways for things to thrash!
is this okay to close?
reviews are always appreciated on ATN extension site ;-)

**Comment by schouler** [comment]
yes. close. thank you.

just done shoulder in, toyping with lft hund... so a reminder to ATN in the
near future wouldn't be amiss...
