### ISSUE TITLE
Rework permissions

### ISSUE THREAD

**Issue by alexolog** [thundernest/import-export-tools-ng#430]
The extension asks for "Full, unrestricted access to Thunderbird, and your computer", this seems like an overkill.

Please use the minimum required permissions as detailed on https://support.mozilla.org/en-US/kb/permission-request-messages-thunderbird-extensions

**Comment by cleidigh** [comment]
@alexolog 
ImportExportTools NG is a privileged extension which uses what is sometimes referred to as legacy technology as compared to a pure web extension. The info popup you see is the standard Thunderbird message for these types of extensions of which there are many.

ImportExportTools requires essentially full access to both reading and writing messages into Thunderbird. Most importantly it requires File io access to be able to import and export to the users storage (only at the request of the user).

This last requirement means that until there is a file api on the web extension side, ImportExportTools will have to remain a hybrid extension with full permissions.

So no, this permission form cannot change.
Of course it's open source so one can see what it does.
@cleidigh
