### ISSUE TITLE
Addon no longer functions when I delete .xpi install file

### ISSUE THREAD

**Issue by benlundmaine** [thundernest/import-export-tools-ng#434]
Although this may simply be lack of experience with an .xpi beta, when I install (by dragging and dropping the .xpi on the addon pane), then addon will not work after I delete the .xpi file.  I have to keep the .xpi file in a folder (apparently any folder) in order for the addon to work.

Thanks for all of the work on this.

**Comment by cleidigh** [comment]
@benlundmaine 
Hmm, that's all core code. I never even knew you could dnd.
I suggest you install from file, I have never had any issues that way.
@cleidigh

**Comment by benlundmaine** [comment]
Again, perhaps a naive question, but which file? I downloaded the .xpi file.  Is there an executable file of the beta that would install?  Thanks.On Sep 7, 2023, at 8:38 PM, Christopher Leidigh ***@***.***> wrote:﻿
@benlundmaine
Hmm, that's all core code. I never even knew you could dnd.
I suggest you install from file, I have never had any issues that way.
@cleidigh

**Comment by cleidigh** [comment]
@benlundmaine 
No the xpi (which is just a zip) is the file you pick from install addon from file.
There is no executable.
@cleidigh

**Comment by benlundmaine** [comment]
I am guessing that the drag and drop approach that I used must do the same thing.  That said, I can uninstall and reinstall using your approach.On Sep 7, 2023, at 9:28 PM, Christopher Leidigh ***@***.***> wrote:﻿
@benlundmaine
No the xpi (which is just a zip) is the file you pick from install addon from file.
There is no executable.
@cleidigh

**Comment by benlundmaine** [comment]
I uninstalled and used your approach, but the result is the same.  If I delete the .xpi file, the addon no longer works--at least for the function for which I use it, which is to export an email in .html format, message only.  Thanks.

**Comment by cleidigh** [comment]
@benlundmaine 
I am all of the sudden seeing issues with exporting either html or pdf independent of deleting the xpi.
Your post implies it works as long as the xpi exists?
I don't understand why this is not working, there are many using one or the other.
I have to figure out the root cause.
@cleidigh

**Comment by cleidigh** [comment]
@benlundmaine 
Are you still having the issue?
Try b8
@cleidigh

**Comment by benlundmaine** [comment]
I'm afraid that b8 does not solve the problem.  Thanks.

**Comment by benlundmaine** [comment]
Unfortunately, after installing the latest beta, it doesn't work at all, and the version that I was previously using doesn't reverse the effect.  Addon no longer functions, period.  Thanks for the work on this.
