### ISSUE TITLE
Correct bad translations of ctxMenu_ExtensionName.title

### ISSUE THREAD

**Issue by topoldo** [thundernest/import-export-tools-ng#435]
Hi.
I have just installed ImportExportToolsNG (IET-NG) 14.0. beta7a (Italian version) and I noticed a strange thing regarding the appearance of the option "ImportExportToolsNG" in Betterbird (but I supposed also in Thunderbird) context menu.
As you can see from the image attached below, the name of the option appear as "ImportExportTools**OF**" (instead of "ImportExportTools**NG**") (see red rectangle). This doesn't happen in the case of the title of IET-NG in the "tab" of its guide (see light blue rectangle).
Is this a "mark" for the beta version(s)? N->O & G->F?
Regards,
Topoldo

![ImportExportToolsNG](https://github.com/thundernest/import-export-tools-ng/assets/9356777/edc712e5-e531-4863-9923-bcde72800501)

**Comment by cleidigh** [comment]
@topoldo 
Ha, nothing so creative as a beta mark...
it's a bad translation, I thought I fixed!
Will do in next beta, thanks.
@cleidigh

**Comment by cleidigh** [comment]
Fixed with b8
@cleidigh
