### ISSUE TITLE
Maybe a little isse - Someone confirms?

### ISSUE THREAD

**Issue by topoldo** [thundernest/import-export-tools-ng#437]
Hi all.
Until this mornig I have been using **IET-NG b7** on my Win11 64 22H2 on **Betterbird 115.2.1bb11**
Then I moved to update to **IET-NG b8** on the same platform and everyting was correct.
After that, I noticed that a new release of Betterbird, ie v.**115.2.1bb12** (no parallel to a TB new release, just due to a localisation error, so all localised versions were replaced), was out.
After BB update, as always happens when you restart TB/BB, a couple of tabs opens, in my system ie guides for IET-NG and PrintingTools-NG.
In this case, however the **IET-NG b8** opened **2 tabs** of the same type.
I don't know if this depends from the update of Betterbird or from IET-b8 one.
Anyway it is a minor bug. I'll report what happens with future updates.
It was just FYI.

Regards,
Topoldo

**Comment by cleidigh** [comment]
@topoldo 
I have to say I have no experience with BetterBird.
My guess is there were two startup events created that opened help twice. Let's see if that happens again, I think I also have to be careful with chasing things like that right now just before release.
@cleidigh
