### ISSUE TITLE
final installation on Thunderbird 115.2.3

### ISSUE THREAD

**Issue by FJMMKM** [thundernest/import-export-tools-ng#441]
b8 installed and seemed to run fine - no exhaustive testing.
b9 and tb (final?) will not install - returns incompatible with Thunderbird 115.2.3.
Note that version check has always returned only compatible with Thunderbird 102.

Thank you for your work on this project.  I am using b8 for now.

**Comment by cleidigh** [comment]
@FJMMKM 
Thanks for the status post.
I am confused by your b9 reference, I have not released anything above b8.
Were you referring to an old 102 b9?
@cleidigh

**Comment by lmtkjapan** [comment]
Hi, 
Thanks for your great work! 
Will B8 or a [coming?] update work on Thunderbird 115.3.1 (32-bit)?
(Apologies in advance for a basic question -- I am having memory issues with my computer and have to backup email asap.)
Thanks so much again for your work and time.
lmtkjapan

**Comment by cleidigh** [comment]
@lmtkjapan 
No apologies!
Yes all v14 betas are specifically for Thunderbird v115.The official v14.0.0 is actually in the review Q and I am hoping will be released in days.
B8 is quite good shape. I actually broke a couple things in v14 in my haste to release.
What method do you wish to use?
@cleidigh
