### ISSUE TITLE
Only exporting 100 emails

### ISSUE THREAD

**Issue by pquadros1** [thundernest/import-export-tools-ng#442]
On Windows 10 Pro 64bit
Thunderbird 115.2.3 (64-bit)

Trying to export over 1,000 conversations but only exports 100 (on any options eg as html, pdf, eml etc with or without index)

**Comment by cleidigh** [comment]
@pquadros1 
What beta are you using.
I did a specific fix for that in b7a.
Should work, if not then I have to follow up.
@cleidigh

**Comment by pquadros1** [comment]
I have v14.0.0-b6 installed - thanks.
Will install b7a
