### ISSUE TITLE
EML-Import funktioniert

### ISSUE THREAD

**Issue by tbusermr** [thundernest/import-export-tools-ng#443]
Hallo,

habe mit W10/TB 115.2.3/v14.0.0-b8 heute die Funktionen
- eml-Dateien importieren und
- Alle eml-Daeien aus Verzeichnis und Unterverzeichnissen importieren
verwendet (ca. 7000 Dateien importiert).

Funktionierte reibungslos, danke!
Gruß Michael

**Comment by cleidigh** [comment]
Michael
Vielen Dank für Ihre Berichterstattung!

Die EML-Funktionalität ist eine sehr wichtige Funktion, sodass Ihre Verwendung und Ihr Erfolg dazu beitragen, dass Sie bei der Veröffentlichung von Version 14 sicherer sind. Ich hoffe, dass die Veröffentlichung diese Woche erfolgt.

Prost!
Christopher

**Comment by urmel1960** [comment]
Habe heute auf Win11 mit v14.0.0-b8 eine ganze Reihe eml-files in  TB 115.3.0 importiert (aus Verzeichnissen und Unterverzeichnissen - rd. 17.000 Mails). Die eml-Files stammten aus einem Export mit emClient.

Es hat einwandfrei funktioniert und ich bin heilfroh darüber - Danke !

PS: Was ich noch feststellen konnte ist, dass nach dem Import nun eine ganze Reihe von Mails als ungelesen angezeigt werden  - knapp über 10.000 von den insgesamt rd. 17.000. Ich hatte eigentlich erwartet, dass alle als gelesen bzw als ungelesen angezeigt werden...  Aktuell versuche ich noch herauszufinden, wie man in TB eine ganze Verzeichnisstruktur als gelesen markieren kann :-) 

Beste Grüsse

**Comment by cleidigh** [comment]
Danke!
@cleidigh
