### ISSUE TITLE
Addon does not work with Thunderbird 115.2.3.

### ISSUE THREAD

**Issue by kunalbedi** [thundernest/import-export-tools-ng#444]
Dear Christopher,

First of all many thanks and kudos for the excellent plugin you have developed. It is second nature to use its various features for my use case and I thank you for it.

I need to report that the plugin does not work with latest Thunderbird 115.2.3.

I would like to know if you are working on getting it to work on latest version of Thunderbird 115.2.3.

Thanks
Kunal Bedi

![2023-09-27_14-41-24](https://github.com/thundernest/import-export-tools-ng/assets/6187230/6fac6c8c-1ae9-42dd-8ae1-519a86845516)

**Comment by cleidigh** [comment]
@kunalbedi 
I have actually just released the new Version v14.0.0 to support Thunderbird v115
You can download the last beta now here until the official release comes out this week.
https://github.com/thundernest/import-export-tools-ng/issues/408

@cleidigh

**Comment by kunalbedi** [comment]
Thanks @cleidigh 

Great that you answered so soon. I was able to download the b8 beta after several attempts. (FF failed but Chrome was able to download. Github glitch probably!)

I can confirm that for my functionality of add-on able to export folder messages as EML is WORKING. I am on Thunderbird 115.2.3.

Thanks for the good work.

Regards
@kunalbedi

**Comment by cleidigh** [comment]
@kunalbedi 
Excellent!
Thanks for your report and support!

@cleidigh
