### ISSUE TITLE
German Translation Error

### ISSUE THREAD

**Issue by acbugreport** [thundernest/import-export-tools-ng#447]
Version: 14.0.0.b8

Bug:
The translation used for "Header" in the copy to clipboard menu item is "Überschrift". That would be the heading.

Correction:
The appropriate term in the context of emails is "Kopfzeile".

**Comment by cleidigh** [comment]
@acbugreport 
Thanks!
@Mr-Update did a full de locale update which I will have in the first maintenance release.
I will make sure this is considered.
@cleidigh

**Comment by cleidigh** [comment]
Done
