### ISSUE TITLE
Export Dialog Box does not open

### ISSUE THREAD

**Issue by jjacob9105** [thundernest/import-export-tools-ng#457]
I'm on Thunderbird 115.3.1.  When I try to export a message in EML format, the folder dialog box does not open.  (None of the others do either.)

**Comment by cleidigh** [comment]
@jjacob9105 
Questions 
- what OS
- do you have export directories enabled
- can you capture the error console 

@cleidigh

**Comment by jjacob9105** [comment]
Windows 11

I have not changed my settings regarding export directories.

I went into troubleshooting mode and then back out.  Now the dialog box opens.  Go figure...

Thanks for responding.

**Comment by cleidigh** [comment]
@jjacob9105 
That is very odd and I have never heard a similar report...
But you are good to go now, yes?
Ok to close?
@cleidigh

**Comment by jjacob9105** [comment]
Good to go.  I'll let you know if it happens again and I can't figure out how to fix it.  Thanks again for a great add-on.

**Comment by cleidigh** [comment]
@jjacob9105 
Thank you mucho 👍 
@cleidigh
