### ISSUE TITLE
Context menu selection not honored

### ISSUE THREAD

**Issue by mforkel** [thundernest/import-export-tools-ng#475]
I'm using version 14.0.0 of the extension with Thunderbird 115.3.2.

If I open a context menu (right mouse click) for a message in the inbox pane and select a command from import-export-tools-ng's submenu, that command will be executed for a previously selected message (left mouse click) in that pane or is a no-op if no selection exists.

Other commands in the regular context menu operate on the message the context menu was opened for. So did import-export-tools-ng's context menu commands in previous versions.

My use case is copying the text of a suspicious message to the clipboard without having to open it in the message pane. Currently, this does not seems possible.

**Comment by cleidigh** [comment]
@mforkel 
Thanks for the post.
I have a first beta for v14.0.1 which address  this among other things.
It also gives a warning if more than one message is selected.
You can track and download here : 
- #466 

Let me know in case I have missed anything.
@cleidigh

**Comment by mforkel** [comment]
I just tested v14.0.1 b2 and can confirm that it solves the issue. Thanks!
