### ISSUE TITLE
Update Danish translation

### ISSUE THREAD

**Issue by Joergen** [thundernest/import-export-tools-ng#478]
I have been looking at the latest version of ImportExportTools NG. It looks like there has been added some new machine translated strings.
I have updated the Danish translation and corrected some of my old mistakes. 
How can I add the changed Danish files to this project without having to fork and clone the project?

**Comment by cleidigh** [comment]
@Joergen 
Thanks for posting!
Of course I absolutely welcome native, non robot locale help and contributions.
Yes using the Google API has its limits, however, I could never support 21 locales without it.

It would be great to improve the Danish locale.
If you are not up to doing a github pull request then you can download and modify the current files and zip and post here, I will merge.
First thing is to check with me to make sure we won't collide on anything.
Then the files: 
- I am working on the v14.0.1 branch now
- Danish files are in three places 
- src/_locales/da
- src/chrome/locale/da/mboximport
- src/chrome/content/mboximport/help/locale/da

I would suggest doing one file and checking with me just to make sure you have the process down

@cleidigh

**Comment by Joergen** [comment]
Ok.
I will first upload the messages.json file zipped as da-messages.json.zip to https://github.com/thundernest/import-export-tools-ng/tree/v14.0.1

**Comment by cleidigh** [comment]
@Joergen 
You actually post the zip right in this thread.
@cleidigh

**Comment by Joergen** [comment]
[da-messages.json.zip](https://github.com/thundernest/import-export-tools-ng/files/13061888/da-messages.json.zip)

**Comment by Joergen** [comment]
Hi @cleidigh 
Here are the remaining updated Danish files:
[da-importexport-help.html.zip](https://github.com/thundernest/import-export-tools-ng/files/13064533/da-importexport-help.html.zip)
[da-mboximport.zip](https://github.com/thundernest/import-export-tools-ng/files/13064534/da-mboximport.zip)

**Comment by cleidigh** [comment]
@Joergen 
Everything looks good, thank you very much!
Brings back memories from my couple of trips to Denmark.

I merged into b3 which I just posted.
@cleidigh

**Comment by Joergen** [comment]
@cleidigh 
Thanks.
