### ISSUE TITLE
File name format for export to PDF

### ISSUE THREAD

**Issue by marceepoonu** [thundernest/import-export-tools-ng#53]
I downloaded it a few minutes ago from https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/
and I installed it to a Thunderbird ver. 60 installation.
Is there any option to control the file naming format for exports to PDF?
If I posed this question inappropriately in some way, please let me know what I did that was inappropriate, so that I don't do it again.
           Marc

**Comment by cleidigh** [comment]
@marceepoonu 
slow response, sorry!
Yes, under the extension options (Tools/Add-on Options Menu)  there are many configuration options including forename conventions:
![image](https://user-images.githubusercontent.com/25272315/71423550-35371000-2658-11ea-8949-a192a502d93c.png)

I am hoping to find some time to get minimal user manual for these types of questions.
Thanks, let me know if this answers your question to close.
Christopher
