### ISSUE TITLE
Mbox import dialog cancel button ignored

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [thundernest/import-export-tools-ng#56]
Hi there,

So I right click on a folder to test this new version, I click on import/export import, then Mbox file.

I click on cancel & it doesn't cancel, it brings up the Explorer window to find the file I was supposed to import.

Thanks

**Comment by cleidigh** [comment]
@CleanSoftwareIsKey 
Thanks for the issue post.
I reproduced your issue, I am pretty certain it's a change in the dialogue handler.

Currently I will be doing a new Release shortly because of another bug.  I will address this at the same time.

@cleidigh

**Comment by ILoveSkilledCoders** [comment]
> @CleanSoftwareIsKey
> Thanks for the issue post.
> I reproduced your issue, I am pretty certain it's a change in the dialogue handler.
> 
> Currently I will be doing a new Release shortly because of another bug. I will address this at the same time.
> 
> @cleidigh

Not to confuse you b/c I confused myself LOL, I changed my UN.

Great, glad you were able to replicate it.

Does it update automatically on TB?

I just upgraded (finally) to the latest version of TB so I was really nervous this add-on was no longer going to be available.

Thanks for helping with that.

**Comment by cleidigh** [comment]
@ILoveSkilledCoders 
If you are the "Release" channel for extensions it will upgrade automatically (default)
I fixed it last night.  Look out for 4.0.5
Cheers

**Comment by cleidigh** [comment]
Fixed: #56

**Comment by ILoveSkilledCoders** [comment]
Thank you

Be well
