### ISSUE TITLE
createSubFolder throws error after large number of operations

### ISSUE THREAD

**Issue by cleidigh** [thundernest/import-export-tools-ng#57]
For any operations involving the creation of message subfolders (import EML, etc)
Thunderbird will throw unknown error after successive createSubFolder. 
Usually this occurs around 470+ operations.  It can happen earlier.

Testing shows that JavaScript scheduler yields do not fix the problem.
Using folder creation promises / async/await a with a database update
currently looks promising.

This issue is related to:
#42 
#50 
@buggyboy
@cameronjpu 
@braian87b 
@nvanderperren 

Working towards a beta
@cleidigh

**Comment by braian87b** [comment]
Do you have working code? can you submit a push request?

**Comment by cleidigh** [comment]
@braian87b 
Not yet , I think I fixed the folder issue, I get similar issues with messages.  Banging away at that now.  I will flag here soon as I have beta.  Testing help will be great!

**Comment by braian87b** [comment]
Cool, I have around 70gb of around 300.000 emails to test.

**Comment by cleidigh** [comment]
All - update:
Happy New Year's!
Still struggling with some errors.  Hoping for some after holiday help ;-)
Nothing worth to test yet...

**Comment by braian87b** [comment]
@cleidigh Happy New Year for you too!, Thanks, let me know when we can try again, thanks.

**Comment by cleidigh** [comment]
All
. Working through the holiday, unfortunately still getting unknown errors.
I am going to try to a different approach suggested to Me, will continue to report on progress

**Comment by braian87b** [comment]
Thanks @cleidigh ! user is currently on holiday so no problem with their emails... I will suggest him to give a try with to see the Apple Mail issue with some apple support guy.

**Comment by cleidigh** [comment]
All
I have not disappeared, working hard to figure this out still.
Christopher

**Comment by braian87b** [comment]
@cleidigh thanks!

**Comment by cleidigh** [comment]
@buggyboy
@cameronjpu 
@braian87b 
@nvanderperren 


All
I appreciate your patience on this.  I am basically having to rewrite core parts of the extension to deal with higher volume transactions.  I believe I have a worthwhile step testing.  It is a pseudo- import test that creates subfolders and populates family with a set of messages.  The messages are actually internal test messages.  To make this flexible I added a new panel tab for test options.  
You can configure test cycles and the folder and message counts as well as individual message size.
You will see a status bar and can also see the times and the debug console.  I was able to do a 2GB 
pseudo- import in ~7.5min  , but I do have a very fast PC and this does not include read files, just the folder creation and  addMessage.  I would expect maybe an additional forty percent time increase once I had the read.  I am not concentrating on performance now I just have to get it to work reliably and then optimize.

If anyone can do some experiments it would be great.  I added two test items to the folder menu:
CreateFolders..
Test2
only the first works right now but it will kick off a pseudo- import based on  on your options.

CreateFolders test2 
Code: same as test1 return before delete (one cycle for size test)
100Mb total in 100 folders/100messages per folder


StartTime: 2020-01-22T22:56:29.108Z mboximport.js:1078:10
CreateFolders Test1 - Start Cycles: 1 Folders: 100 MsgPerFolder: 100 MsgSize: 10000 mboximport.js:1691:10
Time: 2020-01-22T22:56:29.109Z mboximport.js:1700:11
Cycle: 1 Time End: 48.329 mboximport.js:1773:11


2Gb 500 folders 200/folder
StartTime: 2020-01-22T23:06:23.142Z mboximport.js:1078:10
CreateFolders Test1 - Start Cycles: 1 Folders: 500 MsgPerFolder: 200 MsgSize: 10000 mboximport.js:1691:10
Time: 2020-01-22T23:06:23.143Z mboximport.js:1700:11
Cycle: 1 Time End: 438.767 mboximport.js:1773:11 ~3.6min/Gb

![image](https://user-images.githubusercontent.com/25272315/73033891-6f3f3180-3e11-11ea-9351-4bcf84023300.png)

**Comment by danielehrhardt** [comment]
Something new here?

**Comment by danielehrhardt** [comment]
![image](https://user-images.githubusercontent.com/19570043/75271526-9ddb6e00-57fc-11ea-9c28-234ba46cb308.png)

**Comment by cleidigh** [comment]
@danielehrhardt 
I am still working on this, it is not consistent and very difficult solution.  That the problem usually occurs with large imports well into the process.  Can you give the versions/OS info?
Also any relevant details on what you are trying to import.  Anything helps!
sorry for the issue.
@cleidigh

**Comment by cleidigh** [comment]
@danielehrhardt  - I finally have something new!
@buggyboy
@cameronjpu 
@braian87b 
@nvanderperren 

I know it's been way too long.  I believe five finally have something worth testing and would be great to get some confirmation from some of you if possible.
I have been doing tasks with ~40000 messages within 1000-2000 folders
around 2.5GB repeated imports.
here's the pointer:
https://github.com/thundernest/import-export-tools-ng/blob/import-4.1.1-test/xpi/import-export-tools-ng-4.1.1-test1-tb.xpi

Feedback really appreciated , especially all of your patience!!
@cleidigh

**Comment by cleidigh** [comment]
Finally identified the root cause.  I have a test extension
https://github.com/cleidigh/iet-tests/blob/master/xpi/iet-ng-tests-0.1.14-tb.xpi
third menu option (experimental)  contains this and other fixes.
@cleidigh

**Comment by cleidigh** [comment]
Issue is related to the number of open files. Windows allows 500
we have to force a database classed after about 400 createFolder operations
similar issues with addMessage

Fix:
```
			if (folderCount++ % 400 === 0) {
				rootFolder.ForceDBClosed();
			}
```

**Comment by cleidigh** [comment]
Fixed
v10.0.0
