### ISSUE TITLE
McAfee detected virus

### ISSUE THREAD

**Issue by RiKoMar** [thundernest/import-export-tools-ng#60]
Many thanks for this great tool - still having issues, but I scan GitHub for reasons first.

This issue: I have installed this addon by donwloading the addon from homepage and pulling teh file  into 'AddOns' of TB. McAfee detected virus and isolated it.

![McAfee Virus](https://user-images.githubusercontent.com/59361517/71579851-a23a2200-2afe-11ea-982d-5bdd89ac4ae6.jpg)

Homepage:
https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/

On a second PC, I have added the addon by using TB-AddOn tab - no virus detected.
I then uninstalled there and re-installed by the file above - Virus detected.

Dont know if any important.

Kind regards, RiKoMar

**Comment by cleidigh** [comment]
@RiKoMar 
Thanks for the issue post, happy new year!
While I do not use McAfee I imagine this is actually standard when downloading through the browser.  The scanner is detecting the content of the compressed xpi (same as zip) which includes JavaScript obviously.  When you download through Thunderbird the scanner is either out of the loop or does not flag it.  Either way the scanner is giving you an appropriate warning for that file type.
I assume with your current settings it would flag any similar file/extension.

Please let me know if this matches the situation, if so I think we can close.
Christopher

**Comment by RiKoMar** [comment]
Hi Christopher,
many thanks for your prompt reply. I understand your view. Apparently, McAfee did deactiate certain part of the downloaded code and the add-on did apparently work w/o this blocked code (sorry for my simple words, I am not a proffessional and English is not my mother language...). Anyway, you are sure your site and download code is clean and that is most important. For me, the case can be closed. As this is my first entry in GitHub, I try the button <Close and comment> to close by myselfe...
Kind regards - RiKoMar
