### ISSUE TITLE
Error when exporting to Plain Text with attachments and with HTML index

### ISSUE THREAD

**Issue by boesiii** [thundernest/import-export-tools-ng#63]
I am exporting a bunch of emails using version 4.0.4 and when it gets to some emails it gives me and error message.  `Warning: Unresponsive script a script on this page may be busy or ... Script: chrome://mboximport/content/exportTools.js:1105`

When this happens it locks up Thunderbird and I have to stop it using Task Manager.  I am using Windows 10.

**Comment by boesiii** [comment]
How do I find exportTools.js so I can look at line number 1105?

**Comment by boesiii** [comment]
If I export to plain text with html index but WITHOUT attachments then the tool works successfully.  I am trying to narrow down the attachment giving me problems but haven't found it yet.

**Comment by boesiii** [comment]
To workaround the problem, I had to look at the attachments last downloaded during the initial export and then find the corresponding email and move the email to another folder so it wouldn't be downloaded.

**Comment by cleidigh** [comment]
@boesiii 
Thanks for the post, sorry for the issue - and happy new year!
My initial guess based on your latest comments is that there is a attachment content issue 
in one of your attachments specifically the one you identified.  There is manipulation by the extension
that could be the issue or something new extension does not know how to handle.
Separately, I am working on several new issues concerning large-scale operations.  It's not clear whether these are the same on all platforms.  
Did you capture the Debug log?  
@cleidigh

**Comment by cleidigh** [comment]
@boesiii 
You can always look to source code here in the repository:
https://github.com/thundernest/import-export-tools-ng/blob/master/src/chrome/content/mboximport/exportTools.js

**Comment by cleidigh** [comment]
Fixed
v10.0.0
