### ISSUE TITLE
Add Ability To Add Suffix to File Name

### ISSUE THREAD

**Issue by JF1313** [thundernest/import-export-tools-ng#67]
This is a wonderful extension for Thunderbird and provides additional functionality that is needed and important.

It would be great if there was the ability to add a suffix at the end of a file name. Currently, the extension allows you to add a prefix. While this is a nice feature, it will get in the way of sorting by date. 

Having either a suffix or having the prefix AFTER the date would solve this issue.

Keep up the wonderful work.

**Comment by cleidigh** [comment]
@JF1313 
@artofit
I am thinking the right way to approach this is with both a configurable date specification (I do the same my other extension message archive options)  Also use configurable placeholders for things like  both prefix and suffix .  When I get a little farther the problems, I will post a possible solution so people can comment.

**Comment by JF1313** [comment]
thank you Christopher for the follow-up. Looking forward to what you might be able to find.

On another note, I believe I saw a thread in which you were talking about the ability to change the email subject for emails that are received. This would be a much needed extension of Thunderbird and something that is greatly missed in the latest version. 

Jeffrey 

Quote:

Never, never, never, never, never, in nothing great or small, large or petty, never give in, except to convictions of honour and good sense.  Never yield to force; never yield to the apparently overwhelming might of the enemy. -- Winston Churchill

-----Original Message-----

**Comment by cleidigh** [comment]
@JF1313 
@artofit

I have rolled this into a single issue #75 which captures other related requests.
Check out the mockup , feedback before I roll would be great.
I think the fully customizable file name 'will allow you to do all sorts of things!
@cleidigh

**Comment by cleidigh** [comment]
Added:
4.1.0
