### ISSUE TITLE
Index.html attachment flag always blank for e-mails with attachments

### ISSUE THREAD

**Issue by kanlukasz** [thundernest/import-export-tools-ng#68]
Hello

I used export with `Exporting all messages in EML` option.
This operation created an index listing all messages. This is OK

BUT - In the "Attachment" column, messages with attachments should be marked with an asterix "*", unfortunately **they have not been marked**

Column "Attachment" is **empty**, but attachments **exist**

#### TB Version:
![obraz](https://user-images.githubusercontent.com/30685349/71886555-b6080880-313c-11ea-834e-7f145712d694.png)

#### OS:
![obraz](https://user-images.githubusercontent.com/30685349/71886577-c15b3400-313c-11ea-802a-bba3a3d8a129.png)

#### Addon version:
![obraz](https://user-images.githubusercontent.com/30685349/71886614-d33cd700-313c-11ea-9aab-71b1e68699c6.png)

**Comment by cleidigh** [comment]
@kanlukasz 
Thanks for the post and happy new year!
This is the first report of this type as far as I am aware.  I don't have any history on the original extension.
Did you see a change in behavior for NG with a particular Thunderbird version/OS platform?
@cleidigh

**Comment by kanlukasz** [comment]
Thank you for your reply and I wish you a happy new year too
I can only make tests on my computer. I have only Windows10
I can tell you that when I used the [original addon version](https://addons.thunderbird.net/pl/thunderbird/addon/importexporttools/) with previous TB everything was ok

**Comment by cleidigh** [comment]
@kanlukasz 
Attachment flag must have changed.  I now check for both integer or string.
```

		var hasAtt;
		// attachment flag may have changed from integer to string
		if (hdrs[6] === 1 || hdrs[6] === '1')
			hasAtt = "*";
		else
			hasAtt = "&nbsp;";
```

I just posted this fix in v4.0.5-b2 if you would like to test/use .
https://github.com/thundernest/import-export-tools-ng/blob/import-tests/xpi/import-export-tools-ng-4.0.5-b2-tb.xpi

@cleidigh

**Comment by kanlukasz** [comment]
I tested and I can confirm that this fix works OK 👍

![obraz](https://user-images.githubusercontent.com/30685349/72218607-e4228980-353c-11ea-97b4-230a2d3d5512.png)

**Comment by cleidigh** [comment]
@kanlukasz 
Excellent.  I wish all issues were as easy to solve :-(
I will keep this open until I do the actual next version.

**Comment by spd2000** [comment]
Hi -- Thanks for this great add-on. I'm actually encountering the same issue of no flag being set in the Attachment column when an attachment is present (when using "Export all messages in folder" / "HTML format with attachments").

Thunderbird: 68.4.2 (32-bit)
ImportExportTools NG  release, 4.0.0
Windows 10 Home - 1903 -- OS Build 18362.592

**Comment by cleidigh** [comment]
@spd2000 
If you look several posts above you'll see a pointer for a beta that fixes this.  I am currently battling a big issue that I want to solve before releasing another version.  Hopefully you can deal with the Beta for a bit.
Cheers
Christopher

**Comment by cleidigh** [comment]
@spd2000 
@kanlukasz 
Added:
4.1.0
