### ISSUE TITLE
CSV export - body only in HTML since NG

### ISSUE THREAD

**Issue by 7ohm7** [thundernest/import-export-tools-ng#69]
Dear Christopher,

I use your add-on and I really appreciate it. I mainly export messages to csv, load them in Excel and manage responses. Since the NG version, however, the CSV export has changed - the body of the message was originally normal raw text, now it is already in HTML and I can't find the add-on setting to change output back in raw text.

ImportExportTools:
![old](https://user-images.githubusercontent.com/46259543/72087287-7d1c8f00-3308-11ea-9ab0-e98bc496bea4.png)

ImportExportTools NG:
![ng](https://user-images.githubusercontent.com/46259543/72087302-83127000-3308-11ea-863e-52a61dcc36fa.png)

Unfortunately, with this setting, CSV export is unusable for me because it forces every program that loads these CSVs to have function to convert from HTML. Is this an intention? Will you return the option to export to CSV so that the body of the message is raw text? Thank you.

Marek

**Comment by cleidigh** [comment]
@7ohm7 
Thanks for the post, happy new year!
Fortunately this is a duplicate of #23 .  The encoding API changed on me.  I already have the fix in the
4.0.5-b1
See the repository link near the end:  Let me know if this addresses your problem, I'm trying to get several other bugs fixed before releasing as there is always a review delay.
https://github.com/thundernest/import-export-tools-ng/issues/23
@cleidigh

**Comment by 7ohm7** [comment]
Happy New Year to you too!
I apologize for not noticing the older topic
But, excellent, it fits completely and solved the problem. You have exemplary support, everything fast and accurate :) Thank you very much.

Marek
