### ISSUE TITLE
 HTML Export with Attachments - Inline Images not exported

### ISSUE THREAD

**Issue by jessejmorrow** [thundernest/import-export-tools-ng#74]
Hi,

I love this tool and use the HTML Export with Attachments daily to do local storage of emails related to various projects. You had previously helped me with a bug fix and special feature of storing the HTML attachments is date-time stamp folders, instead of the default Attachment-1, -2, etc.

The issue I'm having right now is with inline images. If a person sends their images as an attachment, all is good and these get saved in the export. But if the images are in the body of the email, the images doesn't get saved, which is a problem as that generally means you are losing the most important part of the email.

Is this a bug? Or is this a new feature request?

ML, Jesse

**Comment by cleidigh** [comment]
@jessejmorrow 
happy New Year's, good to hear from you!
you may remember that I have none of the history on the original extension.  I will look into this but if you have experience with this in the original extension it would be great to know.
Explicitly is this something you have successfully done before?
@cleidigh

**Comment by jessejmorrow** [comment]
Thank! And Happy New Year to you.

I actually don't know if the original did it or not as I didn't 
encounter it so much as a need.

It certainly seems like something it SHOULD do. But I don' t know about 
the original feature set or intention.

ML,

Jesse

**Comment by cleidigh** [comment]
@jessejmorrow 
I just did a couple comparison test.  
E-mail 1: text, in line image, text
E-mail 2: text, , text (attached image)

I copied both e-mails to a local folder and exported.  I am attaching this file for you to see.
The extension puts in-line images into a subfolder(s) "EmbeddedImages-x"
For the second to e-mail and attachments directory is created with the file.
Viewing under a browser displays the images in either case.
As I stated above, I could probably use an example problematic e-mail from you as there are several methods to include in-line images.  Since I am exporting from Thunderbird  with email created by Thunderbird we may not be taking another message into account.  Additionally the online images could just be base64 in the HTML however the original extension and current not choose this method.

[ImageExportTest_20200207-1625.zip](https://github.com/thundernest/import-export-tools-ng/files/4173037/ImageExportTest_20200207-1625.zip)

**Comment by waerlogauk** [comment]
As I am seeing the same issue I have taken the liberty of sending you a sample email that for me fails to export the image. The exported Html seems to be attempting to reference the image on the server

**Comment by cleidigh** [comment]
@waerlogauk 
Thanks, examples are exactly what we need.  I exported to HTML (with attachments) and the result was below.  Also the image was saved into subdirectory which you see referenced in the HTML.
I guess we have to figure out if there is a process or option difference that is doing things differently for us.  Can you post to the HTML output that is in error?

```HTML

  | <html>
-- | --
  | <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  | <title>Fwd: small inline test image</title>
  | <link rel="important stylesheet" href="">
  | <style>div.headerdisplayname {font-weight:bold;}
  | </style></head>
  | <body>
  | <table border=0 cellspacing=0 cellpadding=0 width="100%" class="header-part1"><tr><td><b>Subject: </b>Fwd: small inline test image</td></tr><tr><td><b>From: </b>&quot;G.Rixon&quot; &lt;gargith@gar.waerloga.co.uk&gt;</td></tr><tr><td><b>Date: </b>2/9/2020, 7:55 AM</td></tr></table><table border=0 cellspacing=0 cellpadding=0 width="100%" class="header-part2"><tr><td><b>To: </b>test1@kokkini.net</td></tr></table><br>
  | <html>
  | <head>
  |  
  | <meta http-equiv="content-type" content="text/html; ">
  | </head>
  | <body>
  | <p>test message to show failure to export image<br>
  | </p>
  | <div class="moz-forward-container">first text
  | <p><img src="EmbeddedImages-1/0.jpg" alt="my
  | alternate text" class=""></p>
  | <p>more text<br>
  | </p>
  | </div>
  | </body>
  | </html>
  |  
  | </body>
  | </html>
  |  

```

**Comment by cleidigh** [comment]
@jessejmorrow 
@waerlogauk 
I just thought of an obvious question:

Are you both expecting that an in-line image exist within the HTML message as embedded base64?
The extension has always stored the images in-line or attached in subdirectories separate files.  
@cleidigh

**Comment by waerlogauk** [comment]
I see rather different Html:
(some parts of server access replaced with *)

[20200209-small test image-1954.pdf](https://github.com/thundernest/import-export-tools-ng/files/4180470/20200209-small.test.image-1954.pdf)

side question how did you insert your html sample?

**Comment by cleidigh** [comment]
@waerlogauk 
okay clearly we've got something going on here differently.  I have to think of some ways to copy this
behavior. 
I have one question off the top of my head:
Specifically what steps did you take to add the image also where did the image come from?

Re: the code formatting, it is a GH markdown ability:
Basically you start and then the code block with triple backticks followed by  language keyword
You can also use a single one for codewords

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by waerlogauk** [comment]
Another test
1: copy-pasted from another email
2: file dragged & dropped inline
3: attached (the attached one worked fine)
 gives

```html
<html><head>

    <meta http-equiv="content-type" content="text/html; ">
  </head>
  <body><div class="moz-text-html" lang="x-unicode">
    <p>Three images</p>
    <p>1: copy pasted from another email</p>
    <p><img src="imap://*******************.co.uk:993/fetch%3EUID%3E.INBOX*****?part=1.1.2.2&filename=ifoobchpcpknbdgk.jpg" alt=""></p>
    <p>2: file dragged &amp; dropped inline</p>
    <p><img src="imap://*******************.co.uk:993/fetch%3EUID%3E.INBOX******?part=1.1.2.3&filename=indgokfhgefjaaem.jpg" alt=""></p>
    <p>3: as attachment</p>
    <p>Kim<br>
    </p>

</div><br><hr><br><div style="font-size:12px;color:black;"><img src="data:image/gif;base64,R0lGODdhDwAPAOMAAP///zEwYmJlzQAAAPr6+vv7+/7+/vb29pyZ//39/YOBg////////////////////ywAAAAADwAPAAAESRDISUG4lQYr+s5bIEwDUWictA2GdBjhaAGDrKZzjYq3PgUw2co24+VGLYAAAesRLQklxoeiUDUI0qSj6EoH4Iuoq6B0PQJyJQIAOw==">
<ul><li><a href="Attachments-1/folder.jpg">Attachments-1/folder.jpg</li></a></ul></div><div class='' ></div></body></html>
'''

**Comment by cleidigh** [comment]
I don't get it, we still get different results...
I have to think of something to debug output I can add to a beta

**Comment by cleidigh** [comment]
@jessejmorrow 
@waerlogauk 
a little bit of progress...
 
I just uploaded a beta that includes debug output that I think will get to the heart of the matter.
Also I realized that we have not established OS, Thunderbird/IETng versions.
@waerlogauk I just saw your output the image source as imap, I think that means you are using 60.x?

Below I have my debug output, I have redacted nothing.  If either of you could check b10 , export the e-mail with in-line images and copy the debug output here that would be great, I think it's in the parsing of the source attribute.  There were some changes in Thunderbird regarding this recently.

```

attachment name folder.jpg exportTools.js:1084:17
save embedded images exportTools.js:1207:14
<html>

<head>

<title>more image tests</title>

<link rel="important stylesheet" href="chrome://messagebody/skin/messageBody.css">

</head>

<body>

<table border=0 cellspacing=0 cellpadding=0 width="100%" class="header-part1"><tr><td><div class="headerdisplayname" style="display:inline;">Subject: </div>more image tests</td></tr><tr><td><div class="headerdisplayname" style="display:inline;">From: </div>&quot;G.Rixon&quot; &lt;gargith@gar.waerloga.co.uk&gt;</td></tr><tr><td><div class="headerdisplayname" style="display:inline;">Date: </div>2/11/2020, 6:25 AM</td></tr></table><table border=0 cellspacing=0 cellpadding=0 width="100%" class="header-part2"><tr><td><div class="headerdisplayname" style="display:inline;">To: </div>test1@kokkini.net</td></tr></table><br>

<html><head>

    <meta http-equiv="content-type" content="text/html; ">
  </head>
  <body><div class="moz-text-html" lang="x-unicode">
    <p>Three images</p>
    <p>1: copy pasted from another email</p>
    <p><img src="mailbox:///C:/Dev/Thunderbird/Profiles/Test68-x/Mail/secure33.webhostinghub.com/Inbox?number=12&header=header=filter&part=1.1.2.2&filename=ifoobchpcpknbdgk.jpg" alt=""></p>
    <p>2: file dragged &amp; dropped inline</p>
    <p><img src="mailbox:///C:/Dev/Thunderbird/Profiles/Test68-x/Mail/secure33.webhostinghub.com/Inbox?number=12&header=header=filter&part=1.1.2.3&filename=indgokfhgefjaaem.jpg" alt=""></p>
    <p>3: as attachment</p>
    <p>Kim<br>
    </p>
  


</div><br><hr><br><div style="font-size:12px;color:black;"><img src="data:image/gif;base64,R0lGODdhDwAPAOMAAP///zEwYmJlzQAAAPr6+vv7+/7+/vb29pyZ//39/YOBg////////////////////ywAAAAADwAPAAAESRDISUG4lQYr+s5bIEwDUWictA2GdBjhaAGDrKZzjYq3PgUw2co24+VGLYAAAesRLQklxoeiUDUI0qSj6EoH4Iuoq6B0PQJyJQIAOw==">

<ul><li><a href="Attachments-5/folder.jpg">Attachments-5/folder.jpg</li></a></ul></div><div class='' ></div></body></html> exportTools.js:1208:14
search mailbox exportTools.js:1219:16
# embedded 2 exportTools.js:1221:16
get URL 0  <img src="mailbox:///C:/Dev/Thunderbird/Profiles/Test68-x/Mail/secure33.webhostinghub.com/Inbox?number=12&header=header=filter&part=1.1.2.2&filename=ifoobchpcpknbdgk.jpg" alt=""> exportTools.js:1235:16
mailbox URL 0  mailbox:///C:/Dev/Thunderbird/Profiles/Test68-x/Mail/secure33.webhostinghub.com/Inbox?number=12&header=header=filter&part=1.1.2.2&filename=ifoobchpcpknbdgk.jpg exportTools.js:1239:17
Save embedded as: C:\Dev\Test\ExportImagesTest\EmbeddedImages-7\0.jpg exportTools.js:1247:16
Data after img source substitution exportTools.js:1251:16
<html>

<head>

<title>more image tests</title>

<link rel="important stylesheet" href="chrome://messagebody/skin/messageBody.css">

</head>

<body>

<table border=0 cellspacing=0 cellpadding=0 width="100%" class="header-part1"><tr><td><div class="headerdisplayname" style="display:inline;">Subject: </div>more image tests</td></tr><tr><td><div class="headerdisplayname" style="display:inline;">From: </div>&quot;G.Rixon&quot; &lt;gargith@gar.waerloga.co.uk&gt;</td></tr><tr><td><div class="headerdisplayname" style="display:inline;">Date: </div>2/11/2020, 6:25 AM</td></tr></table><table border=0 cellspacing=0 cellpadding=0 width="100%" class="header-part2"><tr><td><div class="headerdisplayname" style="display:inline;">To: </div>test1@kokkini.net</td></tr></table><br>

<html><head>

    <meta http-equiv="content-type" content="text/html; ">
  </head>
  <body><div class="moz-text-html" lang="x-unicode">
    <p>Three images</p>
    <p>1: copy pasted from another email</p>
    <p><img src="EmbeddedImages-7/0.jpg" alt=""></p>
    <p>2: file dragged &amp; dropped inline</p>
    <p><img src="mailbox:///C:/Dev/Thunderbird/Profiles/Test68-x/Mail/secure33.webhostinghub.com/Inbox?number=12&header=header=filter&part=1.1.2.3&filename=indgokfhgefjaaem.jpg" alt=""></p>
    <p>3: as attachment</p>
    <p>Kim<br>
    </p>
  


</div><br><hr><br><div style="font-size:12px;color:black;"><img src="data:image/gif;base64,R0lGODdhDwAPAOMAAP///zEwYmJlzQAAAPr6+vv7+/7+/vb29pyZ//39/YOBg////////////////////ywAAAAADwAPAAAESRDISUG4lQYr+s5bIEwDUWictA2GdBjhaAGDrKZzjYq3PgUw2co24+VGLYAAAesRLQklxoeiUDUI0qSj6EoH4Iuoq6B0PQJyJQIAOw==">

<ul><li><a href="Attachments-5/folder.jpg">Attachments-5/folder.jpg</li></a></ul></div><div class='' ></div></body></html> exportTools.js:1252:16
get URL 1  <img src="mailbox:///C:/Dev/Thunderbird/Profiles/Test68-x/Mail/secure33.webhostinghub.com/Inbox?number=12&header=header=filter&part=1.1.2.3&filename=indgokfhgefjaaem.jpg" alt=""> exportTools.js:1235:16
mailbox URL 1  mailbox:///C:/Dev/Thunderbird/Profiles/Test68-x/Mail/secure33.webhostinghub.com/Inbox?number=12&header=header=filter&part=1.1.2.3&filename=indgokfhgefjaaem.jpg exportTools.js:1239:17
Save embedded as: C:\Dev\Test\ExportImagesTest\EmbeddedImages-7\1.jpg exportTools.js:1247:16
Data after img source substitution exportTools.js:1251:16
<html>

<head>

<title>more image tests</title>

<link rel="important stylesheet" href="chrome://messagebody/skin/messageBody.css">

</head>

<body>

<table border=0 cellspacing=0 cellpadding=0 width="100%" class="header-part1"><tr><td><div class="headerdisplayname" style="display:inline;">Subject: </div>more image tests</td></tr><tr><td><div class="headerdisplayname" style="display:inline;">From: </div>&quot;G.Rixon&quot; &lt;gargith@gar.waerloga.co.uk&gt;</td></tr><tr><td><div class="headerdisplayname" style="display:inline;">Date: </div>2/11/2020, 6:25 AM</td></tr></table><table border=0 cellspacing=0 cellpadding=0 width="100%" class="header-part2"><tr><td><div class="headerdisplayname" style="display:inline;">To: </div>test1@kokkini.net</td></tr></table><br>

<html><head>

    <meta http-equiv="content-type" content="text/html; ">
  </head>
  <body><div class="moz-text-html" lang="x-unicode">
    <p>Three images</p>
    <p>1: copy pasted from another email</p>
    <p><img src="EmbeddedImages-7/0.jpg" alt=""></p>
    <p>2: file dragged &amp; dropped inline</p>
    <p><img src="EmbeddedImages-7/1.jpg" alt=""></p>
    <p>3: as attachment</p>
    <p>Kim<br>
    </p>
  


</div><br><hr><br><div style="font-size:12px;color:black;"><img src="data:image/gif;base64,R0lGODdhDwAPAOMAAP///zEwYmJlzQAAAPr6+vv7+/7+/vb29pyZ//39/YOBg////////////////////ywAAAAADwAPAAAESRDISUG4lQYr+s5bIEwDUWictA2GdBjhaAGDrKZzjYq3PgUw2co24+VGLYAAAesRLQklxoeiUDUI0qSj6EoH4Iuoq6B0PQJyJQIAOw==">

<ul><li><a href="Attachments-5/folder.jpg">Attachments-5/folder.jpg</li></a></ul></div><div class='' ></div></body></html> exportTools.js:1252:16
```

**Comment by waerlogauk** [comment]
The output is unchanged, I am not seeing any debug, do I have to set debug on somewhere?

Firefox is V 68.05.0
IET NG is V 4.0.5 -b10

Looking at the Thunderbird ' Debug Add-ons' I see;
ImportExportTools NG
>>
    Reading manifest: Error processing xpi-name: An unexpected property was found in the WebExtension manifest.

Extension ID
    ImportExportToolsNG@cleidigh.kokkini.net
Internal UUID
    d4585dda-d189-420a-b274-d8d468cd6a4f
<<

**Comment by cleidigh** [comment]
@waerlogauk 
Sorry I was not clear.  The "Debug Console" actually has all the debug output.  Shift-Control-J
will open up a separate window with the console.  You should see something similar to what I posted above.  Note:  there are no fixes yet just more helpto debug.  your export will be unchanged however but I'm hoping to see where the parsing error is storage negating from my looking at your e-mail converted to HTML internally which should hopefully show why the image links are not being detected for you. I have some guesses but nothing concrete yet.

**Comment by waerlogauk** [comment]
@cleidigh Debug info found as instructed !
```
attachment name folder.jpg exportTools.js:1084:17
save embedded images exportTools.js:1207:14
<html>

<head>

<title>more image tests</title>

<link rel="important stylesheet" href="chrome://messagebody/skin/messageBody.css">

</head>

<body>

<table border=0 cellspacing=0 cellpadding=0 width="100%" class="header-part1"><tr><td><div class="headerdisplayname" style="display:inline;">Subject: </div>more image tests</td></tr><tr><td><div class="headerdisplayname" style="display:inline;">From: </div>&quot;G.Rixon&quot; &lt;gargith@gar.waerloga.co.uk&gt;</td></tr><tr><td><div class="headerdisplayname" style="display:inline;">Date: </div>11/02/2020, 11:25</td></tr></table><table border=0 cellspacing=0 cellpadding=0 width="100%" class="header-part2"><tr><td><div class="headerdisplayname" style="display:inline;">To: </div>test1@kokkini.net</td></tr></table><br>

<html><head>

    <meta http-equiv="content-type" content="text/html; ">
  </head>
  <body><div class="moz-text-html" lang="x-unicode">
    <p>Three images</p>
    <p>1: copy pasted from another email</p>
    <p><img src="imap://gar%40waerloga%2Eco%2Euk@waerloga.co.uk:993/fetch%3EUID%3E.INBOX%3E1965?part=1.1.2.2&filename=ifoobchpcpknbdgk.jpg" alt=""></p>
    <p>2: file dragged &amp; dropped inline</p>
    <p><img src="imap://gar%40waerloga%2Eco%2Euk@waerloga.co.uk:993/fetch%3EUID%3E.INBOX%3E1965?part=1.1.2.3&filename=indgokfhgefjaaem.jpg" alt=""></p>
    <p>3: as attachment</p>
    <p>Kim<br>
    </p>
  


</div><br><hr><br><div style="font-size:12px;color:black;"><img src="data:image/gif;base64,R0lGODdhDwAPAOMAAP///zEwYmJlzQAAAPr6+vv7+/7+/vb29pyZ//39/YOBg////////////////////ywAAAAADwAPAAAESRDISUG4lQYr+s5bIEwDUWictA2GdBjhaAGDrKZzjYq3PgUw2co24+VGLYAAAesRLQklxoeiUDUI0qSj6EoH4Iuoq6B0PQJyJQIAOw==">

<ul><li><a href="Attachments/folder.jpg">Attachments/folder.jpg</li></a></ul></div><div class='' ></div></body></html> exportTools.js:1208:14
search mailbox

**Comment by cleidigh** [comment]
@waerlogauk 
awesome.  my guess was correct.  your image sources point to "imap"  while I understood that this change to "mailbox"  after 60.x  I guess it can be either.  the good thing is this is easy to fix.  I will post a beta and like it here.  I really appreciate the debugging help because I could never reproduce it it's really tricky.  it is Valentine's Day so I better not be on the computer when my wife gets home!
I will post tomorrow.

@cleidigh

**Comment by cleidigh** [comment]
@jessejmorrow 
@waerlogauk 
okay I think I got it...

https://github.com/thundernest/import-export-tools-ng/blob/import-tests/xpi/import-export-tools-ng-4.0.5-b11-tb.xpi
let me know!

**Comment by waerlogauk** [comment]
@cleidigh 
The debug changed only on the last line, which now reads
>> search mailbox & imap <<

**Comment by cleidigh** [comment]
@waerlogauk 
Well yes because the "fix" was really a bug ;-)
in my attempt to rush it I screwed it up. but the good news is now I know the root cause.
The image pointers in the HTML reference mailbox:///  for POP accounts, imap:// for IMAP.
Somehow my test account, misconfigured a while ago completely throwing me off.
I was now able to test and reproduce the error before the fix.

https://github.com/thundernest/import-export-tools-ng/blob/import-tests/xpi/import-export-tools-ng-4.0.5-b12-tb.xpi
@cleidigh

**Comment by waerlogauk** [comment]
@cleidigh 
@jessejmorrow 
That did it, All good now.

**Comment by cleidigh** [comment]
@waerlogauk 
Excellent !  appreciate your patience and testing. It took longer than it should have but that's usually the case.
I am hoping to close up a few more bugs and do a release this week.

Cheers
Christopher

**Comment by jessejmorrow** [comment]
Sorry I'm so late on this chain after my initial post. I have been away from email for some days.

Thanks for tracking this down and fixing this!

Question: If I update to the latest version with this fix will it undo the attachments folder name by date-time you had coded for me earlier?

Or perhaps I can just copy over the one magical line of code that changed the name from "Attachments-1" to "20200222-1352"?

ML, Jesse

**Comment by cleidigh** [comment]
@jessejmorrow 
Just saw your post, good to see you are back.
Two questions:
1 - I cannot seem to find where and how we dealt with the last issue ? Did we not put that fix in the last Release?
2 - if you are interested check out #75 on the new filename options/Beta pointer

Since you are a "superuser" I think you'll like it and would like your feedback...
@cleidigh

**Comment by cleidigh** [comment]
@jessejmorrow 
okay I found it.  we mixed two items in #13 .
the filename of the attachment directories kind of got lost in the shuffle.  I think for backwards compatibility I will add an option to use the date .  what do you think of using the same date format as specified by the new custom date option?

**Comment by jessejmorrow** [comment]
@cleidigh 

Yes, the custom date field is great! As long as it allows yyyymmdd-tttt, which it looks like it does.

Yes, you are correct. I would be wanting to do the same date naming with the embedded images. For my use, I wouldn't even mind if the attachments and embedded ended up in the same folder. But that may not be a desirable behavior for everyone. I like it that way as then you have the HTML file and then all linked objects are in a single folder. Similar to if you were to save a webpage using Chrome and used the "Webpage, Complete" options which would also download all the links and images into a single "links" folder. But if you don't want to go that route, it could be 202002022-1422-Attachments and 20200222-1422-Embedded.

Or better yet, if the custom folder/date had independent settings for the attachments and embedded images, with the defaults set to "Attachments" and "Embedded", then I could just sent BOTH to "yyyymmdd-tttt" and it would dump both items in to the same date-named folder!

Then you would have solved all possible folder naming desires.

@jessejmorrow

**Comment by cleidigh** [comment]
@jessejmorrow 
I can do the embedded image naming the same way.  I think I better hold off a few more than that.
Question:
Before we have the date as a suffix above you have it as a prefix which is better?
Eventually I could have a more complex option.

**Comment by jessejmorrow** [comment]
@cleidigh <https://github.com/cleidigh>

Not sure if we are fully talking about the same thing.

For me, I always name the HTML files as:

date-time  from_subject.html

And then the attachments folders as:

date-time

So neither a prefix or suffix, just date and time. May not suit everyone but the cool thing about it is that it is very easy to quickly see which folder goes with which HTML file as they start with the exact same first 10 characters: 20200222-1755

Jesse

**Comment by cleidigh** [comment]
@jessejmorrow 
Yes, I want to make sure we are on the same page.
Let's continue this in #78  I created so we can track appropriately

**Comment by cleidigh** [comment]
Fixed : #84

**Comment by jessejmorrow** [comment]
Awesome! I’ll check it out.

@jessejmorrow

**Comment by cleidigh** [comment]
Added:
4.1.0
