### ISSUE TITLE
Extended filename format: add suffix, custom date, full formatting 

### ISSUE THREAD

**Issue by cleidigh** [thundernest/import-export-tools-ng#75]
@JF1313
@artofit
@tripleee 

Covers:
#58 
#67

I am capturing several related requests for enhanced filename formatting.  Because there are so many possible date and time formats the only sensible thing is to use the standard gnu date format strings as a new option.  I already have a library I am using in another extension for this.

To not change too many things I propose the following for comment/suggestions:
- Add a suffix option (can be used and referenced in the extended format as {suffix}
- Remove "Add Time to Date" - accomplish with custom date or Date+Time in drop Down
- Add Custom Date format with all the bells and whistles (will have cheat sheet)
- Extended Filename Option:
  - Fully customizable including any static text (excluding illegal characters)
  - Use template placeholders:  {subject}, {date}, {dateCustom}, {index}, {sender}...et cetera

Below are some mockup screenshots, Not tweaked/aligned yet
Please comment !

![image](https://user-images.githubusercontent.com/25272315/74072985-afd4a880-49d6-11ea-9536-c91efc8bc1cc.png)

![image](https://user-images.githubusercontent.com/25272315/74073034-d4c91b80-49d6-11ea-8035-c0afc774f57c.png)

**Comment by artofit** [comment]
In the date I see in your mock up:
%Y-%m-%a %T
Remarks:
1/ %Y, if it is meant to be yyyy? 
2/%a for the days, wouldn't it be clearer %D?
3/%T does it mean hh:mm ss or hh:mm or hhmmss?
I suggest to state as
%YYYY-%MM-%DD %hh:%mm %ss
or simply
YYYY-MM-DD hh:mm ss

SEE also: https://www.geeksforgeeks.org/javascript-date-toisostring-function/

**Comment by tripleee** [comment]
@artofit The standard format strings use a single letter code for each format, `%Y` does stand for a four-digit year (and lower case `%y` would be two digits). You can look them up in the GNU `date` documentation, for example.

**Comment by cleidigh** [comment]
here is the link to the library using to see all the options:
https://thdoan.github.io/strftime/
@cleidigh

**Comment by cleidigh** [comment]
@jf1313 
@artofit 
@tripleee 

I have just posted b13.  This includes the various fixes I have done so far as well as  importantly these new formatting options.  Any feedback or testing would be great. I have some error checking To do but working pretty well.
https://github.com/thundernest/import-export-tools-ng/blob/import-tests/xpi/import-export-tools-ng-4.0.5-b13-tb.xpi

For the extended formatting option you can use the following tokens as well as  other legal characters: 

${prefix}
${smartname}
${sender}
${recipient}
${subject}
${date}
${dateCustom}
${index}
${suffix}

Note:  I have removed to the time option which can be accomplished with the custom date
and I have made the default for the custom date option to  the original date  plus time.
See this readme for date options:
https://github.com/thdoan/strftime

![image](https://user-images.githubusercontent.com/25272315/75103275-8adf5880-55c6-11ea-81b2-8d9ca711b2d0.png)

**Comment by cleidigh** [comment]
All
I have posted a beta (>=b2)
currently:
https://github.com/thundernest/import-export-tools-ng/blob/v4.1.0-update/xpi/import-export-tools-ng-4.1.0-b2-tb.xpi

This has all of the bug fixes as well as enhancements.  
For completion I still have to do the translations as well as some more UI tweaks.

I even through an Easter Egg in:
It is possible to set options strings for the attachment folder names
The only limitation is that these must be set within the config editor.

pref("extensions.importexporttoolsng.export.attachments.filename_extended_format", "");
pref("extensions.importexporttoolsng.export.embedded_attachments.filename_extended_format", "");

If the extended format is blank , the existing format name "Attachments"," Embedded Images"
Will be used.  Otherwise you can use the extended filename formatting with all the bells and whistles.

I am sure I am still several days from Release, any feedback before that would be great.

**Comment by artofit** [comment]
Thanks
Well, stupid but I wanted to try with this beta 4.1 release under Linux, but I do not see how to add this beta xpi as an addon after having downloaded, only search on the addons Thunderbird repository.

**Comment by cleidigh** [comment]
@artofit 
I just finished creating a L Mint virtual machine.  I also installed Thunderbird 68.5.0
you can install local XPi files using the gear menu option install from file

![Screenshot from 2020-03-01 19-39-27](https://user-images.githubusercontent.com/25272315/75637569-4b7fc000-5bf5-11ea-885f-ab41c946f5d5.png)

**Comment by cleidigh** [comment]
anybody have a chance to try this?
I am working on the last UI tweaks and the translations.
maybe I can get it out this week

**Comment by artofit** [comment]
Not finished testing, but

In the addons>ImportToolsNG I selected custom date (%Y%m%d%H%M)
If I do a export all as html with attachment, it does produce the index.html file, but in this index file the date is still the default one(old style) and not the custom date format.
this is according to me the major "annoyance" which lead me to this feature bug report

**Comment by cleidigh** [comment]
@artofit 
Thanks for doing some testing.  I am also doing some tweaks to the index and I actually thought about the date.  What I wondering us if people want the same format for the files and in the index date.
any thoughts?  I almost think I have to give a choice regular date  or the custom date.  I might have this as a preference option without adding to the UI yet.  I have done the same thing to allow custom filenames for the attachment folders.

**Comment by cleidigh** [comment]
@artofit 
okay was feeling good and went ahead and added this as another Easter egg option because I cannot do anything more on the UI or I will go crazy!
Set the index date format in about:config :
extensions.importexporttoolsng.export.index_date_custom_format
(defaults to "" which uses the original format)
unlike filenames you can use any characters including the ':'
I will try to release by Monday so any feedback would be great
Cheers
![image](https://user-images.githubusercontent.com/25272315/76137578-c2a9bf80-600c-11ea-8fa2-eb3c8bf50426.png)

**Comment by artofit** [comment]
Comments:
1/ ImportToolsNG ought to indicate its version, I'm testing import-export-tools-ng-4.1.0-b7-tb.xpi
2/ I believe the config menu ought to be part of Export/Imports menus
3/ how did you get the index.html with such date format??? I failed to.
Note that within your index.html you missed to change the "title date" as:
Inbox (20200703-12:39:54)

**Comment by cleidigh** [comment]
@artofit 
thanks for testing!
1- yes I think I will add it to the options dialog
2- options are currently in the Tools/IET/Options Menu - I could probably squeeze into the other menus
3- you need to set the preference within the config editor:
extensions.importexporttoolsng.export.index_date_custom_format
I did not add this to the UI for the reasons above probably later with the new index option Tab
I will fix the title date. Thanks
You get to the config editor from Tools/Options ( button at bottom of Advanced options):

![image](https://user-images.githubusercontent.com/25272315/76153935-b15ec280-60a1-11ea-99ab-c3733d7d3821.png)

**Comment by artofit** [comment]
On mine TB 68.5 I do not see Config Editor Menu.
Anyhow, this ought to be in the ImportExportsNG config menu
![TB685](https://user-images.githubusercontent.com/7029627/76200731-6bfdda80-61f2-11ea-9675-4576136edf66.png)

**Comment by cleidigh** [comment]
@artofit 
The config editor is under the advanced section after selecting Tools/Options from the main menu.
Yes these options are not currently in the UI, I added these features at the last moment and I cannot do anymore UI changes .  I will probably create new options tab for index options in the next version.  in the meantime you have the functionality.

![image](https://user-images.githubusercontent.com/25272315/76273425-35f14280-6254-11ea-98b0-2adbbdc0083b.png)

![image](https://user-images.githubusercontent.com/25272315/76273336-ff1b2c80-6253-11ea-93b9-0e9d4e49bf2c.png)

**Comment by cleidigh** [comment]
Added:
4.1.0

**Comment by artofit** [comment]
Cleidight.
Thanks for version 4.1
I've been off for a while.

I do not see how to have the custom date format in the index.html file has presented in:
https://github.com/thundernest/import-export-tools-ng/issues/75#issuecomment-596050374

**Comment by cleidigh** [comment]
@artofit 
good to see you are back
I added a section for new experimental options in the help, check everything out there.
@cleidigh

**Comment by JF1313** [comment]
Christopher, you've done a remarkable job on the ImportExportTools NG for Thunderbird. Thank you.

I'm curious if there's a way to have Thunderbird automatically convert an email to PDF if certain rules are met such as the email domain, sender name, etc.

If you have suggestions as to how to do this, please let me know.

Thanks.

Jeffrey
