### ISSUE TITLE
Add option to add customDate to attachment directory names

### ISSUE THREAD

**Issue by cleidigh** [thundernest/import-export-tools-ng#78]
New option:
attachment_dir_add_date_custom_format

Uses extended filename custom date format
Ref: #13

**Comment by cleidigh** [comment]
@jessem
I was only using the word prefix as in the front of, not to prefix text option.
My code before created filenames like:
Attachments-202010101100
I think possibly Judy did something differently yourself?  No "Attachments" ?
For this Release would you be good with:
202010101100-Attachments
This will maintain your sort order but still be similar to the original.
Later when I catch up I can possibly do the custom extended formatting for the attachment folders.

**Comment by cleidigh** [comment]
I have some ideas on this option.  stay posted.

**Comment by cleidigh** [comment]
@jessejmorrow
Check out #75 
I think you will like my last minute little addition...

**Comment by jessejmorrow** [comment]
What was the trick for having the custom date prepended to the Attachments and EmbeddedImages folders? I thought I confirmed this was working when you originally gave #75, but now there is no prepended date anymore.

**Comment by cleidigh** [comment]
@jessejmorrow 
hey have not heard from you for a while
you were using:
even through an Easter Egg in:
It is possible to set options strings for the attachment folder names
The only limitation is that these must be set within the config editor.

pref("extensions.importexporttoolsng.export.attachments.filename_extended_format", "");
pref("extensions.importexporttoolsng.export.embedded_attachments.filename_extended_format", "");

If the extended format is blank , the existing format name "Attachments"," Embedded Images"
Will be used. Otherwise you can use the extended filename formatting with all the bells and whistles.

yes?
I have added a few more things . maybe I broke something
which beta are you using?  b15 is the latest where I have added some hot key support.

**Comment by jessejmorrow** [comment]
Hi Chris,

Yes, I disappear while you and others did the heavy lifting!

Okay, so I found the configurations and they are working. Except I'm not sure what to use to get the timestamp?

I tried ${date}-${time}, but this gives me a folder named "20200409-${time}". Is there an extended format string for the time?

Jesse

**Comment by cleidigh** [comment]
@jessejmorrow 
b15 has a start to a user guide
from the options/file names tab has Links to help
there is a table for all of the date/time percent sequences
there is also a table for file name tokens
the ${date_custom} allows you to use all the sequences (except illegal characters)
you set that in the custom date field
![image](https://user-images.githubusercontent.com/25272315/78945915-73cdca80-7a8f-11ea-9dd1-750ef730a8fc.png)

the custom date above has both date and time

**Comment by jessejmorrow** [comment]
Brilliant! It works beautifully!

BTW, the help text says "${date custom}" without the underscore, which doesn't work. Should be changed to "${date_custom}", as you gave me above.

Thank you!
Jesse

**Comment by cleidigh** [comment]
excellent
yeah, I keep getting distracted with new requests and the documentations is stalled

**Comment by cleidigh** [comment]
Added:
4.1.0
