### ISSUE TITLE
Options dialog fails on TB 69

### ISSUE THREAD

**Issue by dillenger** [thundernest/import-export-tools-ng#8]
document.createElement is deprecated, you now have to use document.createXULElement:

```
--- /old/ImportExportToolsNG/chrome/content/mboximport/mboximportOptions.js
+++ /new/ImportExportToolsNG/chrome/content/mboximport/mboximportOptions.js
@@ -33,7 +33,7 @@
 	var charsetList = IETprefs.getCharPref("extensions.importexporttoolsng.export.charset_list");
 	var charsetItems = charsetList.split(",");
 	for (var i = 0; i < charsetItems.length; i++) {
-		var menuitem = document.createElement("menuitem");
+		var menuitem = document.createXULElement("menuitem");
 		menuitem.setAttribute("label", charsetItems[i]);
 		menuitem.setAttribute("value", charsetItems[i]);
 		charsetPopup.appendChild(menuitem);
```

[ImportExportToolsNG@cleidigh.kokkini.net.zip](https://github.com/thundernest/import-export-tools-ng/files/3464032/ImportExportToolsNG%40cleidigh.kokkini.net.zip)

**Comment by cleidigh** [comment]
@dillenger 
Thanks, I purposely avoided 69 to get 68 out more quickly.
now on my list of to-do's

**Comment by cleidigh** [comment]
@dillenger 
FYI - since you are running bleeding edge, I just posted an initial beta addressing this and couple things for 68.  I'm holding off for a few more issues before updating.

Fixed in v4.0.1-b1 WIP (under beta  branch XPI)

**Comment by cleidigh** [comment]
@dillenger 
Thanks
FYI-update waiting for review

**Comment by dillenger** [comment]
You're welcome
