### ISSUE TITLE
Headings should have a transparent/grey (not white) background

### ISSUE THREAD

**Issue by ovari** [thundernest/import-export-tools-ng#80]
`Customized format for filenames` and `Misc` should have a grey/transparent (not white) background as shown in the image below:
![image](https://user-images.githubusercontent.com/17465872/75108623-0861a200-5675-11ea-84ac-81a09220e61a.png)

Linux Mint 19.3 Cinnamon 64-bit
Thunderbird 68.4.1 (64-bit)
ImportExportTools NG 4.0.5-b15

Hint: https://github.com/thundernest/quicktext/issues/147

What do you think?

Thank you

**Comment by cleidigh** [comment]
@ovari 
Thanks.
I will have to see if I can figure out the non Windows CSS.
I will let you do as it would be helpful for you to test as I do don't have a *nix

**Comment by cleidigh** [comment]
@ovari 
I am using the same formatting techniques for fixing the groupbox styling as I do with LocalFolders.
Does LocalFolders group box style correctly on Cinnamon ?

**Comment by ovari** [comment]
`Menu Bar` → `Tools` → `Add-on Preferences` does not show `LocalFolders`; hence, there are no group box style to compare. However, a LocalFolders dialog box is shown below:
![image](https://user-images.githubusercontent.com/17465872/75189351-195c0180-57a2-11ea-9299-e29d0e305e48.png)

Hope this helps.

**Comment by cleidigh** [comment]
@ovari 
I think this addresses the background , it now looks right on OS X.
If you can check out cinnamon that would be great.
I still have to figure out how to disable the text boxes, still an issue
https://github.com/thundernest/import-export-tools-ng/blob/v4.1.0-update/xpi/import-export-tools-ng-4.1.0-b3-tb.xpi

**Comment by ovari** [comment]
The heading are strike-through.

![image](https://user-images.githubusercontent.com/17465872/75597345-0ff7cf80-5ae9-11ea-8919-e726838479f9.png)

**Comment by cleidigh** [comment]
@ovari 
Thanks
I just read that groupbox is styled differently on Linux
certainly there are some oddities still
But... I am almost complete installing mint, slow process for me but almost there
I will then be able to check these out myself, and not bother you to check!
@cleidigh

**Comment by ovari** [comment]
[Linux Mint 19.3 Cinnamon](https://linuxmint.com/edition.php?id=274) is easier to install than LMDE (Linux Mint Debian Edition). If you need any help, email us and we can talk on [Jami](https://jami.net/). Cheers

**Comment by cleidigh** [comment]
@ovari 
Thanks for the offer, I have already installed a Linux Mint 19.3 .  I went that way based on your prior e-mails.  I have to run it in a virtual machine AND access with RDP otherwise my Dragon dictation software cannot send keystrokes to it.  The command line set up without that is terribly slow but I am most completely set up.

As I mentioned above I found out that groupboxes on Linux do not have an outline or border.
I think it looks better with the board and matches other systems.  I will try CSS if not HTML fieldset
@cleidigh

**Comment by ovari** [comment]
It would be better to have a native look in GNU/Linux systems. If that means not to have a border, so be it.

**Comment by cleidigh** [comment]
Fixed: 
v4.1.0-b6

**Comment by cleidigh** [comment]
Added:
4.1.0
