### ISSUE TITLE
Grey out items in the Filenames tab

### ISSUE THREAD

**Issue by ovari** [thundernest/import-export-tools-ng#81]
Selecting the `Filenames` tab shows:

![image](https://user-images.githubusercontent.com/17465872/75109247-cc7b0c80-5675-11ea-9eae-49ea978b5182.png)

Should the fields be greyed out as the tickboxes are not selected, i.e.

![image](https://user-images.githubusercontent.com/17465872/75109319-1e239700-5676-11ea-9726-777b98dfce39.png)

Linux Mint 19.3 Cinnamon 64-bit
Thunderbird 68.4.1 (64-bit)
ImportExportTools NG 4.0.5-b15

What do you think?

Thank you

**Comment by cleidigh** [comment]
Fixed: 
v4.1.0-b6

**Comment by cleidigh** [comment]
Added:
4.1.0
