### ISSUE TITLE
valign=center (centre) the field labels + some suggestions

### ISSUE THREAD

**Issue by ovari** [thundernest/import-export-tools-ng#82]
### valign=center field labels

In `Filenames` tab: `Custom Date:`, `Format:`
![image](https://user-images.githubusercontent.com/17465872/75109406-b9b50780-5676-11ea-93d0-febce625153d.png)

In `Tests` tab: `Cycles :`, `# Folders :`, `# Nessages/Fld :`, `Message Size(b) :`
![image](https://user-images.githubusercontent.com/17465872/75109436-2d571480-5677-11ea-9050-6daa74fa47ab.png)

### Other suggestions
1. Remove the space before the colons.
2. Move the `(b)` after the field, drop the brackets `()` and type `bytes` (if that what it is). This would be consistent then with the `Misc` tab's `characters` units
3. Appending 1-character ellipses to the `Browse` label strings so the buttons change from `Browse` buttons to `Browse…` (or `Choose…` if using macOS)
```
        { PLATFORM() ->
            [macos] Choose…
           *[other] Browse…
        }
```
https://transvision.mozfr.org/?recherche=Browse%E2%80%A6&repo=gecko_strings&sourcelocale=en-US&locale=hu&search_type=strings
4. Replace `#` with `Number of`
5. Replace `Fld` with `Folder`

What do you think?

Thank you

**Comment by cleidigh** [comment]
Fixed: 
v4.1.0-b6

**Comment by cleidigh** [comment]
Added:
4.1.0
