### ISSUE TITLE
Difference between Import Messages and Import All Messages actions

### ISSUE THREAD

**Issue by zhengpd** [thundernest/import-export-tools-ng#83]
I'm new to ImportExportTools NG and wondering if any difference between `Import Messages` and `Import all messages from a directory` actions. Are they the same if I want to import all EML files from a folder?

**Comment by cleidigh** [comment]
@zpdcodes 
Thanks for using the extension and the issue post!
I still need to finish user guide to explain things like this.
Basically there is very little difference.  Both the options you reference concern EML message importation.  The basic differences that the first `Import Messages` allows you to select EML messages to be imported from a particular directory.  The second option allows you to import based on a folder selection.  Again both pertain to EML e-mail files.

The original extensions grew over a large amount of time and some of the options like this are slightly redundant and therefore confusing.  You are not alone in this respect.  One of my upcoming releases will try to address this confusion.  I also need to do the user guide.
@cleidigh

**Comment by zpdcodes** [comment]
@cleidigh Thanks for the clear explanation and efforts on the project.
