### ISSUE TITLE
Incorrect German translation for option "Overwrite the mbox files with the same name in the destination directory"

### ISSUE THREAD

**Issue by dipgithub** [thundernest/import-export-tools-ng#93]
The option "Overwrite the mbox files with the same name in the destination directory" is translated to German "Dateien gleichen Namens im Zielverzeichnis überschreiben" but this translation means "Overwrite files with the same name in the destination directory". The translation therefore creates the impression that also index.html files are overwritten when creating an index of selected messages, which is not the case. I always thought the option does not work since I use only the create index feature.
So either the German translation should be changed to "Mbox-Dateien gleichen Namens im Zielverzeichnis überschreiben" or the functionality should be changed that index.html files are also overwritten if this option is set.

**Comment by cleidigh** [comment]
thanks sounds good

**Comment by cleidigh** [comment]
Fixed:
4.1.0-b25
