### ISSUE TITLE
68.6.0 TB compatibility

### ISSUE THREAD

**Issue by LupoAlberto74** [thundernest/import-export-tools-ng#99]
I had to disable this fantastic addons because it make looping my TB. I run on a windows 10 OS and i disabled all the other addons, except lightining 68.6.0 and sogo connector 68.0.1 (I absoluterly need them for work).
Moreover the TB addons page shows that IET-NG is not compatible with the current version of my TB, so... have I to expect a new version or may there is some workaround that I could put in place?
I really like to activate again this addon... :p

**Comment by LupoAlberto74** [comment]
I know, I am sorry for beeing so inaccurate! what i can do is to show you that with the addon activated sometimes I get TB running the update ever and ever (but no new mails are getting down)
![image](https://user-images.githubusercontent.com/63091883/78567692-5c89a580-7821-11ea-955d-de162bfe23cd.png)

I can work for some time, the I get TB locked. If I deactivated the addon and starr again TB, everything is working well, in real time, with any loop or freeze....

I can be able to let you connect by teamviewer or else, should you need. 
Thanks, 
Alberto

**Comment by cleidigh** [comment]
@LupoAlberto74 
I am still a bit confused about what is going on.
Where are you located?  maybe the teamviewer is the way to go as I really need more information.
Christopher

**Comment by LupoAlberto74** [comment]
You are right Christopher.  
I am still having the problem, but I suppose that is not your addon! I tried again again and again to disable every addon and to reactivate a single one and I must say that - probably - another addon is causing the freeze/loop issue. So, I do apologize and thank you for the time you spent for my issue! 
And thanks again for your so useful addon! 
Alberto
